### ISSUE TITLE
Contributor concensus: moving from GPLv3+ to MIT

### ISSUE THREAD

**Issue by jarun** [jarun/googler#102]
The current discussion relates to all contributors to `googler`.

We had been using the GPLv3+ license model for `googler` so far. At this point, we feel a more permissive license would do it justice. The proposal was raised by @zmwangx at #100. As the maintainer and active contributor to `googler` I am completely aligned to him given the scope and application of `googler` as a utility.

I request the following contributors for their opinion and note of (dis)agreement so that we can bring this activity to a logical closure.

@shaggytwodope 
@Narrat 
@ibaaj 
@jeremija 

We have contacted @henux over email as he doesn't seem to be active on GitHub anymore.

We'll wait for a period of 1 week from now for the responses from the contributors. In case there is none from certain contributors, we'll conclude with what we have on the plate.

**Comment by shaggytwodope** [comment]
I'm all for it. Just for hell of it tho, which MIT license you going with?

**Comment by zmwangx** [comment]
https://opensource.org/licenses/MIT

**Comment by Narrat** [comment]
No particular feelings about the change. Do it if you want to, although I'm not sure if this change is really necessary.
Even after reading #100 I don't really see the gain with switching as the biggest point for switching is ruled out. (At least as I understand it. Maybe I'm missing some point, which is possible as my knowing of the licenses is rather basic)

**Comment by jarun** [comment]
> as the biggest point for switching is ruled out

@Narrat would you please explain which point you are referring to here?

**Comment by Narrat** [comment]
I was referring to the sentence
```
It's not like anyone's ever going to incorporate our code (definitely not in closed-source products as far as I could imagine), (...)
```
in #100 .
If it's unlikely, why switching (let aside the point with the personal preferences), is my current thought about this.
Still not a vote against the switch, it's just how I perceive it.

**Comment by zmwangx** [comment]
I did not explain well the benefits in #100, because the benefits of a permissive license is obvious in the right mindset.

> If it's unlikely, why switching

1. Unlikely != impossible, especially in the open source setting. Some people (me included) will be extremely hesitant to make use of GPL code even if the derivative work is fully open source, because it dictates their license. I don't want to dictate anyone's license.

2. There's simply no reason to copyleft the code, and it's a conceptual thing. Even FSF, despite being paranoid most of the time, only advises copyleft for relatively large projects.

3. If we want to switch, doing it sooner is always better than later.

**Comment by jarun** [comment]
I have decided to maintain a status quo wrt. licensing. Reasons:

- I can't state honestly that I'll be very happy if a closed source product uses `googler` without a note of thanks.
- We already have our package accepted in Debian Sid and I want to avoid the situation of having 2 licenses in 2 places (looks shady) or following up with Debian to get things straight.

Thanks for your suggestions and opinion on this guys!
