### ISSUE TITLE
Discussion: Switch from http.client to urllib.request

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#104]
I've been improving upon existing code without thinking too much, but it just occurred to me: why are we using `http.client` instead of `urllib.request` and handling all that connection and redirection stuff manually? I have the alternative implemented in [the `http-to-urllib` branch](https://github.com/zmwangx/googler/commits/http-to-urllib) (based on `oo-refresh` in #99). In particular, quoting https://github.com/zmwangx/googler/commit/0e4e938f2f4c3be16efd70f55b0793d813c214d2:

```
urllib.request is higher level than http.client and does almost
everything we need automatically (redirection, for instance). It even
recognizes users' proxy settings in the https_proxy env var (when we
don't set a proxy explicitly). Most importantly, it saves a hell lot of
code and maintenance.

The only downside is that `Connection:close' is hardcoded in each
request* so we can't keep the connection alive. I doubt that will cause
any noticeable delay on any reasonable network in a country or region
where Google is usable.

Note that I'm building an URL opener just to be forward-looking. We
could also have used urllib.request.urlopen for the moment.

* See https://docs.python.org/3/library/urllib.request.html:

  > urllib.request module uses HTTP/1.1 and includes Connection:close
  > header in its HTTP requests.
```

> Most importantly, it saves a hell lot of code and maintenance.

The diff stat says it all: 

    1 file changed, 31 insertions(+), 204 deletions(-)

And the logic is cleaner: we no longer have the awkwardness of not 200 after the *first* redirection, and stuff like that.

In general, I think programmer time is more valuable then a few milliseconds of user time.

**Comment by zmwangx** [comment]
See https://github.com/zmwangx/googler/commit/665a9c2b431a0e45028cd25ad91c93b034c18ae5. Removed more stuff.

    1 file changed, 42 insertions(+), 242 deletions(-)

**Comment by jarun** [comment]
I don't think the current `http.client` implementation have any serious bugs in it. There are places where we have hard-coded minor stuff but it's a completely working implementation. I am inclined to retain the 200 deletions as long as it's not buggy.

> The only downside is that `Connection:close' is hard-coded in each request

So we are going to lose persistent connections. Going by default this means we open and close a new connection for 10 results. Please, no.

> it even recognizes users' proxy settings in the https_proxy env var

It's simple to implement or maintain (if you already have it in the proxy-related PR)

> I think programmer time is more valuable then a few milliseconds of user time.

As of now, we are not spending any time to maintain this code. If we go with `urllib.request`, this won't be the last time we add delay. The worst thing about delays is - they add up.

It's impossible to conclude whose time is more important. There are just too many variables. I use `googler` myself for every search that involves google ;).

Let's not move from `http.client`.
