### ISSUE TITLE
"Connection blocked due to unusual activity" on Travis

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#106]
This is getting annoying. Either Google hardened their rate limiting, or something. We used to be able to go through six jobs within the matrix, each issuing 100 queries; now we can't even get through three. Basically all Travis builds that actually test googler now fail.

Of course there is the dream of unit testing, but in the mean time, we probably need to reduce the number of queries, or something.

**Comment by jarun** [comment]
I guess `google` has blacklisted the Travis range of IPs. Build fails constantly. I think even the first query filed in the last instance.

Also, how about gracefully catching this blocked exception that we raise?

**Comment by zmwangx** [comment]
> I guess Google has blacklisted the Travis range of IPs. 

Cool, just what we need. I've set the `CI_SKIP_TEST` env var for now.

> Also, how about gracefully catching this blocked exception that we raise?

That was an intentional change. `--debug` enables the traceback dump for all uncaught or re-raised exceptions terminating the program, whereas the traceback is always suppressed and replaced with an `[ERROR] Exception error msg` under normal operation.

I think it's neither justifiable nor worthwhile to make an exception for this case.

**Comment by jarun** [comment]
> I've set the CI_SKIP_TEST env var for now.

:+1: 

> I think it's neither justifiable nor worthwhile to make an exception for this case.

Agreed.

**Comment by zmwangx** [comment]
By the way, we'll see if we're permablocked, but if we're not, we can try to explicitly sleep 5 or 10 seconds after each request.

**Comment by jarun** [comment]
Try with 1 first ;)

**Comment by zmwangx** [comment]
1 wouldn't help much because each request takes ~1s.

**Comment by jarun** [comment]
I'm saying check if the first one works...
In the meantime:
https://groups.google.com/forum/#!forum/daily-web-proxies

**Comment by jarun** [comment]
can't open now...

**Comment by zmwangx** [comment]
You mean like `https://www.collegeonlinetwohundredfiftyfive.xyz/`?

```
nmap -Pn www.collegeonlinetwohundredfiftyfive.xyz

Starting Nmap 7.12 ( https://nmap.org ) at 2016-06-07 22:53 PDT
Nmap scan report for www.collegeonlinetwohundredfiftyfive.xyz (104.18.33.167)
Host is up (0.043s latency).
Other addresses for www.collegeonlinetwohundredfiftyfive.xyz (not scanned): 104.18.32.167
Not shown: 997 filtered ports
PORT     STATE SERVICE
80/tcp   open  http
443/tcp  open  https
8080/tcp open  http-proxy

Nmap done: 1 IP address (1 host up) scanned in 66.17 seconds
```

```
googler -p www.collegeonlinetwohundredfiftyfive.xyz:8080 google
[ERROR] Failed to connect to proxy server www.collegeonlinetwohundredfiftyfive.xyz:8080: Tunnel connection failed: 400 Bad Request.
```

That's not an HTTPS proxy. It does handle HTTP requests over 8080. But then, each day the new fast proxy is this one, so probably just a joke.

**Comment by zmwangx** [comment]
Actually even the HTTP proxy doesn't work (I didn't read the response just now):

```
curl -x collegeonlinetwohundredfiftyfive.xyz:8080 http://google.com
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>DNS resolution error | google.com | CloudFlare</title></title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>
<!--[if lte IE 9]><script type="text/javascript" src="/cdn-cgi/scripts/jquery.min.js"></script><![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1001</span>
          <small class="heading-ray-id">Ray ID: 2afa18a490b60d3d &bull; 2016-06-08 05:55:40 UTC</small>
        </h1>
        <h2 class="cf-subheadline" data-translate="error_desc">DNS resolution error</h2>
      </div><!-- /.header -->

      <section></section><!-- spacer -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>You've requested a page on a website (google.com) that is on the <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_100x" target="_blank">CloudFlare</a> network. CloudFlare is currently unable to resolve your requested domain (google.com). There are two potential causes of this:</p>
            <ul>
               <li><strong>Most likely:</strong> if the owner just signed up for CloudFlare it can take a few minutes for the website's information to be distributed to our global network.</li>
               <li><strong>Less likely:</strong> something is wrong with this site's configuration. Usually this happens when accounts have been signed up with a partner organization (e.g., a hosting provider) and the provider's DNS fails.</li>
            </ul>
          </div>


        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">CloudFlare Ray ID: <strong>2afa18a490b60d3d</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 128.12.252.4</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">CloudFlare</a></span>

  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script type="text/javascript">
  window._cf_translation = {};


</script>

</body>
</html>
```

So just a joke.

**Comment by zmwangx** [comment]
Oh okay, it's actually a web-page based proxy.

**Comment by jarun** [comment]
Doesn't help. I know other avenues... but right now :x: 
Is your proxy related PR in?

**Comment by zmwangx** [comment]
?? #37

**Comment by jarun** [comment]
okies...

**Comment by zmwangx** [comment]
By the way, crazy busy tonight, will talk to you tomorrow.

**Comment by jarun** [comment]
same here. Touche!

**Comment by jarun** [comment]
I need to test this in my den, but `googler` seems to be unusually slow! A fresh query takes 2-3 secs to show results while in FF browser, fresh tab I'm getting results in .38-.40 secs. All queries for google.co.in server.

At least we need to work on speeding up the utility for **slower connections** and optimize wherever possible.

**Comment by jarun** [comment]
Two consecutive searches from FF:
```
`https://www.google.co.in/search?client=ubuntu&channel=fs&q=hello&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=BBpZV7PoAY2P8QfX6JLgDA`

`https://www.google.co.in/search?client=ubuntu&channel=fs&q=hello+world&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=CBpZV7iRGI2P8QfX6JLgDA`
```

The `ei` changes but see the pattern?

**Comment by jarun** [comment]
`ei` stands for engine id.

**Comment by zmwangx** [comment]
> A fresh query takes 2-3 secs to show results while in FF browser, fresh tab I'm getting results in .32-.40 secs.

I don't know, pretty fast for me. You can try to run a profiler with your slow connection.

> On the same system, I can use FF to fetch the results, but not googler! 

This suggests randomizing UA to me.

**Comment by jarun** [comment]
Home connection: 0.62 secs chrome, 1.3+ `googler`.

> This suggests randomizing UA to me.

I used the same UA.

**Comment by jarun** [comment]
Seems fixed.

Relevant commits:
https://github.com/jarun/googler/commit/870217a2fefda6b12e07fa078adb3475c29f71be
https://github.com/jarun/googler/commit/b6aeeaaca6a81e9186f12fcf8fd301976aaccf79
https://github.com/jarun/googler/commit/1606369148b994f810a9862798b89963ce3b6b8a

Relevant build:
https://travis-ci.org/jarun/googler/builds/136619516

**Changes:**
Cookie exchange
The number of queries are set to 30
A gap of 5 seconds between 2 successive queries
