### ISSUE TITLE
More navigation issues

### ISSUE THREAD

**Issue by jarun** [jarun/googler#113]
**`unfilter` should set start to 0**

This should work as per `google` behaviour. When omitted results are included, results are shown from the first page.

**next should not increment start if the last set of results were NIL**

Currently `n` key at omniprompt increments `start` every time. So user needs to press `p` as many times to return to the last set of results.

**Comment by zmwangx** [comment]
Next: intentional. No results on this page doesn't necessarily mean last page, especially when count is low.

**Comment by jarun** [comment]
> especially when count is low

Yes, planning to set the threshold to 5.

**Comment by jarun** [comment]
Unfilter issue fixed at https://github.com/jarun/googler/commit/3b474bb34bdf24b4eead04c88224ac4c61716a1e.
