### ISSUE TITLE
2.5 broken on OS X: module 'socket' has no attribute 'TCP_DEFER_ACCEPT'

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#115]
OS X 10.11.5, Python 3.5.1, googler 2.5:

```python
> /usr/local/Cellar/googler/2.5/bin/googler --debug --noprompt Homebrew
[DEBUG] Connecting to new host www.google.com
Traceback (most recent call last):
  File "/usr/local/Cellar/googler/2.5/bin/googler", line 579, in new_connection
    self._conn.connect()
  File "/usr/local/Cellar/googler/2.5/bin/googler", line 122, in connect
    sock.setsockopt(socket.SOL_TCP, socket.TCP_DEFER_ACCEPT, 1)
AttributeError: module 'socket' has no attribute 'TCP_DEFER_ACCEPT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/googler/2.5/bin/googler", line 1908, in <module>
    main()
  File "/usr/local/Cellar/googler/2.5/bin/googler", line 1882, in main
    repl = GooglerCmd(opts)
  File "/usr/local/Cellar/googler/2.5/bin/googler", line 1471, in __init__
    self._conn = GoogleConnection(self._google_url.hostname, proxy=proxy)
  File "/usr/local/Cellar/googler/2.5/bin/googler", line 530, in __init__
    self.new_connection(host, port=port, timeout=timeout)
  File "/usr/local/Cellar/googler/2.5/bin/googler", line 582, in new_connection
    raise GoogleConnectionError(msg)
__main__.GoogleConnectionError: Failed to connect to www.google.com: module 'socket' has no attribute 'TCP_DEFER_ACCEPT'.
```

**Comment by zmwangx** [comment]
http://linux.die.net/man/7/tcp

Apparently `TCP_DEFER_ACCEPT` is not only not POSIX, but also not available in Linux before 2.4.

**Comment by jarun** [comment]
OK. I'll release 2.5.1 shortly.

**Comment by jarun** [comment]
Closed by mistake.

**Comment by jarun** [comment]
I think we can safely assume either none or very small section of our users are on Linux 2.4. So I'll make this change for OS X only.

I am seeing more that 100 ms gain with this option enabled.

Can you please check if https://github.com/jarun/googler/commit/99c13360d7a75f82ed4d6ee9e721f2c181fe17f8 works for you?

**Comment by zmwangx** [comment]
`TCP_DEFER_ACCEPT` isn't the only problem. `TCP_QUICKACK` is also not available, for instance.

I don't have time to read the code and figure out what each line does, but one should really stick to POSIX. If you want to have separate code for Linux then sure, it's your call; as I said I'll no longer work on new features and this is one, so it won't be my domain.

Here's `tcp(4)` for you: https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man4/tcp.4.html.

**Comment by jarun** [comment]
> I don't have time to read the code

I wanted to know if the version is working for you. Not asking you to review the change.

> it's your call

Yes, I intend to retain the optimizations for Linux given that both are available in the recent versions. Linux 2.4 was released in Jan 2001.

Commit https://github.com/jarun/googler/commit/77fa658ebb3d3992242c0b49c3bbb32adc181a19 has all options disabled for OS X. Please confirm if this works on your system and I'll make the release.

**Comment by zmwangx** [comment]
> I wanted to know if the version is working for you

As said, no. Now it appears to be working.

**Comment by zmwangx** [comment]
> Linux 2.4 was released in Jan 2001.

Nowhere do we mention Linux before Jan 2001 is not supported. The usual way to feature test in python is try catch.

**Comment by jarun** [comment]
> Nowhere do we mention Linux before Jan 2001 is not supported.

I think we can keep arguing on this but it doesn't make practical sense. If someone comes back with reports on kernel 2.4 we'll provide a patch.

> The usual way to feature test in python is try catch.

I didn't want to make extra calls when it's known to fail. I'll re-look at it later.
