### ISSUE TITLE
Unable to integrate with text-based browsers

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#125]
Due to redirecting stdin and stderr unconditionally to `/dev/null`in https://github.com/jarun/googler/blob/dfc988f16c7e17bb691b3ef4e154f17ae5436588/googler#L93-L109 (which IIRC is there to suppress logging of graphical browsers), currently googler can't integrate with text-based browsers like `w3m`:

```
BROWSER=w3m googler -n 3 -d google
[DEBUG] Version 2.6
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&num=3&oe=UTF-8&q=google&start=0
[DEBUG] Cookie: NID=85=0ZPk4CbfrgeZk1YH8HkP5ETEVlEPA8Iah5wr63Nb2LJKRDITbPjbH14B1RksRJDiUOvil3RjWUDEOySNarkAKuVQqMY3kop27vLgHbpAdjrY6IIhZZvsq4m5tjbQW_MUx6wmQE2v0O8B1g
[DEBUG] Response body written to '/tmp/googler-response-nb04dlxs'.

1 Google
https://www.google.com/
Search the world's information, including webpages, images, videos and more. Google has many special features to help
you find exactly what you're looking ...

2 Google Maps
https://maps.google.com/
Find local businesses, view maps and get driving directions in Google Maps.

3 Google (@google) | Twitter
https://twitter.com/google?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor

googler (? for help) 1
[DEBUG] Opening https://www.google.com/
googler (? for help) q
```

(Nothing else appears after `[DEBUG] Opening https://www.google.com/`.)

## Proposed solution

Add a `--disable-browser-output` option to only redirect browser stdin and stdout to `/dev/null` when the option is on; or add a `--enable-browser-output` option, which is the other way round.

## Temporary workaround

Until this is resolved, if you want to integrate with a text-based browser, you can apply this patch (assuming your googler is up-to-date with the master branch): https://gist.githubusercontent.com/zmwangx/d250bd0521b96cec2b21a1bc2db57a6b/raw/575b5af324e6e3b323a90da2ba1c76e725d76151/googler.patch (https://git.io/v6N80):

```sh
$ cd /directory/where/googler/lives
$ curl -sSL https://git.io/v6N80 | patch -p1
```

By the way, the easiest way to be up-to-date with the master branch, assuming you're using a recent enough version with self-upgrade support, is

```
$ googler -U --include-git
```

**Comment by jarun** [comment]
I'm fine with the proposed solution.

**Comment by zmwangx** [comment]
> I'm fine with the proposed solution.

Which one, `--disable` or `--enable`? (`--enable` is better for backward compatibility, but `--disable` is somewhat more logical.)

**Comment by zmwangx** [comment]
`--disable` is probably going to bite a lot more people though, so I'm in favor of `--enable`.

**Comment by jarun** [comment]
`--enable` is fine.

**Comment by zmwangx** [comment]
Better:

1. Browser output on by default when `BROWER` is `w3m`, `lynx` or any other popular text-based browser. (Do you know any? There are of course Emacs `w3` and `eww`, but there are no associated commands except personal wrappers.)

2. Browser output off by default otherwise.

3. `--enable-browser-output` for the unfortunate special cases.

I'll implement this later today.

**Comment by jarun** [comment]
+ links, elinks

**Comment by Sasikanth3** [comment]
works with w3m and lynx . thanks guys

**Comment by jarun** [comment]
Cool! Don't forget to award a star. ;)
