### ISSUE TITLE
Error doing a Hello World

### ISSUE THREAD

**Issue by Ruffeng** [jarun/googler#132]
Hi, 
When I'm trying to do some examples,it returns me an error:

```
$ googler hello world                               
[ERROR] Failed to connect to www.google.com: module 'ssl' has no attribute 'PROTOCOL_TLSv1_2'.

```

I don't know what is it. I have Python 3, running in ZSH and OS x. 

Thanks!!

**Comment by jarun** [comment]
Happening because `googler` is trying to use TLSv1.2 but your OS probably doesn't support it yet. Can you check if your version of OSX supports TLSv1.2?

**Comment by Ruffeng** [comment]
UF, I'm checking and I'm not sure if they give me support in TLSv1.2
I'm running on a  OS X El capitan. I'm cannot find anything about TLS 1.2 on mac

**Comment by jarun** [comment]
The following might shed some light:
https://github.com/kennethreitz/requests/issues/2778#issuecomment-141597822

**Comment by Ruffeng** [comment]
I check and I have V 0.9.8. When I'm trying to install through brew, it returns me a message that version 1.0.2 is already installed.

I have no idea how to change the version.

**Comment by jarun** [comment]
How about `brew reinstall` or `--force`?

@zmwangx while we are at it, do you think it would be reasonable to provide an option to disable all optimizations and TLS 1.2 usage? A generic HTTPSConnection is what I am thinking of.

**Comment by jarun** [comment]
@Ruffeng I think your problem may be closely related to this:
http://stackoverflow.com/questions/15185661/update-openssl-on-os-x-with-homebrew

**Comment by Ruffeng** [comment]
I found this solution as well. But when I'm trying to force openssel, it returns me:

Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib

And it still without working

**Comment by jarun** [comment]
Strictly speaking, this is not a `googler` issue. Rather a Homebrew installation troubleshooting. You should be using the latest version of OpenSSL.

However, given the fact we still support a regular HTTPSConnection on certain systems I'm leaving it open till we decide on proving an option to force the same.

**Comment by Ruffeng** [comment]
You're right. Is not a googler issue. But running on OS X , homebrew updated and python 3 on the system, is not working. It's probably, that some more users working with OS X will find the same trouble. 

If in some case I can find the solution, I'll paste it here for other users with the same problem.

**Comment by zmwangx** [comment]
@Ruffeng I happen to a collaborator here *and* a Homebrew maintainer. I wonder where you got your Python 3 (OS X does NOT ship Python 3 so I don't know what you mean by "Python 3 on the system"), because if you're using Python 3 from Homebrew, that one should be linked to an up-to-date openssl:

```
$ brew linkage python3
System libraries:
  /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
  /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
  /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
  /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
  /System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl
  /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk
  /usr/lib/libSystem.B.dylib
  /usr/lib/libbz2.1.0.dylib
  /usr/lib/libncurses.5.4.dylib
  /usr/lib/libobjc.A.dylib
  /usr/lib/libpanel.5.4.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/gdbm/lib/libgdbm.4.dylib (gdbm)
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)
  /usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/Python (python3)
  /usr/local/opt/readline/lib/libreadline.6.dylib (readline)
  /usr/local/opt/sqlite/lib/libsqlite3.0.dylib (sqlite)
  /usr/local/opt/xz/lib/liblzma.5.dylib (xz)
```

I guess the quick solution is

```
brew install python3
```

and make sure `type python3` shows `/usr/local/bin/python3` first.

Do NOT mess with openssl, we disabled linking it because you shouldn't, and it would't help with the problem anyway.

**Comment by zmwangx** [comment]
@jarun 

> while we are at it, do you think it would be reasonable to provide an option to disable all optimizations and TLS 1.2 usage? A generic HTTPSConnection is what I am thinking of.

I'm not familiar with that part of the code but sure, I'm fine with that.

**Comment by zmwangx** [comment]
Another comment: in general, if you have problem with Homebrew, feel free to open an issue on https://github.com/Homebrew/homebrew-core/issues and we'll help you. Random answers on the web are often outdated or plain wrong / undermine our security model.

**Comment by Ruffeng** [comment]
Hi @zmwangx !
I installed python through brew. the problem is TLS 1.2 on the system.
Anyway, thanks for your help fellas. I'll try it on ubuntu, but i cannot make it work on OS X.

**Comment by zmwangx** [comment]
> I installed python through brew

You mean you did `brew install python3` and made sure `type python3` prints `/usr/local/bin/python3` first?

> the problem is TLS 1.2 on the system.

You shouldn't have that problem with brewed Python 3; if you do we'd like to take it serious. Could you please show me your `brew config`?

**Comment by Ruffeng** [comment]
@zmwangx 
When I type: `Type python3` it returns:
python3 is /Library/Frameworks/Python.framework/Versions/3.5/bin/python3


My brew config:
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7a9934ffa3cb051a2a3480f3c952a9e568e6e519
Last commit: 21 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 128e33259423e7f9c3ef042533798c3dadd7a0a5
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/opt/rbenv/shims/ruby => /usr/local/Cellar/rbenv/1.0.0/versions/2.3.1/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: N/A

**Comment by zmwangx** [comment]
@Ruffeng Yep you're not using brewed Python 3! Guess you got an installer somewhere, from python.org maybe?

Anyway, please

```
brew install python3
```

and that should do the trick.

Or actually just

```
brew install googler
```

which will take care of *both* python3 and googler.

**Comment by Ruffeng** [comment]
I installed some time ago from the website, but I removed. Today i re-installed python3 through brew. I did it.
If i'm trying again, it returns me this error

```
Error: /usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:240: syntax error, unexpected tSTRING_BEG, expecting ']'
                          "Library/Homebrew/cask", "Libr...
                           ^
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:240: syntax error, unexpected ',', expecting keyword_end
...       "Library/Homebrew/cask", "Library/Homebrew/test"]
...                               ^
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:240: syntax error, unexpected ']', expecting keyword_end
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:65:in `<main>'
Warning: python3-3.5.2_1 already installed, it's just not linked
```

**Comment by zmwangx** [comment]
@Ruffeng Sorry that's unfortunately a bad commit that happened several minutes ago (happens once in a blue moon...) and is already squashed. Please do the following:

```
$ cd /usr/local && git fetch && git reset --hard origin/master && brew update
$ brew link python3
```

**Comment by zmwangx** [comment]
(We're moving stuff around in Homebrew in the past few days and dashing towards brew 1.0.0 release so things have been in flux. On behalf of our team I apologize for the inconvenience.)

**Comment by Ruffeng** [comment]
Ok i got totally lost. I receive this issue when I'm running this command:

`fatal: Not a git repository (or any of the parent directories): .git`

Don't apologise, i really like to use brew and not has to work always. It's totally normal.

**Comment by zmwangx** [comment]
Oh okay it means you're already migrated which is good. In that case,

```
$ cd /usr/local/Homebrew && git fetch && git reset --hard origin/master && brew update
$ brew link python3
```

**Comment by zmwangx** [comment]
Once we finish this round of migrations and reach brew 1.0.0 we'll have a better release model and non-Homebrew-developer users won't be exposed to the less tested stuff on the master branch.

**Comment by Ruffeng** [comment]
Ok, fixed. However, when i'm doing the googler stuff it keeps showing me: 
`[ERROR] Failed to connect to www.google.com: module 'ssl' has no attribute 'PROTOCOL_TLSv1_2' `

**Comment by zmwangx** [comment]
And `type python3` now shows `/usr/local/bin/python3`?

**Comment by Ruffeng** [comment]
Nope, it stills stuck on:
`python3 is /Library/Frameworks/Python.framework/Versions/3.5/bin/python3`

**Comment by zmwangx** [comment]
Please show me your `PATH`.

```
$ echo $PATH
```

**Comment by Ruffeng** [comment]
`echo path`

`./bin /usr/local/opt/rbenv/shims /usr/local/opt/rbenv/bin /Library/Frameworks/Python.framework/Versions/3.5/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin`

**Comment by zmwangx** [comment]
That's a completely screwed up path. Problem with `~/.zshrc` probably.

**Comment by zmwangx** [comment]
Anyway, this is no longer or googler or Homebrew issue. You can verify that by running

```
$ PATH=/usr/local/bin:$PATH googler
```

I recommend that you read up on `$PATH` stuff afterwards.

**Comment by Ruffeng** [comment]
uaaaa zmwangx. You fixed my error running that command and you scared me a lot hahahah. What should I do??
Well I guess that this is out of your business.
thank you and thanks to @jarun  for your support.

**Comment by zmwangx** [comment]
> Well I guess that this is out of your business.

I would love to help, but it's too complicated a problem, I would need to sit at your computer...

Begin with https://en.wikipedia.org/wiki/PATH_(variable) maybe?

Closing the issue as resolved by the way.
