### ISSUE TITLE
How to run in China?

### ISSUE THREAD

**Issue by bubifengyun** [jarun/googler#133]
As known, google cannot use in China. But when hosts was changed, it may work well.
I can google in firefox, but it pops error when in googler.

```
$ googler firefox
[ERROR] Got HTTP 302: Found

```

**Comment by jarun** [comment]
Try the `--proxy` option.

**Comment by cyio** [comment]
use proxychains if you use shadowsocks
```bash
$ proxychains googler 谷歌 -l zh
```

@jarun Will googler consider support socks5 proxy ?

**Comment by jarun** [comment]
We got an issue report with proxychains earlier (refer to https://github.com/jarun/googler/issues/54). Try tsocks whic is known to work.

Regarding `socks5`, I do not see much ROI. China maybe, otherwise we do not see many authorities blocking google. I can reconsider if I see a PR.

**Comment by liang1224** [comment]
Try to search in baidu with the key "google hosts",enter the first result.Download the hosts file.and flush your dns cache.And you should use googler with option "-c hk".Enjoy!

**Comment by jarun** [comment]
Guys, just make sure you wouldn't face any issues in your country for googling.
