### ISSUE TITLE
BROWSER_ARG var

### ISSUE THREAD

**Issue by eoli3n** [jarun/googler#135]
#### Feature requests

Hi,
google chrome provides an app mode which launch chrome without border, usefull with i3wm.
tried to set BROWSER as following : 
    BROWSER="google-chrome-stable --app=" googler -dj netflix
But it opens chrome as classic way, i think because of googler putting a space between BROWSER and url argument. --app $url don't work with chrome.
Is there a way to add a var BROWSER_ARGS with an inline var which will be $url as:
    BROWSER="google-chrome-stable" BROWSER_ARGS="--app=%%url%%" googler -j netflix

Or something similar ?

I also tried to add a function in shellrc as 
    chromeapp() { google-chrome-stable --app=$1 }
but it seems not resolving aliases as
    BROWSER="chromeapp" googler -j netflix

So for now i wrote a script
    #!/bin/bash
    google-chrome-stable --app="$1"
then it's working, but it's ugly :)
   BROWSER="/home/$USER/scripts/bash/chromeapp.sh" googler -j netflix

Have a nice day.

**Comment by jarun** [comment]
Support for the BROWSER env variable comes from standard Python support/features. Please refer to:

https://docs.python.org/3/library/webbrowser.html

We can't do much here. You may want to raise the question in the Python forums.
