### ISSUE TITLE
Problem with alias (config file)

### ISSUE THREAD

**Issue by military1** [jarun/googler#136]
Hello!
The Problem with alias (config file). I add alias g='googler -n 7 -c ru -l ru' on bashr, but search and news aren't displayed in Russian. Works only with specific search googler -c ru. 
http://storage5.static.itmages.ru/i/16/1006/h_1475743100_8431068_2a48629e83.jpg

**Comment by jarun** [comment]
Please copy the output of `type g` here.

**Comment by military1** [comment]
```
[tux@antergos ~]$ type g
g is aliased to `googler -n 7 -c ru -l ru'
```

**Comment by jarun** [comment]
Noticed from your image you are using `googler -N archlinux`.
You should use:

    g -N archlinux
to actually use the alias.
