### ISSUE TITLE
Got HTTP 503: Service Unavailable after some (ca 15) successful queries

### ISSUE THREAD

**Issue by mpschr** [jarun/googler#137]
Debug log: https://gist.github.com/mpschr/c412aba1d2c277354d5cdc85604cd071

System: Ubuntu 14.04.1 LTS / Bash 4.3.11(1)-release / Python 3.4.5 |Anaconda 2.2.0 (64-bit)| (default, Jul  2 2016, 17:47:47) 

Locale: -LANG=en_US.UTF-8

----------------------

Hi 

The title says it pretty much, I am quering google with many similar terms, after about 15 successful queries I suddenly get blocked and the program returns `[ERROR] Got HTTP 503: Service Unavailable`. I do not really know if the blocking occurs at OS level or from Google itself (tending to OS).

Do you know if it is a known issue and if there is a workaround?

Thanks and best,
mpschr

**Comment by jarun** [comment]
Google detects and blocks very frequent automated queries. As far as I remember, we had tested this with a regular browser as well (Google Chrome) and got blocked. Gets unblocked after a while.

In general the response code falls in `30x` (on ipv4 but shouldn't change on ipv6). It's 503 here. Can you reproduce this?

I guess you can check if the service is really available or not from the regular browser.

**Comment by mpschr** [comment]
I see, so automated queries are not encouraged ;) I switched to bing for that - they let me make an api key for automatic querying.

Thanks for the info!

**Comment by jarun** [comment]
You are welcome!
