### ISSUE TITLE
Discussion: remove the --exact option and make it default

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#154]
Say you run `googler googler`. The word "googler" doesn't even appear once in the results. What the ...? Oh, Google is showing results for "google". But there's no indication whatsoever of this autocorrect in our output; sure, we can introduce more complexity in the parser to detect "Showing results for ...", but just like the result count, this doesn't sit well with our entry-based parser and printer, and is especially problematic with serialized output (`--json`), unless we completely break the interface.

Moreover, autocorrection simply isn't what people expect from command line utilities (autocorrect in interactive shell's line editor is a different story; we're talking about command lines being `exec`'ed here). When you `cat google`, `cat` doesn't autocorrect that to `googler`. You're responsible for what you type. If you made a typo, no sweat, do it again. (You can even correct the query right within googler's "shell", with all options preserved.)

Therefore, I propose to remove the `--exact` option and make it the default (that is, the only) behavior.

@jarun I'll raise a PR if you support this idea.

**Comment by jarun** [comment]
There are innumerable instances where auto-correction helps me at least. Specially which looking up movies on IMDB with the `--lucky` option.

We can type again, but I keep missing an option to press *UP arrow* and get the command line arguments at the omniprompt. (It would be great if we can have something like that). People prefer to type less.

Google prefers to assist when something seems wrong. Let's not trump the behaviour of the service we are a client to. However, will it be possible to add the "Showing results for ..." by just adding some parser overhead at the root_start() or result_start() level?

We can handle all of this better if we can bind (initial) custom strings to the arrows with readline.

**Comment by zmwangx** [comment]
Fair enough, #155, similar to the how we handle filtered results. Heck, turned out to be a fair bit of work.

**Comment by jarun** [comment]
I've also added https://github.com/jarun/googler/commit/44abeb451c825abc675ad5ab1568ca88681ce5cd to get the cmdline keywords.

**Comment by zmwangx** [comment]
👍
