### ISSUE TITLE
Add entry to the Free Software Directory

### ISSUE THREAD

**Issue by jorgesumle** [jarun/googler#160]
Googler is completely free software, so I added it to the Free Software Directory. Can you please review it? It probably takes some time until the entry gets approved. I've used all the information from the Git repository, such as program name, description, donation link, etc.

http://directory.fsf.org/wiki?title=Googler&action=formedit

**Comment by jarun** [comment]
The PayPal link is broken (extra `amp;`). Please use:

`https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RMLTQ76JSXJ4Q`

**Comment by jorgesumle** [comment]
Fixed. When you finish reviewing this close the issue. We just have to wait until the entry gets approved.

**Comment by jarun** [comment]
Looks good now. Thank you very much!!!

If I am not imposing (and you have the time), please consider submitting [Buku](https://github.com/jarun/Buku), [imgp](https://github.com/jarun/imgp) and [bcal](https://github.com/jarun/imgp) to FSF. All of them are in one or other major distro now.

**Comment by jarun** [comment]
> anyone can edit it, so maybe you should also add the main developers (maybe Zhiming Wang and Henri Hakkinen).

Which is the relevant tab/field? I could only find the licenses tab.

**Comment by jorgesumle** [comment]
http://directory.fsf.org/wiki?title=Googler&action=formedit#tab=4__Person_info

The person tab. Here there is a button which reads "Add another"
