### ISSUE TITLE
Can Use it for my automation script which will be used in web server?

### ISSUE THREAD

**Issue by tiru1930** [jarun/googler#164]
Hi  Arun

Its nice and very useful to my work,but i have few questions 
can i use it my web application like web crawler?
What are then terms&conditions should i fallow to use it in my web application?

**Comment by zmwangx** [comment]
googler is GPL licensed (*NOT* AGPL). That should answer your question.

https://www.google.com/search?q=gpl+proprietary+web+app

**Comment by jorgesumle** [comment]
Read the license: https://raw.githubusercontent.com/jarun/googler/master/LICENSE

**Comment by kyrias** [comment]
Just remember that using the results you get from googler in your own web app most likely violates Google's ToS

**Comment by tiru1930** [comment]
Thank you , I have read the terms and conditions ,I will go with GCE for my
application

**Comment by jarun** [comment]
All the best! Closing the issue.
