### ISSUE TITLE
Smart card results showing up

### ISSUE THREAD

**Issue by jarun** [jarun/googler#165]
The query I tried is:

`googler paytm wallet coupon code`

The results shows smart card at the top:

![search_results](http://i.imgur.com/PfqpyF6.png)

The output dump is at http://paste.ubuntu.com/23902555/

**Comment by jarun** [comment]
@zmwangx I think this should go away if we can filter out results within the tag `<div class="_uXc hp-xpdbox">`. Is there any easy way to do this?

**Comment by jarun** [comment]
The attr `hp-xpdbox` is not fixed... keeps changing.

**Comment by jarun** [comment]
I got http://paste.ubuntu.com/23902777/ in another run.

**Comment by jarun** [comment]
The case in http://paste.ubuntu.com/23902777/ happening because of `g-blk` is fixed with:

```
diff --git a/googler b/googler
index b0b5fa2..42daa18 100755
--- a/googler
+++ b/googler
@@ -1182,6 +1182,10 @@ class GoogleParser(html.parser.HTMLParser):
         {
             'tag': 'div',
             'class': 'related-question-pair'
+        },
+        {
+            'tag': 'div',
+            'class': 'g-blk'
         }
     ]
 
@@ -1191,7 +1195,7 @@ class GoogleParser(html.parser.HTMLParser):
     def root_start(self, tag, attrs):
         # We omit Google's "smart card" results (term coined by me) by
         # guarding against the 'g-blk' class (sample response: https://git.io/voJgB)
-        if tag == 'div' and 'g' in self.classes(attrs) and 'g-blk' not in self.classes(attrs):
+        if tag == 'div' and 'g' in self.classes(attrs):
             # Initialize result field registers
             self.title = ''
             self.url = ''
```

**Comment by jarun** [comment]
`<div class="_uXc hp-xpdbox">` happens with `--noua` which I am using as default in my system.

**Comment by zmwangx** [comment]
> The case in http://paste.ubuntu.com/23902777/ happening because of g-blk is fixed with:

Looks good (i.e., can't remember any counter example now).

The comments should be updated though (make sure to insert a comment above the `IGNORE_LIST` entry, and remove the original comment).

> --noua ... keeps changing

Not sure what can be done here within our existing framework.

Of course, one solution is to deduplicate results post-parsing. If two items have the same URL, discard the one with no or shorter abstract.

**Comment by jarun** [comment]
The complete fix is:

```
diff --git a/googler b/googler
index b0b5fa2..305249b 100755
--- a/googler
+++ b/googler
@@ -1182,6 +1182,17 @@ class GoogleParser(html.parser.HTMLParser):
         {
             'tag': 'div',
             'class': 'related-question-pair'
+        },
+        # We omit Google's "smart card" results (term coined by me) by
+        # guarding against the 'g-blk' class (sample response: https://git.io/voJgB)
+        {
+            'tag': 'div',
+            'class': 'g-blk'
+        },
+        # We also guard against "smart-card" results with `--noua` option
+        {
+            'tag': 'div',
+            'class': 'hp-xpdbox'
         }
     ]
 
@@ -1189,9 +1200,7 @@ class GoogleParser(html.parser.HTMLParser):
 
     @annotate_tag
     def root_start(self, tag, attrs):
-        # We omit Google's "smart card" results (term coined by me) by
-        # guarding against the 'g-blk' class (sample response: https://git.io/voJgB)
-        if tag == 'div' and 'g' in self.classes(attrs) and 'g-blk' not in self.classes(attrs):
+        if tag == 'div' and 'g' in self.classes(attrs):
             # Initialize result field registers
             self.title = ''
             self.url = ''
```

**Comment by zmwangx** [comment]
> ```
> +        # We also guard against "smart-card" results with `--noua` option
> +        {
> +            'tag': 'div',
> +            'class': 'hp-xpdbox'
>          }
> ```
> 

Hmm... I think you said `hp-xpdbox` keeps changing.

**Comment by jarun** [comment]
No, it seems constant. I wanted to say it changes with and without `--noua`.

On a different note, are you ware of any way to top google from redirecting? I want to use google.com but I get redirected to google.co.in all the time. However, my browser search results are returned from com. So there should be some way.

**Comment by zmwangx** [comment]
> However, my browser search results are returned from com.

Maybe check your browser's network panel? Any cookies, special headers, etc.

**Comment by jarun** [comment]
I'll check it out. Thanks!

**Comment by jarun** [comment]
Depends on the cookie. We'll live without it. ;)
