### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by fredzannarbor** [jarun/googler#166]
Getting 503 errors when I run googler.

Is this transitory or could I have hit service limits?

Linux Ubuntu 16.04

```
fred@fred-XPS-L322X:~$ googler -d "Hans Rosling"
[DEBUG] Version 2.9
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&num=10&oe=UTF-8&q=Hans+Rosling&start=0
[DEBUG] Redirecting to URL https://ipv6.google.com/sorry/index?continue=https://www.google.com/search%3Fie%3DUTF-8%26num%3D10%26oe%3DUTF-8%26q%3DHans%2BRosling%26start%3D0&q=EhAmAgMKLhvkYAAAAAAAAABJGMnV88QFIhkA8aeDS0VeNCxVYQqOxNbvLU9tifTR_sfXMgFj
[DEBUG] Connecting to new host ipv6.google.com
[DEBUG] Fetching URL /sorry/index?continue=https://www.google.com/search%3Fie%3DUTF-8%26num%3D10%26oe%3DUTF-8%26q%3DHans%2BRosling%26start%3D0&q=EhAmAgMKLhvkYAAAAAAAAABJGMnV88QFIhkA8aeDS0VeNCxVYQqOxNbvLU9tifTR_sfXMgFj
Traceback (most recent call last):
  File "/usr/local/bin/googler/googler", line 2347, in <module>
    main()
  File "/usr/local/bin/googler/googler", line 2336, in main
    repl.cmdloop()
  File "/usr/local/bin/googler/googler", line 1930, in cmdloop
    self.fetch_and_display()
  File "/usr/local/bin/googler/googler", line 1635, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/local/bin/googler/googler", line 1799, in fetch_and_display
    self.fetch()
  File "/usr/local/bin/googler/googler", line 1635, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/local/bin/googler/googler", line 1729, in fetch
    page = self._conn.fetch_page(self._google_url.relative())
  File "/usr/local/bin/googler/googler", line 745, in fetch_page
    raise GoogleConnectionError('Got HTTP %d: %s' % (resp.status, resp.reason))
__main__.GoogleConnectionError: Got HTTP 503: Service Unavailable
fred@fred-XPS-L322X:~$ 
```

#### Bug reports

Before opening an issue, please try to reproduce on [the latest development version](https://github.com/jarun/googler#installing-from-this-repository) first. The bug you noticed might have already been fixed.

If the issue can be reproduced on master, then please make sure you provide the following:
- Output of `googler -d`;
- Link to the response body (you should see a line like `[DEBUG] Response body written to '/Volumes/ramdisk/googler-response-xxxxxxxx'` in the output of `googler -d`; please upload the file to a [gist](https://gist.github.com/) and include the gist's URL in the issue);
- Details of operating system, Python version used, terminal emulator and shell;
- `locale` output, if relevant. It's a good idea to set your locale to UFT-8. Please refer to [Buku #30](https://github.com/jarun/Buku/issues/30).

If we need more information and there is no communication from the bug reporter within 7 days from the date of request, we will close the issue. If you have relevant information, resume discussion any time.

#### Feature requests
Please consider contributing the feature back to `googler` yourself. Feel free to discuss. We are more than happy to help.

--- PLEASE DELETE THIS LINE AND EVERYTHING ABOVE ---

**Comment by zmwangx** [comment]
> Is this transitory or could I have hit service limits?

I'm afraid this is the question we would ask you. Did you encounter this after some successful sessions? If so, patiently wait a while and try again.

**Comment by fredzannarbor** [comment]
Yes. Just wanted to know if this is a known problem.

**Comment by zmwangx** [comment]
> Just wanted to know if this is a known problem.

Google does block you for up to a few hours if you send many requests rapidly. This happens even in the browser, so it shouldn't be surprising.

What we typically see is `http://ipv4.google.com/sorry/IndexRedirect?continue=...`, treated in https://github.com/jarun/googler/blob/e37716e84f4e75e83d38742082644b6a72d22d4d/googler#L736-L737. Guess we can add `sorry/index?` to that rule?

Anyway, closing this issue since it's most likely just the mundane "connection blocked due to unusual activity". Please report back if the issue transforms into something else.

**Comment by zmwangx** [comment]
#167 accounts for the URL you encountered. (It doesn't help you with fetching results, but it does lead to a clearer error message: "Connection blocked due to unusual activity.")
