### ISSUE TITLE
How can I make the completions work with Oh My Zsh?

### ISSUE THREAD

**Issue by maaxxicarvalho** [jarun/googler#168]
Hi,

I am trying to make the completions work with my oh-my-zsh, the `/usr/local/share/zsh/site-functions` is being loaded but I see no completion.
I believe I'm missing something here so any help would be really appreciated.

**Comment by zmwangx** [comment]
Sorry, but this is not the forum for general Zsh help. Please read http://zsh.sourceforge.net/Doc/Release/Completion-System.html. If you still can't figure out, you can ask for help on StackOverflow, SuperUser, or zsh-users@zsh.org.
