### ISSUE TITLE
while add proxy  ,it need certificate verify 

### ISSUE THREAD

**Issue by gjpicker** [jarun/googler#186]
#### Error output
`
landscape-OptiPlex-7040 :   googler --proxy  127.0.0.1:8087  -c hk  --notweak   query_keywords
`
 
[ERROR] Failed to connect to proxy server 127.0.0.1:8087: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645).

#### description it 
landscape-OptiPlex-7040  :my machine 
command-line: googler --proxy  127.0.0.1:8087  -c hk  --notweak   query_keywords 
proxy: @see all https://github.com/XX-net/XX-Net

#### env
* netstat -nlp 

`
tcp        0      0 127.0.0.1:8087          0.0.0.0:*               LISTEN      -               
`
* linux version 

`
landscape-OptiPlex-7040 : cat /etc/os-release
`

NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
`
#### self-try 
 I think  loss system's  certificate ,so  I  finish import CA.crt which  copyed from  XX-Net into system .
operate command  like 
`
$ sudo cp mycert.cer /usr/share/ca-certificates/mycert.pem
`
`
$ sudo dpkg-reconfigure ca-certificates
`
`
$ sudo update-ca-certificates
`

oops , it doesn't work ,show same error log

**Comment by zmwangx** [comment]
You sure your proxy actually works with HTTPS connections? What about

```
$ curl -x localhost:8087 https://www.google.com
```

And your Python version? I assume 3.5.2?

**Comment by zmwangx** [comment]
By the way, I think we only support HTTPS proxies, not SOCKS4/5 proxies. Is XX-net a SOCKS5 proxy? I don't know much about proxies and I can't tell immediately from a Google search.

**Comment by jarun** [comment]
It seems the utility [supports](https://github.com/XX-net/XX-Net/wiki/How-to-use#linux%E7%B3%BB%E7%BB%9F) HTTP(S) as well.

**Comment by jarun** [comment]
The curl command is the first logical step.

**Comment by zmwangx** [comment]
Okay yeah it has an HTTP(S) mode, but since it appears to be used to bypass the GFW here, I'm skeptical that that mode is good enough here. The GFW is pretty good at deep packet analysis. Maybe only the SOCKS mode can sneak through the GFW? At least the last time I had to circumvent the GFW, I used Shadowsocks which is a SOCKS5 proxy. I'm just guessing here. Curl should be able to tell.

**Comment by zmwangx** [comment]
It's been a week (well, almost) without response. Please leave a comment if you have more to share. Closing.
