### ISSUE TITLE
--news is not working

### ISSUE THREAD

**Issue by mberg2007** [jarun/googler#187]
On my Ubuntu 16.x system, performing any "news" search always returns zero results. Is this a known issue or perhaps the feature only works in certain countries?

**Comment by zmwangx** [comment]
Please follow the issue template: https://github.com/jarun/googler/blob/master/.github/ISSUE_TEMPLATE.md
We can't possibly debug anything with a blanket "not working" statement.

**Comment by mberg2007** [comment]
Right, sorry about the short error description. Here's some further information for you:

michael@michael-laptop:~/temp/googler$ googler -d
[DEBUG] Version 3.1
[DEBUG] Connecting to new host www.google.com
Please initiate a query.

No further output was produced, only a prompt for me to enter a query. So I cannot show what the response body linked to.

michael@michael-laptop:~/temp/googler$ uname -a
Linux michael-laptop 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

michael@michael-laptop:~/temp/googler$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

michael@michael-laptop:~/temp/googler$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2

michael@michael-laptop:~/temp/googler$ bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

michael@michael-laptop:~/temp/googler$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by mberg2007** [comment]
And just to follow up with a concrete example - first something that works, then something that unexpectedly doesn't:

michael@michael-laptop:~/temp/googler$ ./googler --json -t d5 -n 3 --np -C Election
[
  {
    "abstract": "for 9 timer siden - The UK could be heading for a hung parliament as voting closes across the UK in the 2017 general election, the exit poll has predicted. The exit poll suggests ...",
    "title": "Election 2017 live updates: Shock exit poll shows UK heading for a ...",
    "url": "http://www.independent.co.uk/News/uk/politics/election-uk-live-updates-latest-jeremy-corbyn-theresa-may-winning-polls-seats-majority-labour-a7774696.html"
  },
  {
    "abstract": "for 7 minutter siden - The United Kingdom general election of 2017 took place on 8 June 2017. Each of the 650 parliamentary constituencies is electing one Member of Parliament ...",
    "title": "United Kingdom general election, 2017 - Wikipedia",
    "url": "https://en.wikipedia.org/wiki/United_Kingdom_general_election,_2017"
  },
  {
    "abstract": "for 3 dage siden - Latest General election 2017 news, comment and analysis from the Guardian, the world's leading liberal voice.",
    "title": "General election 2017 | The Guardian",
    "url": "https://www.theguardian.com/politics/general-election-2017"
  }
]

michael@michael-laptop:~/temp/googler$ ./googler --news --json -t d5 -n 3 --np -C Election
[]

**Comment by jarun** [comment]
I can't reproduce this with the same arguments. Can you please add the flag -d to the last command and provide the dump file from /tmp?

**Comment by jarun** [comment]
Please run

`./googler -d --news --json -t d5 -n 3 --np -C Election`

and share the response body. The path with the shown in the line:

`[DEBUG] Response body written to '/tmp/googler-response-...'.`

**Comment by jarun** [comment]
Also,

`michael@michael-laptop:~/temp/googler$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)`

googler works with Python 3.3 and above only. However, I am assuming it's there on your system from the working output.

**Comment by mberg2007** [comment]
michael@michael-laptop:~/temp/googler$ ./googler -d --news --json -t d5 -n 3 --np -C Election
[DEBUG] Version 3.1
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&num=3&oe=UTF-8&q=Election&tbm=nws&tbs=qdr:d5
[DEBUG] Cookie: NID=105=GTDVMGs1FOhVpkvvI4oTeCOdgGP1mEmzZibMPkdwc6Jp28nBTTbibcCDmZ8jQT0GfQUAG6IvAYKrvsM_-4jt_RYB7sQpYzkQ0pv8SfiQ5JhVVHq7WdnueAKG9auZuYbm
[DEBUG] Redirecting to URL https://www.google.dk/search?ie=UTF-8&num=3&oe=UTF-8&q=Election&tbm=nws&tbs=qdr:d5&gws_rd=cr&ei=gFc6WYq6A4XHwQLtsrOwBw
[DEBUG] Connecting to new host www.google.dk
[DEBUG] Fetching URL /search?ie=UTF-8&num=3&oe=UTF-8&q=Election&tbm=nws&tbs=qdr:d5&gws_rd=cr&ei=gFc6WYq6A4XHwQLtsrOwBw
[DEBUG] Response body written to '/tmp/googler-response-h7zbmw3o'.
[]

Here's the response body file (attached)

michael@michael-laptop:~/temp/googler$ ls -la /tmp/googler-response-h7zbmw3o
-rw------- 1 michael michael **247216** Jun  9 10:08 /tmp/googler-response-h7zbmw3o

[googler-response-h7zbmw3o.zip](https://github.com/jarun/googler/files/1063359/googler-response-h7zbmw3o.zip)

**Comment by zmwangx** [comment]
I can reproduce, but only with the .dk TLD.

```
$ googler -d --news -c dk --json -t d5 -n 3 --np -C Election
[DEBUG] Version 3.1
[DEBUG] Connecting to new host www.google.dk
[DEBUG] Fetching URL /search?ie=UTF-8&num=3&oe=UTF-8&q=Election&tbm=nws&tbs=qdr:d5
[DEBUG] Cookie: NID=105=AOZYE_Qf4J5XgrUYG3eQlHCUnMfWK0RfInle1F8NX_WUNV5urfkvUspK-Byk5j1VNGTqhY1yt7VfM0PpItHNcGGyInKVBzMvcIsoH6USxqxjSQEa92nDU6-_HV1JMz0N
[DEBUG] Response body written to '/Volumes/ramdisk/googler-response-jhy042p0'.
[]
```

In the response, there's a message

> Din søgning – Election – kunne ikke gennemføres med de valgte søgeindstillinger.

and according to Google Translate, it means

> Your search - Election - could not be completed with the selected search settings.

I tried a whole bunch of other TLDs and they are work just fine. Not sure what's going on with the Danish version of Google.

**Comment by zmwangx** [comment]
By the way, there's a meta refresh in the response: `<meta content="0;url=/search?q=Election&amp;tbm=nws&amp;tbs=qdr:d5&amp;gbv=1&amp;sei=gFc6Wf6ZCsWlwQLk34DYBg" http-equiv="refresh">`. If we follow that refresh it might work. Not sure I want to get into the business of parsing meta tags though.

**Comment by zmwangx** [comment]
Another side note: I have reposted the response in `googler-response-h7zbmw3o.zip` as <https://gist.githubusercontent.com/anonymous/c01d4eeb6c5aef60db09ad8a07407d67/raw/de8ba28f9a7a09afc0fa0b6c8b47c952f4fad702/googler-response-h7zbmw3o>. zip is just too hostile.

**Comment by mberg2007** [comment]
I agree that meta parsing will make the whole thing more convoluted but I think the options are limited here. I'm not sure you can force a different tld and even if you could, it might only work temporarily until Google decides otherwise.

It's a tricky one for sure. But if Python has some xslt/xpath stuff built into it it might be somewhat feasible to parse one specific Meta header.

**Comment by mberg2007** [comment]
Come to think of it, doesn't the response come back as a 302 redirect? I would sort of expect that.

**Comment by zmwangx** [comment]
No, that meta refresh is wrapped in a noscript tag. No redirect if you have JavaScript turned on.

And I tried to add the `gbv` and `sei` query params. No, following the meta refresh doesn't magically yield results.

Since you sometimes see results and sometimes don't, I'm tempted to say that www.google.dk is just fucking with users. The fact that when I visit https://www.google.dk/search?ie=UTF-8&num=3&oe=UTF-8&q=Election&tbm=nws&tbs=qdr:d5 in the browser (with JavaScript turned off) I always seem to get something is eluding me at the moment, but I don't have time to experiment with all the headers. Maybe you could try that.

> I agree that meta parsing will make the whole thing more convoluted but I think the options are limited here.

> But if Python has some xslt/xpath stuff built into it it might be somewhat feasible to parse one specific Meta header.

There's separation of concern in googler where HTTP part fetches HTML and hands over to the HTML parser works strictly offline and in a reproducible way. That's why we have `devbin/parse` which works reproducibly on any debug response. Having to interpret meta http-equiv means HTTP stuff now bleeds into the HTML part and the whole model basically needs to be rearchitected. It's not about fishing out the redirect URL (which isn't a technical challenge, although it could be painful), and it's more complicated than you'd think.

Fortunately, following the redirect doesn't seem to actually work, as mentioned above.

**Comment by mberg2007** [comment]
If you're seeing results in your browser but not with your Python http client, this suggests some missing request headers to me. Google may be playing around with users who are "very obviously" trying to scrape their results. And by very obvious I mean missing a user agent header for example.

You could try to use F12 in chrome and watch the "Net" tab to see what exactly the browser is doing to get those results back. Compare that with what your Python http client is doing. There must be a difference somewhere.

**Comment by mberg2007** [comment]
(Funny that this thing only seems to be a problem with News. What's so special about News I wonder..?)

**Comment by zmwangx** [comment]
Thanks, I know how to use Developer Tools, or I wouldn't have been contributing to googler. Didn't I say

> but I don't have time to experiment with all the headers. Maybe you could try that.

**Comment by zmwangx** [comment]
One more note: this is more localized than I thought, probably only localized to www.google.dk in Danish. Even specifying the English language result in something:

```
$ googler -d --news -c dk --json -t d5 -n 3 --np -C yes
[DEBUG] Version 3.1
[DEBUG] Connecting to new host www.google.dk
[DEBUG] Fetching URL /search?ie=UTF-8&num=3&oe=UTF-8&q=yes&tbm=nws&tbs=qdr:d5
[DEBUG] Cookie: NID=105=A5mRZQdm3H2KgmEnk4MsXmdxRxoBdWGi7ttncdnVSfjiKitQOjBvfG9M3whbZQfR1E36GdwKmrQRG7x5YromDQVbzXTi001Whsga1MmLOo1JnPubTpsUl2Dfvvve0seP
[DEBUG] Response body written to '/Volumes/ramdisk/googler-response-bgql3tx0'.
[]
$ googler -d --news -c dk -l en --json -t d5 -n 3 --np -C yes
[DEBUG] Version 3.1
[DEBUG] Connecting to new host www.google.dk
[DEBUG] Fetching URL /search?hl=en&ie=UTF-8&num=3&oe=UTF-8&q=yes&tbm=nws&tbs=qdr:d5
[DEBUG] Cookie: NID=105=MTULkvHieSfgvHolpdz0tc6_LLXALD5wtPd7sJQzy4S28guZ1_W1nwPFmaL9dAF7aB_t28mDHgdCAJ9PqwcS0LMJTIgHeaPyS3IKhqBLIVcGcStNXPzRcMb6L0zxtfra
[DEBUG] Response body written to '/Volumes/ramdisk/googler-response-iua0_7rg'.
[
  {
    "abstract": "Ratings released by Nielsen on Thursday showed that viewership of the team's games on YES is up 50 percent for the first two months of the season ...",
    "metadata": "New York Post, 6 hours ago",
    "title": "Aaron Judge-led Yankees a ratings success for YES",
    "url": "http://nypost.com/2017/06/09/aaron-judge-led-yankees-a-ratings-success-for-yes/"
  },
  {
    "abstract": "From now until the time he retires, LeBron James' free agency decisions will be covered with the fervor of a presidential election or, say, an NBA prospect's ...",
    "metadata": "Complex, 13 hours ago",
    "title": "LeBron James to the Lakers? Yes, This Is a Rumor That's Actually ...",
    "url": "http://www.complex.com/sports/2017/06/lebron-james-2018-free-agency-rumors-lakers"
  },
  {
    "abstract": "Koby Gal-Raday will report to Yes CEO Ron Eilon and will oversee all aspects of business, including originals development, production, programming, content ...",
    "metadata": "C21Media, 3 hours ago",
    "title": "ProSieben alum joins Israel's Yes",
    "url": "https://www.c21media.net/prosieben-alum-joins-israels-yes/"
  }
]
```

I bow out until there's something actionable that don't require half an hour or more on my part.

**Comment by mberg2007** [comment]
I don't know Python so I have little to contrubute with other than suggestions, even if they seem obvious to you.

I'm reporting to issue so you are aware of it. If you don't have time to work on this right now I understand. We all have day jobs.

**Comment by zmwangx** [comment]
> I don't know Python...

Sure. You know what, you don't need to know Python to be useful here. You only need to know how to use curl to do HTTP stuff. Even if you don't, you can copy as curl from DevTools, paste into your terminal, and just try to add or remove `-H` options until there's a visible difference in the number of results. So please do give that a try if you have time.

**Comment by jarun** [comment]
@mberg2007 while it might be a bit annoying that everything else works, I believe working on this only because of a single domain wouldn't yield reasonable ROI. Both myself and @zmwangx are quite busy at the moment.

As @zmwangx has pointed out, there's one workaround for you - to add the `-l en` option. At this point this is the best we can offer. Thanks for helping us with all the info. I'll add this as an item in our ToDo list so someone else can try it out if (s)he finds it interesting enough.

**Comment by mberg2007** [comment]
Adding the -l en is a perfecly fine workaround. And I understand you need to prioritize issues according to relevance and number of users affected. I never expected anyone to drop everything and work on this right away, I just wanted to report the issue.

It might be affecting other TLD's that you just don't know about yet. So the problem could be bigger.

Anyway, the workaround is fine for me, thanks for that.

**Comment by jarun** [comment]
> It might be affecting other TLD's that you just don't know about yet. So the problem could be bigger.

Very much possible!

Thanks for confirming and reporting the issue.

**Comment by zmwangx** [comment]
Quick test of some popular tlds:

```
for tld in com ar au be br ca ch cz de es 'fi' fr id 'in' it jp kr mx nl ph pl pt ro ru se tw ua uk; do echo -n "$tld: "; googler --news -c $tld --json -t d5 -n 3 --np -C election | jq length; done
com: 3
ar: 3
au: 3
be: 3
br: 3
ca: 3
ch: 3
cz: 3
de: 3
es: 3
fi: 0
fr: 3
id: 3
in: 3
it: 3
jp: 3
kr: 3
mx: 3
nl: 3
ph: 3
pl: 3
pt: 3
ro: 3
ru: 3
se: 3
tw: 3
ua: 3
uk: 3
```

only .fi isn't working.

A quick test of Nordic countries:

```
$ for tld in dk fi is no se; do echo -n "$tld: "; googler --news -c $tld --json -t d5 -n 3 --np -C election | jq length; done
dk: 0
fi: 0
is: 0
no: 3
se: 3
```

so Island also isn't working.

**Comment by jarun** [comment]
> so Island also isn't working.

Iceland you mean...

**Comment by jarun** [comment]
As per my understanding from this image, there is no News for Google Denmark. Same goes for Iceland.

![google Denmark](http://i.imgur.com/ZaEHkrI.png)

**Comment by jarun** [comment]
And Finland too! ;)

**Comment by zmwangx** [comment]
> there is no News for Google Denmark.

Wha...

![screen shot 2017-06-09 at 9 44 38 am](https://user-images.githubusercontent.com/4149852/26978137-4fd61262-4cf8-11e7-8e9a-9cc0c08c1f2b.png)

**Comment by mberg2007** [comment]
I can confirm as per the screenshot from @zmwangx that we do indeed have Google News here in Denmark - from a range of Danish media.

**Comment by jarun** [comment]
Check the page when the language is set to Danish.

**Comment by jarun** [comment]
And I get exactly the same results from your image when I set the language to `en` in googler.

![Danish News en](http://i.imgur.com/IZ5i8cZ.png)

**Comment by jarun** [comment]
I can open https://news.google.co.in/, https://news.google.co.uk/

But https://news.google.dk/ redirects me to https://news.google.com/. It doesn't exist. Period.

**Comment by zmwangx** [comment]
In fact, lang `da` and `fi` doesn't work for Google News in under any TLD. Might be due to some political crap.

**Comment by zmwangx** [comment]
Anyway, I doubt we can do anything about this.

**Comment by jarun** [comment]
Yeah... no crime, no news... ;)

**Comment by jarun** [comment]
Shall we document this anymore?

**Comment by jarun** [comment]
I'll add a update the ToDo list.
