### ISSUE TITLE
Does googler support to return the total number of google search result ?

### ISSUE THREAD

**Issue by JeepLin** [jarun/googler#192]
Does googler support to return the total number of google search result ?

When I search the keyword "China", I want to know the total number of google search's result . Can googler support this ?

Thanks !

**Comment by jarun** [comment]
The details are in the page but looking for it would mean unnecessary parsing for us. I guess you are probably interested in mining the data for some comparative analysis. Maybe write a small script using curl and any html decoder to get the information?

**Comment by zmwangx** [comment]
This has been answered in #144. See my (trivial) script at https://github.com/jarun/googler/issues/144#issuecomment-260716097.
