### ISSUE TITLE
unfilter results without typing "unfilter"

### ISSUE THREAD

**Issue by mattmar** [jarun/googler#193]
Hi all,
I need to perform a full Google search from the command line and  therefore I am using Googler.
However when I run:
`googler -x -C -n 500 -s 100 -c cl -l sp Clínica+Veterinaria+Putre`

I get a few results and then:
> ** Enter "unfilter" to show similar results Google omitted.

Browsing Googler source code I spotted these comments:

>     #   Sometimes Google omits similar (more like duplicate) result
>     #   entries. Whenever this happens there will be a notice in p#ofr. The way
>     #   to unfilter is to simply add '&filter=0' to the query string.

When I add "&filter=0" two the query, I obtain 0 results.
`googler -x -C -n 500 -s 100 -c cl -l sp "Clínica+Veterinaria+Putre&filter=0"`

Can you help me to overcome this problem?
Thanks 
Matteo

**Comment by jarun** [comment]
You shouldn't try to manipulate the search string. There was a PR on this sometime back. Take a look at https://github.com/jarun/googler/pull/188. If you really want it, fork and raise the PR.

**Comment by jarun** [comment]
Closing this issue,
