### ISSUE TITLE
[Windows] Installing Via Pip Errors Out

### ISSUE THREAD

**Issue by zQueal** [jarun/googler#195]
Seems to be reproducible on the latest dev build as well.

    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

However;

![kytrn](https://user-images.githubusercontent.com/239193/27962486-137fd6a4-6300-11e7-8d2b-630dfef9cfd2.png)

--------------------------

As far as I can tell I already have the dependency it requires--but it's still failing.

**Comment by zmwangx** [comment]
https://pypi.python.org/pypi/googler is https://github.com/tfmt/googler. It has absolutely nothing to do with us. To install our googler, see https://github.com/jarun/googler#installation.
