### ISSUE TITLE
Behind Proxy

### ISSUE THREAD

**Issue by PatroxGaurab** [jarun/googler#20]
Will be great if it works behind a proxy too.

**Comment by jarun** [comment]
Would it be possible for you to send a patch for this?

**Comment by PatroxGaurab** [comment]
Hi Arun lemme work on that.

**Comment by jarun** [comment]
Great! Thank you so much!

**Comment by jarun** [comment]
Don't forget to "star" the project if you find it useful. ;)

**Comment by jarun** [comment]
Consider the following approach:
Pass the IP and port as a params to googler (n.n.n.n:p format?)
- add IP validity check
- add check for no port passed if IP is valid (try default port maybe?)

Users can set and environment variable (GPROXY ??) to avoid passing the proxy details every time.

**Comment by jarun** [comment]
I am not sure if you are working on it. Meanwhile, I have found a possible solution. If you are not OK with system-wide proxy settings, try [proxycahins](http://proxychains.sourceforge.net/). Note that you have to use a proxy other than the default (via tor). Google blocks requests over tor by default and demands captcha pass.

I am closing this issue with the above. Please reopen if you are working on it.

**Comment by zmwangx** [comment]
Experimental HTTP proxy support has been added https://github.com/jarun/googler/blob/master/googler#L393. Please help by testing it or contributing insight/code if you want to see it merged.
