### ISSUE TITLE
[Just to report] Googler on cygwin

### ISSUE THREAD

**Issue by lucas59356** [jarun/googler#201]
The latest commit (dcc4956c76c69c4f112a7b7bf222a9ccffc89894) is working perfectly on babun (cygwin) in my Windows 7 Professional PC.
![image](https://user-images.githubusercontent.com/15693688/29635565-cae58e18-8823-11e7-9be4-0195e1f21a22.png)

**Comment by jarun** [comment]
Many thanks for checking it out and taking the time to confirm!!!
