### ISSUE TITLE
very nice, but google blocks your connection after a few attempts

### ISSUE THREAD

**Issue by sg-s** [jarun/googler#202]
so this is of limited use

**Comment by zmwangx** [comment]
googler isn't designed for mass scraping. It's completely against ToS anyway.

I'm not at all endorsing this practice, but you can use a service like ProxyMesh to increase your "quota".

**Comment by zmwangx** [comment]
And another advice is to space out your queries. Like sleeping for three seconds between two consecutive queries.

**Comment by jarun** [comment]
Some more points on this:

- I know terminal users (both by choice and compulsion) who had been happily using `googler` for years for ALL their google searches
- There are services (including DNS lookup services) who block traffic by the IP range of an ISP or a region. Not saying it's the case here but yes, the Indian IP range from ISP Airtel BB was sanctioned from some services. Google actively identifies tor and some free/popular VPN service IP ranges.
- The behaviour you are noticing is true for web browsers as well. We tested it successfully once (it's recorded in one of the issues/PRs). Google tries to detect automatic queries by the frequency of searches.
