### ISSUE TITLE
Feature: Results should be visible in any terminal size

### ISSUE THREAD

**Issue by psukys** [jarun/googler#207]
Currently, the default is always showing 10 results, whereas this could be dynamically set through interpretting the size of the terminal window.

It seems that `tput lines` does the job (tested on `xterm`, `gnome-terminal`, and in separate tty - ctrl+alt+f3 i.e.), thus this could be estimated beforehand

**Comment by zmwangx** [comment]
> whereas this could be dynamically set through interpretting the size of the terminal window.

Each result occupied an unknown number of lines, so this is not possible.

**Comment by jarun** [comment]
1. Most terminals support scrollbars and mouse scroll.
2. Most terminals support a default size. Use the option `-n` to set the number of results to show per page depending on the default size of your terminal. I use 7, for example.

**Comment by psukys** [comment]
@zmwangx strongly disagree, since you can always find it before printing out.

@jarun I am unsure of the typical `googler` workflow, as it offers interactive mode, but the one needs to use scrollbars (?). Beats the purpose of it being a terminal app.

What I'm proposing is having some special parameter that instead of trying to manually figuring out how many results should be shown, the program would use current terminal's properties in doing the job for the user.

**Comment by zmwangx** [comment]
Sure, please submit a patch, and we'll have a look.
