### ISSUE TITLE
Possible feature request: show "Google processed" answer and exit

### ISSUE THREAD

**Issue by Weej1** [jarun/googler#210]
Hi 

I just found out about this tool from following a reddit post about buku (which I intend to use right after this post). But I was wondering: is there a way to get the "Google processed" results text showing up ? I'm not sure what to call it really but an example is if I type: "What is the time in UK right now?" in google it will give me the result below:
 
![001_github_screenshot_for_jarun_googler](https://user-images.githubusercontent.com/6381159/32842066-1fda6a32-ca42-11e7-89d0-35fa2303c40a.png)

all I really want in the Text within the box and not the search results below it. Now I think i can remove the search results just fine from glancing at the man page for googler but I"m still unsure how to get the "processed answer" result and automatically exit.  

Thanks again for these great little tools!

**Comment by zmwangx** [comment]
See #97, specially my ROI assessment: https://github.com/jarun/googler/issues/97#issuecomment-222322357. In short, I'm afraid googler is designed around a list of results, each with a title, a URL, and an abstract, as opposed to less structured data like this.

**Comment by jarun** [comment]
As @zmwangx has pointed out, there are no plans to support the requested feature. We can reconsider if there's a PR.
