### ISSUE TITLE
Safe Search

### ISSUE THREAD

**Issue by Grauen** [jarun/googler#212]
Does googler allow to disable safe search or is it disabled by default?

**Comment by jarun** [comment]
It's the default - disabled. No plans to provide an option to toggle it.

**Comment by zmwangx** [comment]
Think of googler as Googling on a fresh browser without logging in to a Google account. Here in the U.S. at least, SafeSearch is off by default. See https://www.google.com/preferences. YMMV due to different laws in different countries.

**Comment by Grauen** [comment]
In Europe safe search is activated by default. An option to disable SafeSearch would be very useful.

A workaround could be to use an US-proxy, as I understand. But this will give you different search results. Say, you're looking for results in German, which require SafeSearch to be disabled. If you're using an US-Proxy you'll have SafeSearch disabled, but you will not get the same results.

@jarun @zmwangx

**Comment by jarun** [comment]
> In Europe safe search is activated by default.

That's a good thing, no?

> Say, you're looking for results in German, which require SafeSearch to be disabled.

What kind of German content need safe Search to be disabled?

If you can cite some examples where Safe Search is enabled by default, it would help us re-consider this.

**Comment by Grauen** [comment]
It's not a good thing if you're using googler, since you won't find all results :).

- finding pages with hate speech
- finding websites with illegal content
- finding pages which provides illegal uploads of movies, games with adult material

**Comment by zmwangx** [comment]
Actually, I connected to a German node of PIA, and went to check https://www.google.de/preferences. Safe Search is off.
![screen shot 2017-11-30 at 5 09 08 am](https://user-images.githubusercontent.com/4149852/33425427-a42d9944-d58c-11e7-8773-f56ac12f7e01.png)

**Comment by jarun** [comment]
Thanks @zmwangx! Probably, we can have the option to toggle it then. ;)

**Comment by zmwangx** [comment]
I mean, it seems off by default. In other words, I can't reproduce.

**Comment by jarun** [comment]
That's OK. It can also be disabled by the ISP it seems. It's a good reason to have the option to toggle it.

**Comment by zmwangx** [comment]
The query param is `safe=active`, so it's disabled in googler no matter what.

**Comment by jarun** [comment]
I didn't understand. is it hard-coded?

**Comment by zmwangx** [comment]
No, I'm just saying it should be disabled in googler at the moment wherever you are, and given that users of googler should mostly be adults or at least have judgement, and googler is not visual, I'm not sure a safe option would be useful.

**Comment by jarun** [comment]
If safe search is always active, I don't want to touch it.

**Comment by zmwangx** [comment]
It's always off.

**Comment by jarun** [comment]
Ahh OK, I got it. You are talking of the query from the browser.

**Comment by zmwangx** [comment]
If you want to turn on SafeSearch, you add `safe=active` to the URL.

**Comment by jarun** [comment]
OK. So to answer @Grauen it's disabled by default.

**Comment by Grauen** [comment]
At this moment I couldn't reproduce this, too. I opened a new anonymous window in FireFox and SafeSearch was disabled by default.

Also when using the safe parameter I couldn't see any changes in the result list while toggling the search param (off , actice) while searching for "Wolfenstein" so I guess safe search is ignored when you're looking for stuff which would be usually filtered.

I'll setup a vm for further tests later.

Thanks guys, I love your project.

**Comment by jarun** [comment]
BTW, in the incognito mode, the URL doesn't even change. I searched for `hello world` in google.co.in.

Default: safe search off
I turned it on, page refreshed automatically but no change in URL.

I can dive deeper to look into the headers but I think we can ignore it till someone comes back.

**Comment by zmwangx** [comment]
In the U.S., with Chrome 62, turning on SafeSearch in Incognito mode does lead to `safe=active`.

**Comment by zmwangx** [comment]
> page refreshed automatically but no change in URL

It will just set a cookie and refresh to www.google.com (or www.google.<yourtld>). `safe=active` only manifests when you search for something.

**Comment by jarun** [comment]
👍 But we don't touch it as of now. ;)
