### ISSUE TITLE
[ERROR] 'module' object has no attribute 'get_terminal_size'

### ISSUE THREAD

**Issue by salesiss** [jarun/googler#217]
#### Bug reports

The problem is quite simple, call googler with any site:
root@nyserv:/home/googler2# googler supersite.net

1 supersite.net - supersite Resources and Information. This website is ...
http://supersite.net/
**_[ERROR] 'module' object has no attribute 'get_terminal_size'_**
root@nyserv/home/googler2#

Possibly because we use debian7, anyway googler is so a nice handy program that a pitty it won't work for a simple issue as _get_terminal_size_

#### Addional details:

- Output of `googler -d`;
root@nyserv:/home/googler# googler -d
[DEBUG] googler version 3.4
[DEBUG] Python version 3.2.3
[DEBUG] Connecting to new host www.google.com

- Link to the response body (you should see a line like `[DEBUG] Response body written.)
root@nyserv:/home/googler2# googler -d supersite.net
[DEBUG] googler version 3.4
[DEBUG] Python version 3.2.3
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=supersite.net
[DEBUG] Cookie: NID=120=QpfSnWDXpS__oKDYNNcyCslq4aiUSWB8usj2TyF3y94vCJLPRrJId4ISIu4ovtVpFHg2IiBphAFevb4s6hxLRJWmNP4xBWRdpdZ3K8XJqPJazp9doIsBP7jODfk5ILoI
[DEBUG] Redirecting to URL https://www.google.ca/search?ie=UTF-8&oe=UTF-8&q=supersite.net&gws_rd=cr&dcr=0&ei=lqtNWuqHFYLm_Qbf0JjwCA
[DEBUG] Connecting to new host www.google.ca
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=supersite.net&gws_rd=cr&dcr=0&ei=lqtNWuqHFYLm_Qbf0JjwCA
[DEBUG] Response body written to '/tmp/googler-response-_fg0bs'.

1 supersite.net - supersite Resources and Information. This website is ...
http://supersite.net/
Traceback (most recent call last):
  File "/usr/local/bin/googler", line 2525, in <module>
    main()
  File "/usr/local/bin/googler", line 2514, in main
    repl.cmdloop()
  File "/usr/local/bin/googler", line 2019, in cmdloop
    self.fetch_and_display()
  File "/usr/local/bin/googler", line 1706, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/local/bin/googler", line 1885, in fetch_and_display
    self.display_results(prelude=prelude, json_output=json_output)
  File "/usr/local/bin/googler", line 1706, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/local/bin/googler", line 1841, in display_results
    r.print()
  File "/usr/local/bin/googler", line 1655, in print
    self._print_metadata_and_abstract(self.abstract, metadata=self.metadata)
  File "/usr/local/bin/googler", line 1629, in _print_metadata_and_abstract
    columns, _ = os.get_terminal_size()
AttributeError: 'module' object has no attribute 'get_terminal_size'
root@nyserv:/home/googler2# googler supersite.net

- Details of operating system, Python version used, terminal emulator and shell;
Debian GNU/Linux 7 \n \l
Linux server1jax 2.6.32-042stab123.1 #1 SMP Wed Mar 22 15:21:30 MSK 2017 x86_64 GNU/Linux
root@nyserv:/home/googler# python3 --version
Python 3.2.3

- `locale` output, if relevant. It's a good idea to set your locale to UFT-8. Please refer to [googler #131](https://github.com/jarun/googler/issues/131).
root@nyserv:/home/googler2# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

If we need more information and there is no communication from the bug reporter within 7 days from the date of request, we will close the issue. If you have relevant information, resume discussion any time.

#### Feature requests: get it working !

AMAZING PRODUCT IS GOOGLER !

**Comment by shaggytwodope** [comment]
.get_terminal_size() is only available after Python 3.3, While I believe (Debian) Wheezy is only on Python 3.2.

It is explicitly mentioned in the readme:

>googler requires Python 3.4 or later.

**Comment by zmwangx** [comment]
Even Python 3.3 has reached EOL in September 2017. If you're using Python <3.4, you're on your own, dude.

**Comment by salesiss** [comment]
Thanks i've read the docs after trying first runs. More than cutting-edge python >3.4 is a bless and a curse for those who do not upgrade often but try anyway running beautfil code on legacy distros. Salut. non-issue.

**Comment by zmwangx** [comment]
Just to offer an actual solution instead of saying "not our problem":

`os.get_terminal_size` is [implemented in C](https://github.com/python/cpython/blob/bbdb17d19bb1d5443ca4417254e014ad64c04540/Modules/posixmodule.c#L11063-L11064), so it's hard to properly port it to 3.2.*. However, if you cheat and shell out, you can get it working at least for googler's needs. Here's a patch.

```diff
diff --git a/googler b/googler
index 8ddbf59..cc1b835 100755
--- a/googler
+++ b/googler
@@ -46,6 +46,21 @@ except ImportError:
     pass
 
 
+if not hasattr(os, 'get_terminal_size'):
+    def get_terminal_size():
+        try:
+            stty_size = subprocess.check_output(
+                ['stty', 'size'],
+                stderr=subprocess.PIPE,
+            ).decode('utf-8')
+            lines_str, columns_str = stty_size.split()
+            return (int(columns_str), int(lines_str))
+        except Exception:
+            return (80, 24)
+
+    os.get_terminal_size = get_terminal_size
+
+
 # Basic setup
 
 try:
```

If you don't like all the forking going on here, you can also just return a static `(80, 24)`, for instance.

Btw, Debian Wheezy is reaching EOL soon (May 2018), too.

**Comment by salesiss** [comment]
Thanks !! working, we used your modified version returning return( int(cols), int(rows)). Easy it is to modify small/well written programs.  Salut: here a simple my_ get_terminal_size() to others if needed:

    ##substitute/patch for get_terminal_size, insert this new function anywhere near 
    def mysubst_terminal_size(any):
        rows, cols = os.popen('stty size', 'r').read().split()
        #dbg print( "dbg", rows,cols )
        return (int(cols), int(rows))

##usage
    def _print_metadata_and_abstract(self, abstract, metadata=None, indent=0):
        colors = self.colors
        try:
            **columns, _ =  self.mysubst_terminal_size()** <- change here
        except OSError:
            columns = 0


Bye and great job zmwangx!
