### ISSUE TITLE
Feature request: Adapt number of search results to terminal height

### ISSUE THREAD

**Issue by forthrin** [jarun/googler#218]
By default, `googler` should show a number of search results that fits within the current terminal height.

Right now, 10 is the default, which means you always have to scroll back to see the first hits if you have a window of less than 60 lines (which is quite tall!) You always have to scroll back = Not user friendly.

To fit more search results into the terminal, one could also look into setting a cutoff length for site descriptions, which can run into hundreds of characters for some sites, while others are quite short.

**Comment by jarun** [comment]
See #207.

I'll see how easy it is to use URL folding like we do in `ddgr` (if I ever get the time) but that would be the best you get.

If you don't like the idea a PR for review is welcome.
