### ISSUE TITLE
Question: How to return only 2 websites

### ISSUE THREAD

**Issue by justinTM** [jarun/googler#221]
So I want to return 2 results (`-n 2`): one result from `-w youtube.com` and another from `-w soundcloud.com`. Currently, if I were to try `googler -w youtube.com -w soundcloud.com -n 2 test` I will get two results from youtube. 

Is there any way to essentially search for the same thing on two sites and only show `n` results from each website?

Thank you :)

**Comment by jarun** [comment]
You'll need to fire 2 searches (one for each site-specific) with option `-j` and combine the 2 results.
