### ISSUE TITLE
Get only Title instead of full description (feature_request)

### ISSUE THREAD

**Issue by TonyStark** [jarun/googler#229]
#### Feature requests

Well i dont know it is available or not, but is that possible to get search result titles only instead of full description?
Example:
`$ googler --np --[only_title] blah blah`

> 1 I'm Blah blah
> 2 You are Blah blah
> 3 Everyone blah blah
> 4 All people are blah blah
> So on.....

Thank you for wonderful Program :v:

**Comment by jarun** [comment]
HI,

Sorry, this is not available. But i guess you can get the same output with a little bit of scripting.

**Comment by zmwangx** [comment]
Guess what, we provide structured output with `--json`, so no need for text processing with non-guaranteed assumptions.

```console
$ googler --json blah blah | jq -r '.[].title'
Supreme Patty "Blah Blah" Feat. Big Win (WSHH Exclusive - Official ...
Urban Dictionary: blah blah blah
Urban Dictionary: blah-blah
Blah Blah Blah (Kesha song) - Wikipedia
Blah - Wikipedia
Blah-Blah-Blah | DanRoam.com
Blah-blah-blah - Dictionary.com
Blah Blah Blah | Band Music, Lyrics, Photos, Songs, Albums, Photos ...
blah blah blah - Wiktionary
```

If you want the line numbers:

```console
$ googler --json blah blah | jq -r '.[].title' | nl -nln -w1 -s' '
1 Supreme Patty "Blah Blah" Feat. Big Win (WSHH Exclusive - Official ...
2 Urban Dictionary: blah blah blah
3 Urban Dictionary: blah-blah
4 Blah Blah Blah (Kesha song) - Wikipedia
5 Blah - Wikipedia
6 Blah-Blah-Blah | DanRoam.com
7 Blah-blah-blah - Dictionary.com
8 Blah Blah Blah | Band Music, Lyrics, Photos, Songs, Albums, Photos ...
9 blah blah blah - Wiktionary
```

**Comment by jarun** [comment]
Cool! :+1:

**Comment by TonyStark** [comment]
@zmwangx Impressive man :)
