### ISSUE TITLE
Use /usr/bin/env python instead of /usr/bin/python?

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#23]
Maybe it's better to use `/usr/bin/env python` instead of `/usr/bin/python` to allow more flexibility for users stuck on older systems? I'm not sure about whether the following is true, but I heard that OS X Snow Leopard is still stuck on Python 2.6 by default, which might or might not be compatible with this code (I didn't test, but README says 2.7.x is required). And I suppose this could also be a problem for older releases of slow-moving Linux distros, although I'm not sure if anyone's going to use googler on systems that old.

**Comment by jarun** [comment]
I will check this. Thanks for the issue report.

**Comment by jarun** [comment]
Closed at https://github.com/jarun/googler/commit/03a5316fb5a230becc9e3f6a0ebdb48cc9dff16c.
