### ISSUE TITLE
add support for tmux buffer

### ISSUE THREAD

**Issue by jose1711** [jarun/googler#230]
currently googler uses xsel on linux which means it a running Xserver is required to use it. tmux's buffers can be used as a terminal-only solution. it would be great if googler adds support for this (```['tmux', 'setb', self._urltable[cmd[2:]].encode('utf-8')]```)

**Comment by jarun** [comment]
Can you please send a patch? Also, is there a way to determine if we are running on `tmux`?

**Comment by jarun** [comment]
I think the correct check would be to see if `$TERM` starts with `tmux` because there can be multiple strings based on user preference.

Please confirm if the following patch works for you:

```
diff --git a/googler b/googler
index b26dda3..9042af7 100755
--- a/googler
+++ b/googler
@@ -2090,6 +2090,8 @@ class GooglerCmd(object):
                             copier_params = ['pbcopy']
                         elif sys.platform == 'win32':
                             copier_params = ['clip']
+                        elif os.getenv('TERM').startswith('tmux'):
+                            copier_params = ['tmux', 'setb', self._urltable[cmd[2:]].encode('utf-8')]
                         else:
                             copier_params = []
```

**Comment by zmwangx** [comment]
IIRC the correct way to detect tmux is to check the `TMUX_PANE` env var (the `TMUX` env var is probably set, too, but IIRC it's not documented). `TERM` is not a reliable indicator at all; I have

```tmux
set -g default-terminal "screen-256color"
```

in my `.tmux.conf`, for instance.

**Comment by zmwangx** [comment]
By the way, I'm not sure that using a tmux buffer unconditionally within tmux instead of a system-wide clipboard is actually a good idea.

**Comment by jarun** [comment]
Please test the following patch as suggested by @zmwangx:

```
diff --git a/googler b/googler
index b26dda3..1c57ffd 100755
--- a/googler
+++ b/googler
@@ -2090,6 +2090,8 @@ class GooglerCmd(object):
                             copier_params = ['pbcopy']
                         elif sys.platform == 'win32':
                             copier_params = ['clip']
+                        elif os.getenv('TMUX_PANE', None) is not None:
+                            copier_params = ['tmux', 'setb']
                         else:
                             copier_params = []
 

```

**Comment by zmwangx** [comment]
https://github.com/jarun/googler/blob/7b6ad41226d00386a88fe369d02abce43be90a29/googler#L2084-L2094

You'll probably get a `FileNotFoundError` first. Just typing away without testing, but what about:

```py
                        # try copying the url to clipboard using native utilities
                        copier_params = []
                        if sys.platform.startswith(('linux', 'freebsd', 'openbsd')):
                            if shutil.which('xsel'):
                                copier_params = ['xsel', '-b', '-i']
                        elif sys.platform == 'darwin':
                            copier_params = ['pbcopy']
                        elif sys.platform == 'win32':
                            copier_params = ['clip']

                        if not copier_params and os.getenv('TMUX_PANE'):
                            copier_params = ['tmux', 'set-buffer']  # Use the full command instead of the shortcut as no one's typing this

                        if not copier_params:
                            printerr('failed to locate suitable clipboard utility')
```

**Comment by jarun** [comment]
Right!

**Comment by jarun** [comment]
OK. I will provide a patch for you to test in a few hours.

**Comment by jarun** [comment]
@jose1711 I am reverting my patch. I do not use tmux. I requested a patch. See the second comment.

If you want the support, please send a patch.
