### ISSUE TITLE
Anyway to build for android??

### ISSUE THREAD

**Issue by TonyStark** [jarun/googler#236]
Hello again
Is there any way to build using `NDK` for Android (aarch64)?
Or any alternative of Googler which works in android terminal.

Thank you :)

**Comment by jarun** [comment]
If you can run (probably a lean version of python 3.5) on Android, googler would run as well.

Otherwise, I found this:

https://github.com/kivy/python-for-android

I think there may be many other solutions out in the wild.

    googler python on android

;)

**Comment by TonyStark** [comment]
Ok I found that termux app gives python installation. Which is 3.6.5
Will try...

**Comment by TonyStark** [comment]
Done
https://photos.app.goo.gl/Uj45ey1uiOKX7Zsb2

**Comment by jarun** [comment]
Impressive!!! Can you please send a PR to update the documentation on how to do this step-by-step?

**Comment by TonyStark** [comment]
Okay, i will do :)

**Comment by jarun** [comment]
Thank you!
