### ISSUE TITLE
Hi, is there a way to save the output in a txt or json file?

### ISSUE THREAD

**Issue by hiteshbhatia3559** [jarun/googler#238]
#### Bug reports

Before opening an issue, please try to reproduce on [the latest development version](https://github.com/jarun/googler#installing-from-this-repository) first. The bug you noticed might have already been fixed.

If the issue can be reproduced on master, then please make sure you provide the following:
- Output of `googler -d`;
- Link to the response body (you should see a line like `[DEBUG] Response body written to '/Volumes/ramdisk/googler-response-xxxxxxxx'` in the output of `googler -d`; please upload the file to a [gist](https://gist.github.com/) and include the gist's URL in the issue);
- Details of operating system, Python version used, terminal emulator and shell;
- `locale` output, if relevant. It's a good idea to set your locale to UFT-8. Please refer to [googler #131](https://github.com/jarun/googler/issues/131).

If we need more information and there is no communication from the bug reporter within 7 days from the date of request, we will close the issue. If you have relevant information, resume discussion any time.

#### Feature requests
Please consider contributing the feature back to `googler` yourself. Feel free to discuss. We are more than happy to help.

--- PLEASE DELETE THIS LINE AND EVERYTHING ABOVE ---

**Comment by jarun** [comment]
Use option `--json` and redirect to a text file.

**Comment by jarun** [comment]
Read the program help for other options.
