### ISSUE TITLE
Error when opening a link via a terminal based browser

### ISSUE THREAD

**Issue by jinhongjung** [jarun/googler#240]
#### Bug reports

Before opening an issue, please try to reproduce on [the latest development version](https://github.com/jarun/googler#installing-from-this-repository) first. The bug you noticed might have already been fixed.

If the issue can be reproduced on master, then please make sure you provide the following:
- Output of `googler -d`;
- Link to the response body (you should see a line like `[DEBUG] Response body written to '/Volumes/ramdisk/googler-response-xxxxxxxx'` in the output of `googler -d`; please upload the file to a [gist](https://gist.github.com/) and include the gist's URL in the issue);
- Details of operating system, Python version used, terminal emulator and shell;
- `locale` output, if relevant. It's a good idea to set your locale to UFT-8. Please refer to [googler #131](https://github.com/jarun/googler/issues/131).

If we need more information and there is no communication from the bug reporter within 7 days from the date of request, we will close the issue. If you have relevant information, resume discussion any time.

#### Feature requests
Please consider contributing the feature back to `googler` yourself. Feel free to discuss. We are more than happy to help.

--- PLEASE DELETE THIS LINE AND EVERYTHING ABOVE ---
With python 3.7.0 and osx, when I open a search result via w3m, the following error occurs:

googler (? for help) 1
[DEBUG] Opening https://ko.wikipedia.org/wiki/%22Hello,_World!%22_%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8
Traceback (most recent call last):
  File "/usr/local/bin/googler", line 2575, in <module>
    main()
  File "/usr/local/bin/googler", line 2564, in main
    repl.cmdloop()
  File "/usr/local/bin/googler", line 2076, in cmdloop
    open_url(self._urltable[cmd])
  File "/usr/local/bin/googler", line 134, in open_url
    browser = webbrowser.get()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/webbrowser.py", line 42, in get
    register_standard_browsers()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/webbrowser.py", line 567, in register_standard_browsers
    cmd = _synthesize(cmdline, -1)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/webbrowser.py", line 116, in _synthesize
    register(browser, None, controller, update_tryorder)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given

**Comment by jarun** [comment]
Python 3.7 is not tested yet. More info on this issue here: https://github.com/jarun/ddgr/issues/63

**Comment by zmwangx** [comment]
A late reply here. You were apparently experiencing [bpo-31014](https://github.com/python/cpython/pull/7267). Not googler's problem.
