### ISSUE TITLE
Feature Request: Open GUI browser immediately on search

### ISSUE THREAD

**Issue by RatanRSur** [jarun/googler#241]
I couldn't find a set of options that does this but I wanted to use this in a script so I can select text from the terminal and immediately search it in the GUI browser. Something similar to what o does at the prompt.

Thanks!

**Comment by zmwangx** [comment]
To search Google in a GUI browser, you just need to open a URL. How does this have anything to do with googler? We’re not building a launcher here.

**Comment by jarun** [comment]
@RatanRSur we are mostly terminal guys here. What you are looking for is a script to copy selected text (or something like that) from the terminal and open it in the browser from the terminal. To launch the browser with a URI you can check out a opener like `xdg-open`.

This has very little relevance to what googler does. Closing the issue accordingly.

**Comment by RatanRSur** [comment]
I thought it was relevant because it would format a non URI properly for opening in the browser.

@zmwangx If that is the case, then why does the lucky option exist?

**Comment by zmwangx** [comment]
Well, the lucky option requires parsing Google results. What you’re requesting is literally a percent encode away...

**Comment by RatanRSur** [comment]
I was thinking that this is a non-invasive change and would add some flexibility for those times when a user has less terminal real estate.

**Comment by RatanRSur** [comment]
If I already use googler than I can easily hook a script into it so that sometimes I can just shoot off a search from a tmux selection.

**Comment by zmwangx** [comment]
I don’t think spinning up the Python interpreter, import a million modules, run a lot of preparatory code just to do a percent encode is a good use of resources, or an improvement to googler. No, sorry it’s not, and we won’t encourage that by adding an option.

Btw, your implementation fetches and parses the results just to discard them and open the URL (which, as I said, is literally a percent encode away). Although that could have been changed.

**Comment by zmwangx** [comment]
Actually, you know what, let me just write the script for you.

```sh
#!/bin/sh
open "$(python3 -c 'import sys, urllib.parse; print("https://www.google.com/search?q=%s" % urllib.parse.quote_plus(sys.argv[1]))' "$1")"
```

Done. No googler involved. Replace `open(1)` (macOS) with whatever launcher, e.g. `xdg-open`.

**Comment by RatanRSur** [comment]
Ok, no worries. Thanks...for the script I guess...? Pretty condescending thing to do but I guess that's just your style.

**Comment by zmwangx** [comment]
Sure, take it your way. I'm not the one suggesting a weird "feature" here.

**Comment by jarun** [comment]
Hey guys! Calm down, get out from here and take a beer. 💃 

I'm locking this conversation right now.
