### ISSUE TITLE
Google News and more are broken in v3.7.1

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#251]
Google News (`-N`) is broken in v3.7.1: no results. Some smaller things are broken too, e.g., file types are not shown in front of title (e.g. `filetype:pdf` result titles should start with `[PDF] `, but now they are not).

These problems arise from the fact that the user agent `googler/3.7.1` is roughly equivalent to no user agent, and the HTML response needs to be parsed with the `--noua` variant, but the `--noua` variant is guarded by `not ua` conditions.

One way to fix this is to drop the `not ua` guards, but the other branch might need to be reviewed and some code may need to be removed. The other way to fix this is to wait for the v4.0 parser rewrite. I already have a functional version, but it hasn't undergone scrutiny yet.

**Comment by zmwangx** [comment]
Ref #252.

**Comment by jarun** [comment]
Closed at c0ecedef23ec0cd2b9d900442d59fb35b54fdbf3.
