### ISSUE TITLE
new build 3.7.1 seems to solve my "no results"

### ISSUE THREAD

**Issue by kanliot** [jarun/googler#253]
I was using googler about 3 times per day, I guess google decided to block me though, I don't expect much from google. 

```
 $ googler --notweak
Please initiate a query.
googler (? for help) who hid the halibut on the deck
No results.

```

I updated just the main python with https://github.com/jarun/googler/commit/ea5ca238cc2a3aad9ae2a6a3e541424c5f130332

started working again.

I really like this project because firefox has horrible User interface, and this script makes my life easier.

so THANKYOU

**Comment by kanliot** [comment]
also if I need to do a proper reinstall, do you have build instructions for installing from github, not from packages?

**Comment by jarun** [comment]
> so THANKYOU

Glad to know you find googler useful.

> do you have build instructions for installing from github

You'll find the instructions [here](https://github.com/jarun/googler#downloading-a-single-file).
