### ISSUE TITLE
 No results. googler (? for help)

### ISSUE THREAD

**Issue by Fitopatologo79** [jarun/googler#254]
Hi All. I have just installed googler (version 3.5) and I have a problem when running the command to start a search. Indeed, whenever is the query, the output is always "No results".
Example:

~$ googler github
No results.
googler (? for help)

I have Ubuntu 18.04.1 LTS, bionic. Any suggestion? 
Thanks, 
Gabriele

**Comment by jarun** [comment]
It's fixed on master.

**Comment by nickodell** [comment]
Thanks for the tip, jarun!

Running `sudo googler --upgrade`, and upgrading to 3.7.1 fixed this for me. Strangely, Debian is still distributing version 2.9.

**Comment by jarun** [comment]
Yes, the package is a bit older on Debian. But it's a Python script without deps so you can directly get the script and run.

**Comment by szlin** [comment]
@nickodell Actually you can use v3.7.1 of googler in Debian 9 [1] via stretch-backports archive.

@jarun We rarely bump the version of a package after the official release [2], F.Y.I.

[1] https://packages.debian.org/stretch-backports/googler
[2] https://wiki.debian.org/DontBreakDebian#Some_safer_ways_to_install_software_not_available_in_Debian_Stable

**Comment by kcoyner** [comment]
Ubuntu Cosmic (18.10) still uses googler version 3.6.1 which has the "No results" issue.  For now a workaround is to download version 3.7.1 directly from Ubuntu Disco:
https://packages.ubuntu.com/disco/all/googler/download
