### ISSUE TITLE
Windows packaging

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#258]
I created a Chocolatey package: https://chocolatey.org/packages/googler.

As a Windows n00b submitting the first package, I'm not sure how it'll turn out.

**Comment by jarun** [comment]
Awesome! :dancing_men:

**Comment by zmwangx** [comment]
Just noticed the package has been approved.

**Comment by jarun** [comment]
Can you please add it to the list of packagers?

**Comment by jarun** [comment]
I'm adding it now.

**Comment by jarun** [comment]
Added to the list of packagers at 5df231947392475ced257a6ba5e4cec3c3fbb5a9.

Tastes yummy. Thank you! ;)
