### ISSUE TITLE
[ERROR] Failed to get 'https://www.google.com.hk/search?ie=UTF-8&oe=UTF-8&q=hello+world&gws_rd=cr'.

### ISSUE THREAD

**Issue by sonic3366** [jarun/googler#264]
[ERROR] Failed to get 'https://www.google.com.hk/search?ie=UTF-8&oe=UTF-8&q=hello+world&gws_rd=cr'.

**Comment by zmwangx** [comment]
You were given a template. Please respect devs' time and fill it out. The issue as is without update will be closed out soon.

---

#### Bug reports

Before opening an issue, please

💥💥TRY TO REPRODUCE ON [THE LATEST DEVELOPMENT VERSION][master] FIRST💥💥

The bug you noticed might have already been fixed.

[master]: https://github.com/jarun/googler#downloading-a-single-file

If the issue can be reproduced on master, then please make sure you provide the following:
- Output of `googler -d`;
- Link to the response body (you should see a line like `[DEBUG] Response body written to '/Volumes/ramdisk/googler-response-xxxxxxxx'` in the output of `googler -d`; please upload the file to a [gist](https://gist.github.com/) and include the gist's URL in the issue);
- Details of operating system, Python version used, terminal emulator and shell;
- `locale` output, if relevant. It's a good idea to set your locale to UFT-8. Please refer to [googler #131](https://github.com/jarun/googler/issues/131).

If we need more information and there is no communication from the bug reporter within 7 days from the date of request, we will close the issue. If you have relevant information, resume discussion any time.


#### Feature requests
Please consider contributing the feature back to `googler` yourself. Feel free to discuss. We are more than happy to help.

--- PLEASE DELETE THIS LINE AND EVERYTHING ABOVE ---

**Comment by jarun** [comment]
I don't see an issue here. Closing this and locking this conversation.
