### ISSUE TITLE
Country and Language Options working as expected?

### ISSUE THREAD

**Issue by xoihiox** [jarun/googler#265]
Neat little tool, thanks.

I am in Japan, and Japanese results are finding their way into my result pages seemingly in spite of my specified country and language.  Choosing en as the -l ensures mostly english language results, but Japanese results still also appear for searches done even on 'us' or 'in' servers.  Am I doing something wrong?

Here is some debug output:
googler -d -l en -c us
[DEBUG] googler version 3.5
[DEBUG] Python version 3.6.6
[DEBUG] User Agent is disabled
[DEBUG] Connecting to new host www.google.com
Please initiate a query.
googler (? for help) zebra
[DEBUG] Fetching URL /search?hl=en&ie=UTF-8&oe=UTF-8&q=zebra
[DEBUG] Got exception: Remote end closed connection without response.
[DEBUG] Attempting to reconnect...
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?hl=en&ie=UTF-8&oe=UTF-8&q=zebra
[DEBUG] Cookie: 1P_JAR=2018-12-21-15
[DEBUG] Response body written to '/tmp/googler-response-6bdzxppo'.

I run all of my queries through www.google.com/ncr in the browser.  It'd be nice to have a similar option with your tool, if you ever got around to it.

Thanks for reading!

Is the problem maybe occurring here: [DEBUG] Got exception: Remote end closed connection without response?  Maybe I have typed something wrong?

**Comment by zmwangx** [comment]
You’re not actually redirected to google.co.jp; if you were, it would show up in the logs. Therefore, I’m not really sure why the server is giving you Japanese results.

**Comment by xoihiox** [comment]
Hmmm, here are the results.  Please note that results return empy if I do not include the --noua option.

googler --noua -d -l en -c us zebra
[DEBUG] googler version 3.5
[DEBUG] Python version 3.6.6
[DEBUG] User Agent is disabled
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?hl=en&ie=UTF-8&oe=UTF-8&q=zebra
[DEBUG] Cookie: 1P_JAR=2018-12-21-16
[DEBUG] Response body written to '/tmp/googler-response-73ccl66d'.

1 Zebra Technologies | Enterprise Visibility & Data Capture
https://www.zebra.com/us/en.html
Zebra builds enterprise-level data capture and automatic identification solutions that
provide businesses with operational visibility.

2 Zebra Technologies | Empowering a Performance Edge
https://www.zebra.com/ap/en.html
Empower the front line of your operations with Zebra's enterprise data capture and
automatic identification solutions.

3 Zebra - Wikipedia
https://en.wikipedia.org/wiki/Zebra
Zebras are several species of African equids (horse family) united by their distinctive
black and white striped coats. Their stripes come in different patterns, ...

4 ZEBRA | ゼブラ株式会社 | ボールペン・シャープペン・マーカー筆記具全般
https://www.zebra.co.jp/
ボールペン、シャープペン、シャーボ、多機能ペン、マーカー、修正具などの筆記具メーカーのゼブラ株式会社。替芯・部品の販売、修理、お客様相談室。ペン字や宛名の ...

5 ZEBRA | ゼブラ株式会社 | ブレン
https://www.zebra.co.jp/pro/blen/
2018年12月14日 ... ゼブラ商品（ブレン）の商品紹介。替芯情報やJANコードも掲載。

6 ZEBRA | ゼブラ株式会社 | 商品一覧
https://zebra.co.jp/pro/index.html
現在ページ: TOP ＞ 商品一覧. 商品一覧. ボールペン. 油性ボールペン · エマルジョンボールペン · ジェルボールペン · 多色・多機能ボールペン. シャープ. シャープ
· シャーボ ...

7 Zebra Medical Vision | Medical Imaging & AI
https://www.zebra-med.com/
Zebra's mission is to provide radiologists the tools they need to make the next leap in
patient care. The demand for medical imaging services is continuously ...

8 Animanimals: Zebra - YouTube
https://www.youtube.com/watch?v=n5yn7V5QOAE
13 Jul 2014 - 3 min - Uploaded by Filmbilder One day the zebra runs against a tree and
learns something. Script, design, animation: Julia ...

9 zebra - Wiktionary
https://en.wiktionary.org/wiki/zebra
1600; borrowed from Italian zebra, from Portuguese zebra, zebro (“zebra”), from Old
Portuguese enzebro, ezebra, azebra (“wild ass”), from earlier cebrario (882), ...

**Comment by zmwangx** [comment]
Does this happen for other queries? Maybe you're getting this zebra.co.jp result because ZEBRA is a well-known company in Japan? Google may customize results based on your geolocation.

**Comment by zmwangx** [comment]
I mean, based on the example you gave here, I fail to conclude Google is giving you Japanese results in general. You just happened to hit on a relevant Japanese company.

If I search for "nintendo japan" here in the U.S., I get Japanese results too.

**Comment by zmwangx** [comment]
By the way, I missed this part:

> Please note that results return empy if I do not include the --noua option.

Yeah, google made changes and you need to upgrade to 3.7.1.

**Comment by xoihiox** [comment]
googler --noua -d -l en -c us rhinoceros
[DEBUG] googler version 3.5
[DEBUG] Python version 3.6.6
[DEBUG] User Agent is disabled
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?hl=en&ie=UTF-8&oe=UTF-8&q=rhinoceros
[DEBUG] Cookie: 1P_JAR=2018-12-21-16
[DEBUG] Response body written to '/tmp/googler-response-50exr5tu'.

1 Rhino 6 for Windows
https://www.rhino3d.com/
Rhino is a 3D modeler used to create, edit, analyze, document, render, animate, and
translate NURBS* curves, surfaces, and solids, point clouds, and polygon ...

2 Rhinoceros - Wikipedia
https://en.wikipedia.org/wiki/Rhinoceros
A rhinoceros commonly abbreviated to 'rhino', is one of any five extant species of odd-toed
ungulates in the family Rhinocerotidae, as well as any of the ...

3 Rhinoceros | ライノセラス | 3次元CADソフトウェア
https://www.rhino3d.co.jp/
Rhinoceros（ライノセラス）は、NURBSによる3次元モデリングツールです。3D、2D図面作成、レンダリング、豊富なデータフォーマットサポートなど。

4 Basic Facts About Rhinoceroses | Defenders of Wildlife
https://defenders.org/rhinoceros/basic-facts
Rhinoceroses are the largest land mammals after the elephant. There are five species of
rhinos, two African and three Asian. The African species are the white ...

5 Rhinoceros | WWF
http://wwf.panda.org/what_we_do/endangered_species/rhinoceros/
Rhinoceroses are universally recognized by their massive bodies, stumpy legs and either one
or two dermal horns. In some species, the horns may be short or ...

6 Rhino | Species | WWF
https://www.worldwildlife.org/species/rhino
WWF Statement on U.S. House Resolution 1177, Recognizing the Need for China to Maintain its
Ban on Rhinoceros and Tiger Parts December 12, 2018; WWF ...

7 rhinoceros | Horn, Habitat, & Facts | Britannica.com
https://www.britannica.com/animal/rhinoceros-mammal
Rhinoceros: Rhinoceros, any of five or six species of giant horn-bearing herbivores that
include some of the largest living land mammals. Only African and Asian ...

8 African Rhinoceros | Big Five Wildlife - Kruger National Park
http://www.krugerpark.co.za/faq-on-rhino.html
African Rhinoceros. Female rhino with calf. See a beautiful collection of Rhino photos.
Introduction. These mammals are easily recognised by their prehistoric ...

9 Black Rhinoceros - National Geographic Kids
https://kids.nationalgeographic.com/animals/black-rhino/
Black rhinoceroses have a sort of attack-first-and-ask-questions-later attitude. When a
rhino catches the scent of a human or anything else unfamiliar, it is likely ...

Other queries, like 'michael jordan' or 'paris' don't return any Japanese results on the first page.  But I do not associate either zebra or rhinoceros with anything Japanese, company or otherwise.  These queries certainly would, I think, NEVER return japanese-language on the first page for a query done outside-of country in another language, and indeed do not when I run them through the browser at google.com/ncr.

**Comment by xoihiox** [comment]
>Yeah, google made changes and you need to upgrade to 3.7.1.

Do you know I might expect 3.7.1 to hit the debian repos?  Shall I see if 3.7.1 fixes my issue?

**Comment by zmwangx** [comment]
> Do you know I might expect 3.7.1 to hit the debian repos?

Latest googler is in stretch-backports.[1] You're otherwise at the mercy of Debian's nondeterminate release schedule.

[1] https://packages.debian.org/stretch-backports/googler

**Comment by xoihiox** [comment]
>I mean, based on the example you gave here, I fail to conclude Google is giving you Japanese results in general. You just happened to hit on a relevant Japanese company.

>If I search for "nintendo japan" here in the U.S., I get Japanese results too.

I am 99% sure this is not the case.  I chose these queries at random and two exotic animals showing Japanese-*language* results is too strange to be coincidence.  I tried a few more queries to be sure, and I am getting this:

[DEBUG] Fetching URL /search?hl=en&ie=UTF-8&oe=UTF-8&q=horse&start=20
[DEBUG] Response body written to '/tmp/googler-response-_krudd6v'.

1 Racing Australia | Horse Racing Results
https://racingaustralia.horse/home.aspx?standard=true
Racing Australia is the national industry body representing Thoroughbred racing in
Australia. Australian Horse Racing results, Horse Racing Materials.

2 Horse Racing in Japan
http://japanracing.jp/en/
2018.12.16G1 Asahi Hai Futurity Stakes Hanshin Racecourse Result. 2018.12.15G3 Turquoise
Stakes Nakayama Racecourse Result. 2018.12.09G1 Hanshin ...

3 #horse hashtag on Instagram • Photos and Videos
https://www.instagram.com/explore/tags/horse/?hl=en
24.3m Posts - See Instagram photos and videos from 'horse' hashtag.

4 Horse Racing - The Hong Kong Jockey Club - hkjc
https://racing.hkjc.com/racing/english/index.aspx
Racing Section Homepage provides the latest event information, racing news, race meeting
reminder, featured races and events at the Racecourses.

5 Horse – Official Minecraft Wiki
https://minecraft.gamepedia.com/Horse
14 Dec 2018 ... The horse is a calm and confident compatriot out in the Minecraft wilds.
Found in herds of two-to-six, they roam the plains and savanna biomes ...

6 Horse Search - Equibase
https://www.equibase.com/profiles/Results.cfm?type=Horse
Welcome to Equibase.com, your official source for horse racing results, mobile racing data,
statistics as well as all other horse racing and thoroughbred racing ...

7 Fast Results - Horse Racing - Sporting Life
https://www.sportinglife.com/racing/fast-results
The latest results as they happen from Sporting Life's Fast Results service.

8 The Horse Magazine
https://www.horsemagazine.com/
It's the feature of Frankfurt Horse Show, the prestige class for dressage horses aged 7 to
9 - the Nürnberger Burg-Pokal. On the spot report......more ...

9 Horse | Definition of Horse by Merriam-Webster
https://www.merriam-webster.com/dictionary/horse
Horse definition is - a large solid-hoofed herbivorous ungulate mammal (Equus caballus,
family Equidae, the horse family) domesticated since prehistoric times ...

10 UK & Ireland Results - Horse Racing - BBC Sport
https://www.bbc.com/sport/horse-racing/uk-ireland/results
Find out out all the horse racing results for the last 14 days for races in the UK and
Ireland on BBC Sport. ... Horse Racing UK & Ireland Results ...

Horse racing in Japan on the 2nd page for a 'horse' query?  Also, I am not cherry-picking these queries.  These results are all from a set of less than 12 total queries.

**Comment by zmwangx** [comment]
As I pointed out above

> Google may customize results based on your geolocation.

And contribution for the ncr thing is welcome.

**Comment by xoihiox** [comment]
Ahh, sorry, I didn't see that part.  That is definitely what is happening.  I'll edit the search string and let you guys know how it is done.

In the meantine, this is the string that will ensure untained north american english-language results: https://www.google.com/search?q=%s&pws=0&gl=us&gws_rd=cr.

Thanks.

**Comment by jarun** [comment]
Closing it as there's no update in more then 3 weeks.
