### ISSUE TITLE
PSA: upgrade to Python 3.7.2 for fixed webbrowser module

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#266]
Python 3.7.2 was released earlier today, so it’s a good time to remind Python 3.7 users to upgrade, and have an issue to refer to in the future, since due to screwups in the `webbrowser` module in both 3.7.0 and 3.7.1, googler does not function properly.

Specifically,

- 3.7.0: completely broken due to [bpo-31014](
https://bugs.python.org/issue31014). Symptom: `TypeError: register() takes from 2 to 3 positional arguments but 4 were given`.

- 3.7.1: `BROWSER` env var may not be respected due to [bpo-35308](
https://bugs.python.org/issue35308). Spotted and fixed by yours truly.

Typing this over a restaurant table as I wait for my food, so do excuse typos. Happy whatever holidays (or lack thereof) you celebrate.

**Comment by jarun** [comment]
Thank you! 
Happy Holidays to you too! :)

**Comment by jarun** [comment]
Are you visiting someplace during the holidays? I just returned from a long drive from [Pondicherry](https://en.wikipedia.org/wiki/Pondicherry).

**Comment by zmwangx** [comment]
Um, no, just business as usual for me. I’m firmly against Christian holidays, and indifferent to holidays in general.

**Comment by jarun** [comment]
Hmm... poor kid... holidays are atheist in nature. ;)
