### ISSUE TITLE
Can google be used as API?

### ISSUE THREAD

**Issue by caballerofelipe** [jarun/googler#267]
I would love to use this as an API in a Python project of my own... can it be done? (I mean of course it can but I mean without spending too much time on changing it).

**Comment by zmwangx** [comment]
Well, we don't support the use case, but just read the code, with `main` as the entry point? There are four main components: the URL builder, the HTTP client, the response parser, and the REPL. Each of course has its own private API.

Without knowing your exact needs, it's hard to say if you need to change anything, let alone "too much"; so we can't really tell you much without you reading the code, and if you do you probably don't need explanations anyway. Lastly, we're unlikely to rewrite anything if there are specific needs, and stability of a private API is of course not guaranteed.

Probably enough said. Feel free to ask more specific questions.

(Beware the GPL, by the way.)

**Comment by jarun** [comment]
Also, note that using scripts to automate searches is against google's policy: https://support.google.com/webmasters/answer/66357?hl=en
