### ISSUE TITLE
Think it stopped working with youtube

### ISSUE THREAD

**Issue by anoopd** [jarun/googler#268]
When i try to do `googler -w youtube.com ` and then search it is returning `no results` . Any idea on why it is not giving search results from youtube ?

**Comment by jarun** [comment]
Please ensure you are on v3.7.1.

Works fine for me:

```
$ googler -w youtube.com hello

 1.  Adele - Hello - YouTube [www.youtube.com]
     22 Oct 2015 - 6 min - Uploaded by AdeleVEVO'Hello' is taken from the new album, 25, out November 20.
     http://adele.com  Available now ...

 2.  Adele - Hello (Live at the NRJ Awards) - YouTube [www.youtube.com]
     9 Nov 2015 - 5 min - Uploaded by AdeleVEVO'Hello' is taken from the new album, 25, out November 20.
     http://adele.com  Available now ...

 3.  hello - YouTube [www.youtube.com]
     22 Aug 2017 - 3 min - Uploaded by LauvI met you when I was 18. is a collection of songs, a story.
     about making a big  move, falling in love ...

 4.  Adele - Hello (Official Lyrics Video) HD - YouTube [www.youtube.com]
     30 Nov 2015 - 5 min - Uploaded by Lyrics and MoreMix - Adele - Hello (Official Lyrics Video)
     HDYouTube. Top 7 Acts "JUDGES  START TO CRY ...

 5.  Fickle Friends - Hello Hello (Official Audio) - YouTube [www.youtube.com]
     8 Mar 2017 - 3 min - Uploaded by FickleFriendsVEVOMusic video by Fickle Friends performing Hello
     Hello. (C) 2017 Polydor Records,  a division of ...

 6.  Hello - YouTube [www.youtube.com]
     ... with James Proud: Why We Sleep the Way We Do. 3,818 views 2 years ago. On Charlie Rose, a
     conversation with James Proud, Founder and CEO of Hello.

 7.  Hello - Walk off the Earth + Myles & Isaac (Tap Dance Cover ... [www.youtube.com]
     19 Jan 2016 - 5 min - Uploaded by Walk off the EarthStream or Download Our Music Here:
     https://walkofftheearthent.lnk.to/WOTE  Catch us live ...

 8.  HELLO 2019 X7 - YouTube [www.youtube.com]
     1 day ago - 6 min - Uploaded by The GllaDusDiscord : https://discord.gg/aSdptJn Leave a like if u
     enjoy! twitter:https://twitter. com/TheGllaDus ...

 9.  Adele - Hello (Lyrics) - YouTube [www.youtube.com]
     14 Aug 2017 - 4 min - Uploaded by Adele TVThis is the live version of Hello at SNL~ Like &
     Subscribe!

 10. Hello 2019 - YouTube [www.youtube.com]
     4 Jan 2019 - 5 min - Uploaded by DOLLARMerch STORE LINK https://teespring.com/stores/dollar 20% off
     till end of 2018  just type ...

googler (? for help)
```

**Comment by farhan1243** [comment]
Sent from Yahoo Mail on Android 
 
  On Mon, 14 Jan 2019 at 6:54 pm, Arun Prakash Jana<notifications@github.com> wrote:   
Please ensure you are on v3.7.1.

Works fine for me:
$ googler -w youtube.com hello

 1.  Adele - Hello - YouTube [www.youtube.com]
     22 Oct 2015 - 6 min - Uploaded by AdeleVEVO'Hello' is taken from the new album, 25, out November 20.
     http://adele.com  Available now ...

 2.  Adele - Hello (Live at the NRJ Awards) - YouTube [www.youtube.com]
     9 Nov 2015 - 5 min - Uploaded by AdeleVEVO'Hello' is taken from the new album, 25, out November 20.
     http://adele.com  Available now ...

 3.  hello - YouTube [www.youtube.com]
     22 Aug 2017 - 3 min - Uploaded by LauvI met you when I was 18. is a collection of songs, a story.
     about making a big  move, falling in love ...

 4.  Adele - Hello (Official Lyrics Video) HD - YouTube [www.youtube.com]
     30 Nov 2015 - 5 min - Uploaded by Lyrics and MoreMix - Adele - Hello (Official Lyrics Video)
     HDYouTube. Top 7 Acts "JUDGES  START TO CRY ...

 5.  Fickle Friends - Hello Hello (Official Audio) - YouTube [www.youtube.com]
     8 Mar 2017 - 3 min - Uploaded by FickleFriendsVEVOMusic video by Fickle Friends performing Hello
     Hello. (C) 2017 Polydor Records,  a division of ...

 6.  Hello - YouTube [www.youtube.com]
     ... with James Proud: Why We Sleep the Way We Do. 3,818 views 2 years ago. On Charlie Rose, a
     conversation with James Proud, Founder and CEO of Hello.

 7.  Hello - Walk off the Earth + Myles & Isaac (Tap Dance Cover ... [www.youtube.com]
     19 Jan 2016 - 5 min - Uploaded by Walk off the EarthStream or Download Our Music Here:
     https://walkofftheearthent.lnk.to/WOTE  Catch us live ...

 8.  HELLO 2019 X7 - YouTube [www.youtube.com]
     1 day ago - 6 min - Uploaded by The GllaDusDiscord : https://discord.gg/aSdptJn Leave a like if u
     enjoy! twitter:https://twitter. com/TheGllaDus ...

 9.  Adele - Hello (Lyrics) - YouTube [www.youtube.com]
     14 Aug 2017 - 4 min - Uploaded by Adele TVThis is the live version of Hello at SNL~ Like &
     Subscribe!

 10. Hello 2019 - YouTube [www.youtube.com]
     4 Jan 2019 - 5 min - Uploaded by DOLLARMerch STORE LINK https://teespring.com/stores/dollar 20% off
     till end of 2018  just type ...

googler (? for help)

**Comment by anoopd** [comment]
I cloned it again and did a make install and it works well right now . Thank you .
