### ISSUE TITLE
download link in README.md is broken

### ISSUE THREAD

**Issue by nosarthur** [jarun/googler#270]
I tried to download the executable as shown in the README.md

```
chronos bin $ sudo curl -o /usr/local/bin/googler https://raw.githubusercontent.com/jarun/googler/v3.7.1/googler && sudo chmod +x /usr/local/bin/googler

curl: (6) Couldn't resolve host 'raw.githubusercontent.com'
```
But if I go to that link in web browser, it is able to show the python file content. Is it just a problem with my machine?

**Comment by jarun** [comment]
> Is it just a problem with my machine?

I believe this is a local issue. I was able to run it successfully.

Are you able to ping `raw.githubusercontent.com`?

**Comment by nosarthur** [comment]
I was unable to ping it. I will close it. Maybe there is some network issue from my side. Sorry for the false alarm
