### ISSUE TITLE
News not working

### ISSUE THREAD

**Issue by taewookim** [jarun/googler#271]
Is this a known issue?

googler -d --news --json -t d5 -n 3 --np -C Election
[DEBUG] googler version 3.7.1
[DEBUG] Python version 3.6.5
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&num=3&oe=UTF-8&q=Election&tbm=nws&tbs=qdr:d5
[DEBUG] Cookie: 1P_JAR=2019-02-28-22
[DEBUG] Response body written to '/tmp/googler-response-l5h5g7q2'.
[]

**Comment by jarun** [comment]
Please use master till the next release.

**Comment by taewookim** [comment]
yeah that seemed to have solved it

**Comment by rilian4** [comment]
Thanks for this tip. I just stumbled across this great tool today and had the same issue. Master fixed it!
