### ISSUE TITLE
Migrate from Travis to CircleCI

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#273]
Travis was recently acquired by a holding company [1] and fired their senior engineering staff immediately afterwards [2]. Meanwhile, py38 is coming (3 alphas already out) and given the shitshow that was py37 support on Travis (which literally took more than a year since stable release [3]) long before key engineering staff was fired, the future is pretty bleak.

I suggest we migrate to CircleCI, which seems to be the most recommended CI service these days. I've used it for one of my projects, and while its syntax could be somewhat quirky, and build matrix support is glaringly missing in some cases (I'm talking about the machine executor; you need yaml shenanigans to emulate the effect of a build matrix and even then you need to repeat yourself a lot), I believe the container architecture could be pretty pleasant for an uncomplicated project like googler.

I'll try to put googler on CircleCI when I have time, and see how it goes.

Alternatively, Azure Pipeline (actually used by python/cpython) may also be something we could look into, which would bring Windows testing into the mix (Travis added Windows support too but I found it rather painful). 

[1] https://news.ycombinator.com/item?id=18978251
[2] https://news.ycombinator.com/item?id=19218036
[3] Yeah, I know a large part of that was due to OpenSSL and Travis' reluctance to migrate out of trusty to xenial (we got xenial on Travis after bionic was out for quite a while, think about that), so py38 may not be remotely as bad, but my confidence in Travis was lost long ago.

**Comment by jarun** [comment]
Yes, I was also surprised the way 3.7 was dealt with. All n for CircleCI.
