### ISSUE TITLE
Always need to scroll back on short terminals

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#281]
This is a somewhat frequent complaint (#207, #218, and scattered on hijacked threads). 

There's a fairly obvious solution for this — a goddamn pager! (For some reason I haven't thought of this until now, maybe because of the XY problem — users were always suggesting a dynamic number of results, which is both unnecessarily hard to implement and a poor fit for our paging model, and I was caught up in why that's a bad idea instead of tackling the root cause.)

More concretely, we just need to pipe output into `less -EFX` (`-E` — `--QUIT-AT-EOF`; `-F` — `--quit-if-one-screen`; `-X` — `--no-init`). A tried and true paging technique.

There are two problems with `less -EFX` that are worth mentioning:

1. If user quits early, the rest of the output is lost. We can of course implement a "repeat" command (`r` is conveniently still available) to repeat the current page's results, which largely mitigates the problem. This does mean we can't make paging the default, though. It has to be behind an option (`-P`, `--pager` should be good enough), and discoverability would suffer.

   Discoverability is a really hairy problem for a program that pledges to leave no trace on user's disk. I guess we could suggest the option *once* in each interactive session where the output is ~longer~ way longer than a screenful. That shouldn't be too annoying for people who don't want it, right?

2. `less` is universal enough, with one catch: BusyBox's `less` doesn't have `-F` or `-X` [1] (I'm not even sure if it supports ANSI escapes, haven't tried). A simple preflight with `--help` should shake that out though. I'm not aware of any other `less` implementation except the most common one found in both Linux and BSD.

@jarun Let me know your thoughts.

[1] https://busybox.net/downloads/BusyBox.html#less

**Comment by zmwangx** [comment]
Unrelated: I haven't forgot about the installer script I talked about the other day. I already wrote it a few days ago, but haven't found time to satisfactorily test it yet.

**Comment by jarun** [comment]
I use `less` to show output in some screens in `nnn` but this is a completely different case. I don't know anyone who doesn't set the minimum size of his/her terminal carefully. That's kind of fixed for users.

So where's the problem in using a namesake alias to limit the number of results shown per page? E.g.:

    alias googler=googler -n 6
You can even use auto-completion.

And in those one-off cases where still the output is longer, <kbd>Shift+PgUp/PgDn</kbd> handles that. I would say we should simply document the above two and leave it. I know many people who aren't aware of the <kbd>Shift+PgUp/PgDn</kbd> key and the first thing they do is to grab the mouse.

**Comment by zmwangx** [comment]
A couple of counter arguments, loosely ordered from most to least important.

1. > I don't know anyone who doesn't set the regular size of his/her terminal carefully

   I unapologetically don't, for good reason. My daily driver is a 15'' MacBook Pro, set at 1920x1200 resolution. My terminals by default are 82x158, or when I full screen, two 85x158 side-by-side. However, I vertically split a lot. 82 lines are usually split into two 41 lines, but I don't stop at that; three or four vertical panes are regular sights too. So I could have really short panes. And I'm not that sort of person who always a fixed set of pane arrangements and always runs a certain command in a certain pane.

2. > where's the problem in using a namesake alias to limit the number of results shown per page

   i) Number of lines taken by a fixed number of results isn't fixed. Depending on your terminal width and length of abstracts, 6 results could be 24 lines, or 42 lines. You could set a conservative number which could (a) be very small (b) regularly leave you with a lot of unutilized vertical space; or you could set an aggressive number and regularly have to scroll.

   ii) Fewer number of results per page means more requests — more remote paging than local paging. That also uses even more vertical space for the same amount of information due to prompts being printed, and prompts interrupt the flow of information. Paging with `n` and `p` is probably takes more mental effort too.

3. Even if scrolling back is easy, what's so bad about it?

   Well, **a search engine should emphasize the most relevant results.** When you're **presented with less relevant results and need to scroll back to access the more relevant ones**, that's a UX failure.

   Which naturally brings us to, **what's great about `less -EFX`**?

   - When the output fits in one screenful, **it does nothing**. You read however you like.
   - When the output is more than one screenful, **you're presented with the most relevant results first**, and you **scroll forward instead of backward**. Some nicer details:
     + **Scrolling within `less` is very versatile.** You can (roughly) continuously scroll with j/k/arrow keys/etc., do page jumps with space/f/b/z/w, or even scroll with mouse wheel or touchpad gesture. Few if any terminal emulator's scrollback buffer is that accessible or versatile; if it some terminal emulator can do all those things, first it's hard to discover (try to consult a terminal emulator manual or check all its keybindings, compared to run `less --help`), secondly since less is modal, you don't need modifier keys for anything (vim users always use that against us Emacs users).
     + **You can even quit early if you find relevant results early.** Compared to scrolling back, where you basically have to scroll back however many pages there are.
   - Oh, and with `-E` and `-X`, when you scroll to the end, less quits automatically, and you're left in a state as if nothing ever happened.

4. **The ability to scroll back isn't even a given.**

   A notable example is [mosh](https://mosh.org/). It's an awesome ssh alternative for slow connections or roaming. I've used it sparingly for at least five years, and really ramped up usage in the last couple of months to access some high ping / high packet loss servers. Mosh handles the terminal emulation (which is essential for some of its main differentiators), like a terminal emulator inside your regular terminal emulator; an unfortunate side effect is that you lose access to a scroll buffer (unlike tmux where you can scroll back if you want to, although extremely unpleasant without native control mode integration).

   Meanwhile, a pager like less could navigate the lowest common denominator of terminal emulation (it even works in dumb terminals — try Emacs shell mode — albeit not fully functional).

   Obviously, one don't have to support the "harsh conditions". However, googler is interactive by default, so in the aforementioned "harsh condition" users can't really pipe output to less and call it a day, so native integration for them would be great.

   (As I pointed out above, such users aren't fictional, since I happen to be one from time to time.)

5. > Shift+PgUp/PgDn handles that.

   **That statement packs a lot of assumptions and personal preferences.**
   - I assume you're talking about Gnome terminal. Keybindings are not universal across terminal emulators.
   - You're assuming a keyboard with PgUp/PgDn. Many laptop keyboard don't have that. Some compact desktop keyboards don't have that.
   - Even when PgUp/PgDn are available, they're way off home row, even Mozart probably needs to leave the home row to hit them. I as well as many people don't want to leave the home row at all. See point above on "scrolling within `less` is very versatile".

Ultimately, this is about giving a subset of users, some of whom have been vocal, a **non-default option** to rather **subtly tweak** (options to less have been carefully chosen to preserve as much of existing behavior as possible) **existing behavior for the better** (IMO). One can of course tell those users "you're using it wrong", but I can totally see where they're coming from (and hopefully I've presented the case), and I believe I can give them a better UX.

**Comment by jarun** [comment]
> a non-default option

I think I missed this earlier. I am fine with non-default.

**Comment by EvanDotPro** [comment]
@zmwangx @jarun What about simply adding an `-r` / `--reverse` option that outputs the search results in reverse order?

**Comment by EvanDotPro** [comment]
Also maybe I'm just dumb, but I can't understand for the life of me how one would simply choose a result to open when `googler` interactive output is being displayed by `less -EFXR`. Piping an interactive program to `less` causes all sorts of unexpected weirdness and `less` intercepts all keyboard input AFAIK.

The only way I can get `less` to behave with `googler` output is if I use `--noprompt`... But then what? Use my _mouse_ to click the URL I want?

Surely I'm missing something here about how `less` can play nice with an interactive program like `googler`.

**Comment by jarun** [comment]
I think reversing the results is a good idea if we can ensure the indices are shown in reverse too. Can you please raise a PR for this?

**Comment by EvanDotPro** [comment]
Sure!

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
Just wait till we hear from @zmwangx.

**Comment by EvanDotPro** [comment]
Sure thing. Especially since @zmwangx mentioned portentially using `-r` for repeating output earlier in this thread.

**Comment by zmwangx** [comment]
@EvanDotPro You misunderstood my proposal. Each screenful of result is piped into less, not everything, not any already interactive part. You read the results, manually exit less (or it automatically exits when you reach the end), then do whatever with googler like you’re used to.

Now, reversing the printing order of results is one solution (with the benefit of being trivial to implement, even). I definitely support its inclusion, but I would personally find this more pretty weird.

**Comment by NightMachinary** [comment]
Chiming in to say I use this only for —noprompt, and I’d love a pager option.

**Comment by zmwangx** [comment]
This is a bit complex if to be implemented well (compatibility with busybox less, for instance) and there's not a whole lot of interest, especially not from me anymore, so closing for now.

A less polished implementation can be hacked up in ten minutes though. If anyone would like to see it but can't DIY, just ask.

**Comment by jarun** [comment]
If possible, implement the reversal of results. It would be useful.

**Comment by zmwangx** [comment]
That's easy enough.
