### ISSUE TITLE
Intermittent "no results" due to Google sending an alternative layout not supported by the parser

### ISSUE THREAD

**Issue by mmblz** [jarun/googler#284]
I'm trying to get the URL of the first result, to use in further scripting. I'm using a command line like:
googler -j --url-handler echo Adium software

It fails intermittently (and frequently) with "No results."

Is this because of the comment about how ads can affect parsing?

Mac 10.12.6
[DEBUG] googler version 3.8
[DEBUG] Python version 3.7.3

Is there any way to make this work? I need the URL for further scripting (using quicklook to preview, passing in to sed/awk to insert into a file, etc.

**Comment by jarun** [comment]
Try:

    googler -j Adium software --url-handler echo

@zmwangx any idea why this happens when the order is changed? I could reproduce it with the oder mentioned in the defect. Happens every alternative time. But I can see there's result in the response dump.

**Comment by mmblz** [comment]
I tried the suggested order but it's no different. As an example I just got success, fail, fail, fail, fail, success, success, success, fail, fail, fail

**Comment by mmblz** [comment]
I turned on debug:

googler-3.8 $ googler -d -j Adium software --url-handler echo
[DEBUG] googler version 3.8
[DEBUG] Python version 3.7.3
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=Adium+software&sei=+0ZbdH2UEemTHfQPJDEXUA
[DEBUG] Cookie: 1P_JAR=2019-05-23-19
[DEBUG] Response body written to '/var/folders/x5/7630r43x0xg8nnn9km38qg9c0000gn/T/googler-response-xvke270k'.
No results.
[adium-fail.txt](https://github.com/jarun/googler/files/3213926/adium-fail.txt)

**Comment by jarun** [comment]
> I tried the suggested order but it's no different

That's a little strange as it worked for me. But I did not try too many times.

**Comment by mmblz** [comment]
for comparison here's from when it succeeds. after syntax / pretty print and diff, they are fairly different but beyond that I'm not sure what the critical difference is (or why)

[adium-works.txt](https://github.com/jarun/googler/files/3214037/adium-works.txt)

**Comment by zmwangx** [comment]
This got nothing to do with the order of arguments. Google was sending you a different layout (the more modern layout instead of the classic one which we expect when using a non-browser UA `googler/3.8`). Just look at the two HTML files you attached in a browser, the difference is obvious:

<img width="1004" alt="Screen Shot 2019-05-24 at 9 34 08 AM" src="https://user-images.githubusercontent.com/4149852/58296767-9b7c5b80-7e07-11e9-8152-e666d0dc56ee.png">
<img width="1004" alt="Screen Shot 2019-05-24 at 9 34 11 AM" src="https://user-images.githubusercontent.com/4149852/58296768-a0d9a600-7e07-11e9-994f-d4c3d02bdcc4.png">

I can look into the failed case and see if our parser could support that one too, but sometimes Google does temporary A/B testing and stuff. I'm short on time recently, so please let me know if this is actually a persistent issue before I delve into it.

**Comment by zmwangx** [comment]
Now that I look at the former image more closely, that's not even a desktop layout. I've only seen the every-result-in-a-card layout on mobile. Hopefully just an A/B test (they can't seriously think `googler/3.8` is the UA of a phone browser, can they?).

**Comment by zmwangx** [comment]
Update: I was consistently getting the classic layout when I first looked at the bug ten minutes ago. But now I'm getting the card layout almost every damn time... I suppose we can wait for 24 hours and see if the mobile layout just stops, but if not we definitely need to support the different layout.

I'm changing the title of this issue as it has nothing to do with `-j`.

**Comment by mmblz** [comment]
Using Safari and setting the agent to googler/3.8 - in a normal window I seem to always get the card layout. In a private window I seem to always get the classic layout. The card layout is complicated by the css apparently having been obfuscated.
<img width="500" alt="Screen Shot 2019-05-23 at 10 29 28 PM" src="https://user-images.githubusercontent.com/50965168/58298671-4ceca400-7daa-11e9-93eb-bda8b445ec13.png">

**Comment by zmwangx** [comment]
> The card layout is complicated by the css apparently having been obfuscated.

This sure is annoying. All hail lack of namespacing of CSS and as a result crazy shit like this people resort to.

**Comment by jarun** [comment]
@zmwangx w3m is still working for me. How about you? How about switching the UA?

**Comment by mmblz** [comment]
I was playing with user agent in the browser some more - it seemed like this dictated bad format or not. I tried to get the shortest agent string that gave the desired visual result in the browser and came up with 'googler/5.0 (Trident/7.0;)' ... but then when I put this in googler script it still failed intermittently.

**Comment by zmwangx** [comment]
Briefly tried `w3m/0.5.3` and still getting intermittent card results. If by "w3m is still working for me" you mean Google works inside w3m, then sure, they just show you the text; layout doesn't matter much.

One way out is finding a user agent that reliably produces the classic layout (IE8 maybe?). Another way out is use a know modern browser UA, and parse the modern desktop layout instead.

**Comment by jarun** [comment]
> Another way out is use a know modern browser UA, and parse the modern desktop layout instead.

I agree this is the best path going forward.

**Comment by mmblz** [comment]
maybe agent is a bit of a red herring - I just hardcoded this in the script:
USER_AGENT = ('Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0)')

and still get both results...

**Comment by zmwangx** [comment]
I'm pretty sure user agent is key here; it's not the first time we dealt with layout problems. 

> Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0)

Is that IE7? I don't have intermittent problems with that UA, but it could be dumb luck, I don't know if Google is supposed to recognize that. But, I'm fairly sure if you use a modern user agent like `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0`, you're guaranteed to get the modern desktop layout (note that the parser currently can't handle it), at the cost of stability (of the classic layout) and the possibility of being dragged into an A/B test any time.

**Comment by mmblz** [comment]
oops - I had two copies of script.
yes, that's IE and seems to work. google seems to use bubbles for anything it doesn't recognize

**Comment by jarun** [comment]
Yes, I'm also getting consistent results with

    USER_AGENT = ('Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0)')

**Comment by mmblz** [comment]
This also seems to work; their sniff is apparently pretty rudimentary:
`googler/3.8 (MSIE 7.0)`

**Comment by jarun** [comment]
USER_AGENT = ('googler/3.8 (MSIE 7.0)')
works consistently for me too.

**Comment by mmblz** [comment]
or even:
`googler/3.8 (MSIE)`

**Comment by jarun** [comment]
@zmwangx do you think for the time being we can switch to `googler/3.8 (MSIE)`?

**Comment by zmwangx** [comment]
What about `googler/3.8 (like MSIE)`? (I might be one of the few people who want the UA to mean something.)

While we're at it, `--noua` option should be removed (or made a noop and emit a deprecation warning, your call). Disabling user agent is no longer a reliable way to get the classic layout. The `ua` global variable should go, too, thank god it's been a thorn in my eyes.

**Comment by jarun** [comment]
`googler/3.8 (like MSIE)` works for me. @mmblz please confirm.

> While we're at it, --noua option should be removed

My thoughts exactly.

> `ua` global variable should go, too

Yes, can't request you to keep your eyes closed forever ;)

**Comment by jarun** [comment]
@mmblz if your tests are positive with the proposed UA string can you please raise a PR with the above changes?

**Comment by zmwangx** [comment]
> can you please raise a PR with the above changes?

Or I could do it (not trying to take credit, I'm just more efficient since I probably know the code better and know what to change/remove immediately). If you want to be officially recognized for the contribution then go for it.

**Comment by mmblz** [comment]
I'm new to github - you'll get it done faster :) I'm just grateful for the neat script.

**Comment by jarun** [comment]
@zmwangx have fun! ;)

**Comment by jarun** [comment]
Please push directly. I must run now...

**Comment by zmwangx** [comment]
Sure.

**Comment by zmwangx** [comment]
Oh by the way I need to take care of something else too so expect the patch in 1-2 hours.

**Comment by zmwangx** [comment]
Pushed to master. Might need to issue a patch release.

Thanks @mmblz for the report and investigation.

Notes to @jarun and self:

- Shell completion scripts haven't been updated in quite a while.
- I need to fix the CI tests to catch mark no results as failure on known good queries.

**Comment by jarun** [comment]
The auto-completion scripts are updated at commit c66f129249742e65e49f3a7a7211ab13a90f207f.

**Comment by kbrmimbyl** [comment]
Getting No Results on Ubuntu 16.04. Is there a way to specify the UA using a command-line switch?

**Comment by steackfrite** [comment]
Hi!
Same as @mmblz for the debug:
# googler "site=*.example.com" -d
[DEBUG] googler version 3.7.1
[DEBUG] Python version 3.7.5
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=site%3D%2A.example.com
[DEBUG] Cookie: 1P_JAR=2019-10-14-13
[DEBUG] Response body written to '/tmp/googler-response-bshauhjs'.
No results.

When I check '/tmp/googler-response-bshauhjs' it is indeed a different google css.
![Capture d’écran du 2019-10-14 15-42-19](https://user-images.githubusercontent.com/11270947/66755376-24b82b80-ee98-11e9-81ad-35f5accc9779.png)

**Comment by jarun** [comment]
Are you guys on v3.9 or master?

**Comment by kbrmimbyl** [comment]
I'm on this v3.4: https://launchpad.net/~twodopeshaggy/+archive/ubuntu/jarun/+files/googler_3.4.0-1_all.deb

**Comment by kbrmimbyl** [comment]
Oops, sorry I didn't know about 3.9. I just switched to it from the releases here on github and it's working perfectly!

**Comment by steackfrite** [comment]
Same there! Kali linux doesn't have the last version on their repo.
Sorry for the noise.

**Comment by jarun** [comment]
No problem!

**Comment by kbrmimbyl** [comment]
@jarun, Thanks a ton for googler, man! I see that you're very passionate about terminal-based tools. I wish we could go back to the terminal for everything on the internet!
