### ISSUE TITLE
googler returns no results on macOS

### ISSUE THREAD

**Issue by capaldo** [jarun/googler#285]
Googler randomly stopped working.

- Output of `googler -d`;
```bash
[DEBUG] googler version 3.8
[DEBUG] Python version 3.7.3
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=hey&sei=bHm2On5gEemeiLxqL1Zn7A
[DEBUG] Cookie: 1P_JAR=2019-05-24-20
[DEBUG] Response body written to '/var/folders/n_/w73w9xg12qv85qdnq3ytx90c0000gn/T/googler-response-toe16sfg'.
No results.
```

[gist URL](https://gist.github.com/capaldo/c0286239864c68d86d0e90493cf73f06)

- macOS 10.14.5
- python 3.7.3
- Details of operating system, Python version used, terminal emulator and shell;
- `locale` output, if relevant. It's a good idea to set your locale to UFT-8. Please refer to [googler #131](https://github.com/jarun/googler/issues/131).

**Comment by jarun** [comment]
Probably you are facing https://github.com/jarun/googler/issues/284. Please try master.

**Comment by capaldo** [comment]
> Probably you are facing #284. Please try master.

Works. Thanks for your help. Any ETA on the homebrew version being updated?

**Comment by jarun** [comment]
It would be soon, but I can't give a date yet.

**Comment by capaldo** [comment]
thank you for your work!
