### ISSUE TITLE
Abstract wraps at lesser number of columns

### ISSUE THREAD

**Issue by jarun** [jarun/googler#287]
@zmwangx looks like we have a slight issue with the number of characters printed much lesser than the number of available columns. This has been introduce with PR #283.

Output from released v3.9:

```
~/G/googler$ g hello world

 1.  "Hello, World!" program - Wikipedia [en.wikipedia.org]
     A "Hello, World!" program generally is a computer program that outputs or displays
     the message "Hello, World!". Such a program is very simple in most ...

 2.  hello world - YouTube [www.youtube.com]
     30 Mar 2018 - 2 min - Uploaded by Louie Zonga test of a virtual singer software - http://www.myriad-
     online.com/en/products/ virtualsinger.htm ...

 3.  Hello, World! - Learn Java - Free Interactive Java Tutorial [www.learnjavaonline.org]
     Hello, World! Java is an object oriented language (OOP). Java objects are part of
     so-called "Java classes". Let's go over the Hello world program, which simply ...

 4.  What is Hello World? - Definition from WhatIs.com [whatis.techtarget.com]
     Hello World is a simple program that, when run, displays the message: Hello
     World!. Fittingly, the Hello World program has long been the new programmer's ...

 5.  Hello, World! - Learn Python - Free Interactive Python Tutorial [www.learnpython.org]
     Hello, World! Python is a very simple language, and has a very straightforward
     syntax. It encourages programmers to program without boilerplate (prepared) ...

 6.  Hello World: How to Create Your First Java Program - Guru99 [www.guru99.com]
     29 Apr 2019 ... This tutorial explains with example steps to compile and run hello world
     program. You need the following 2 software to create your first Java ...

 7.  Hello, World! - Learn C - Free Interactive C Tutorial [www.learn-c.org]
     Hello, World! Introduction. The C programming language is a general purpose
     programming language, which relates closely to the way machines work.

 8.  The History of 'Hello, World' - HackerRank Blog [blog.hackerrank.com]
     21 Apr 2015 ... Who knew that the basic 'Hello, World' program is such a pivotal
     part of the history of programming?

googler (? for help
```

Output at commit c66f129249742e65e49f3a7a7211ab13a90f207f:

```
~/G/googler$ g hello world

 1.  "Hello, World!" program - Wikipedia [en.wikipedia.org]
     A "Hello, World!" program generally is a computer program that outputs or displays the message
     "Hello, World!". Such a program is very simple in most ...

 2.  hello world - YouTube [www.youtube.com]
     30 Mar 2018 - 2 min - Uploaded by Louie Zonga test of a virtual singer software - http://www.myriad-
     online.com/en/products/ virtualsinger.htm ...

 3.  Hello, World! - Learn Java - Free Interactive Java Tutorial [www.learnjavaonline.org]
     Hello, World! Java is an object oriented language (OOP). Java objects are part of so-called "Java
     classes". Let's go over the Hello world program, which simply ...

 4.  What is Hello World? - Definition from WhatIs.com [whatis.techtarget.com]
     Hello World is a simple program that, when run, displays the message: Hello World!. Fittingly, the
     Hello World program has long been the new programmer's ...

 5.  Hello, World! - Learn Python - Free Interactive Python Tutorial [www.learnpython.org]
     Hello, World! Python is a very simple language, and has a very straightforward syntax. It encourages
     programmers to program without boilerplate (prepared) ...

 6.  Hello World: How to Create Your First Java Program - Guru99 [www.guru99.com]
     29 Apr 2019 ... This tutorial explains with example steps to compile and run hello world program.
     You need the following 2 software to create your first Java ...

 7.  Hello, World! - Learn C - Free Interactive C Tutorial [www.learn-c.org]
     Hello, World! Introduction. The C programming language is a general purpose programming language,
     which relates closely to the way machines work.

 8.  The History of 'Hello, World' - HackerRank Blog [blog.hackerrank.com]
     21 Apr 2015 ... Who knew that the basic 'Hello, World' program is such a pivotal part of the history
     of programming?

googler (? for help)
```

**Comment by jarun** [comment]
See search result 3 for example.

**Comment by zmwangx** [comment]
Yeah, our wrapping algorithm has no idea of zero width control characters. Will fix.

**Comment by jarun** [comment]
No hurry! ;)

**Comment by jarun** [comment]
@zmwangx did you get time to check this out?

**Comment by zmwangx** [comment]
Sorry, got a project going that tied up all my free time for the past few weeks, and this issue is more intricate than a quick half-hour fix. The project is about to conclude, so I’ll probably write a fix tomorrow.

When I gave this issue some passing thought, there are basically three ways forward:
1. Rewrite (expand) the PSL algorithm, adding support for zero-width and double-width (getting rid of CJK hack at the same time). The algorithm’s complicated as is, so expect some dense code on this path.
2. Use PSL textwrap (along with our CJK hack), but analyze the result to generate a one-to-one, live offset to row:col mapping. Use the mapping to insert characters by offset. This won’t be beautiful, computational complexity will be horrendous in theory but totally acceptable for our hundred-character long strings, and code will probably be mundane and understandable, without too many gotchas.
3. Just forget about hard wrapping, and allow terminals to do what they do — soft wrapping.

My plan is to take route 2, with route 1 as backup. Route 3 is of course welcome if you say the word.

**Comment by jarun** [comment]
Route 3 if it saves your time!

**Comment by zmwangx** [comment]
It's kind of an interesting problem so doesn't hurt to invest some time into it first ;)

**Comment by jarun** [comment]
OK then! I just wanted to ensure you don't spend too much of time on mundane stuff.

**Comment by jarun** [comment]
@zmwangx there's another thing. We have a mechanism to get the clean text from a news article here: https://github.com/jarun/googler/wiki/Directly-print-content-of-results-to-terminal

Would it be possible to read it as well using pico2wave? (see https://github.com/jarun/nnn/blob/master/plugins/readit)

That would be awesome!

**Comment by jarun** [comment]
I tried this using subprocess but I think the encoding to utf-8 has to be changed. For me the output wav is just reading the characters one by one.

**Comment by zmwangx** [comment]
Sorry, unplanned things came up over the weekend so this has to wait till tomorrow, again...

> Would it be possible to read it as well using pico2wave?
>
> I tried this using subprocess but I think the encoding to utf-8 has to be changed to pass the text to pico2wave. For me the output wav is just reading the characters one by one.

I don't have a Linux install connected to a sound device right now so I can't test this (okay, I'm too lazy to reboot into my bare metal Linux install...). What do you mean by "the encoding to utf-8 has to be changed"? You mean it only accepts ASCII, so U+0080 and above need to be stripped? As long as this pico2wave accepts textual input, there's no reason googler, which prints text, can't work with it.

**Comment by zmwangx** [comment]
(Apparently since it outputs a wav file I don't need a sound device on Linux. Will give it a spin.)

**Comment by jarun** [comment]
> As long as this pico2wave accepts textual input, there's no reason googler

I thought so. But somehow couldn't get it to work.

The generic syntax is:

    pico2wave -w "$tmpf".wav -l en-GB "some string"
It doesn't take a file as input but that's OK for us.

**Comment by zmwangx** [comment]
Just tried

```py
#!/usr/bin/env python3

import argparse
import os
import subprocess
import tempfile

import newspaper


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('urls', metavar='URL', nargs='+')
    args = parser.parse_args()

    for url in args.urls:
        article = newspaper.Article(url)
        article.download()
        article.parse()
        fd, path = tempfile.mkstemp(suffix='.wav')
        os.close(fd)
        subprocess.check_call(['pico2wave', '-w', path, '-l', 'en-GB', article.text])
        print(path)


if __name__ == '__main__':
    main()
```

Works for me without a problem.

**Comment by zmwangx** [comment]
Here's a base64 encoded sample of what I got from https://techcrunch.com/2019/06/23/week-in-review-youtubes-awful-comments-and-googles-1b-tech-free-investment/

[tmpedrzr7pe.wav.b64.txt](https://github.com/jarun/googler/files/3318063/tmpedrzr7pe.wav.b64.txt)

**Comment by jarun** [comment]
I was trying popen followed by communicate. Looks like `check_call doesn't need string conversion. Awesome!

Let me try it and I'll add it to the wiki right away. Who wouldn't want to listen to morning news without ads???

**Comment by zmwangx** [comment]
The tts engine leaves much to be desired though...

(Note that my quick and dirty text on command line approach is limited by `ARG_MAX` and company. If pico2wave accepts text on stdin, it should work, too.)

**Comment by jarun** [comment]
You can try `en-US`. And then there's https://archive.fo/OgeSS (but this is free service and can get blocked any day).

**Comment by jarun** [comment]
It doesn't accept stdin.

**Comment by zmwangx** [comment]
Okay, then one is limited by `ARG_MAX` so many long features probably won't work.

**Comment by jarun** [comment]
I think that's fine. I am not sure if it's possible to simulate something like the following with argprocess:

    pico2wave -w "$tmpf".wav -l en-GB "$(cat "$1" | tr '\n' ' ')"

This is what I do in the script to read any text file.

**Comment by jarun** [comment]
@zmwangx any update on this?

**Comment by jarun** [comment]
@zmwangx any update here?

**Comment by jarun** [comment]
As of now, the solution for this is to use ansiwrap or add an option to disable the color coding. However, it doesn't look pressing at the moment.
