### ISSUE TITLE
Choco install not working

### ISSUE THREAD

**Issue by geverghe** [jarun/googler#288]
#### Bug report
I am trying to install googler on the command line using choco.
1. Ran `choco install googler`
2. First time it installed python 3.7 package and installed googler successfully
3. I see that the path variables have also been updated.
4. However, when I run `googler` on the terminal, it says cannot understand the term googler.

**Comment by jarun** [comment]
@zmwangx a dark chocolate for you ;)

**Comment by zmwangx** [comment]
Two things:

1. Make sure `.PY` is in `PATHEXT` (Python 3.7 installer should have done that for you);
2. Make sure `$ChocolateyInstall\lib\googler\tools\googler` is in `PATH` (the googler installer script should have done that for you). Restart whatever terminal you were using. You may need to close all open "terminals" (again, whichever one) first for the environmental variable change to take effect.
