### ISSUE TITLE
googler -n sometimes show a wrong number of results

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#29]
I have noticed that `googler -n` sometimes suffer from a wrong number of results:

* Example 1. More:

    ```
> echo | googler -d -n 1 Homebrew
[DEBUG] Base URL [/search?ie=UTF-8&oe=UTF-8&start=0&num=1&]
[DEBUG] Search URL [www.google.com : /search?ie=UTF-8&oe=UTF-8&start=0&num=1&q=Homebrew]
[DEBUG] Response body written to '/Volumes/ramdisk/googler-response-MAhHbi'.
 1  Homebrew — The missing package manager for OS X
http://brew.sh/
Package Manager. Allows to install, remove and updated applications and packages.

 2  Local business results for Homebrew
https://maps.google.com/maps?oe=UTF-8&num=1&um=1&ie=UTF-8&fb=1&gl=us&sll=37.829533,-122.2105483&sspn=0.4166045,0.7033855&q=Homebrew


Enter 'n', 'p', 'g keywords' or result number to continue:
```

Response: https://gist.github.com/3df4ec1d1b3b46e5b08c.

* Example 2. Fewer:

    ```
> echo | googler -d -n 3 hello
[DEBUG] Base URL [/search?ie=UTF-8&oe=UTF-8&start=0&num=3&]
[DEBUG] Search URL [www.google.com : /search?ie=UTF-8&oe=UTF-8&start=0&num=3&q=hello]
[DEBUG] Response body written to '/Volumes/ramdisk/googler-response-_ZLbpd'.
 1  ADELE - HELLO - Directlyrics
http://www.directlyrics.com/adele-hello-lyrics.html
View the Adele Hello lyrics and music video. Adeles Hello is the first single from her album 25. Hello was released
on October 23rd, 2015 and quickly...

1 ad skipped.
Enter 'n', 'p', 'g keywords' or result number to continue:
```

Response: https://gist.github.com/5912c4cbfd012681021a.

Platform: OS X 10.11.3, tested with Python 2.7.11 or 3.5.1, Zsh 5.2 in iTerm 2.

Haven't investigated yet.

**Comment by jarun** [comment]
Google shows ads, local results etc. And sometimes the first result page actually shows lesser number of results than 10 (by default). This can't be fixed without adding more parsing (or filtering), meaning more time to process the page. Otherwise there's a API for clean results but it has its own share of burdens. I think I'll leave a note in the troubleshooting section.

**Comment by zmwangx** [comment]
Yeah that makes sense, and it's not really a big issue.

> Happens even without n (which is 10).

That's more forgivable because in that case the user isn't saying how many results they want, just "show me some results". However, you see, when `-n` is specified and disobeyed in your face, it's harder to plead innocence... And occasionally you ask for one or two results and nothing is returned (try that with `hello`), it feels kind of broken.

I think this problem can be solved relatively easily by keeping an eye on the counter (there's already an index anyway) and fetching the next page if necessary. Do you feel strongly about that? If not, I might look into the feasibility (without changing overall structure too much) when I've got time.

**Comment by jarun** [comment]
Please add the case with the reason to Troubleshooting section in readme. No code changes, no messages with lengthy explanations for this in the code please.

If we go for anything, first we would need to have a track that this is the first fetch, which would become tricky with continuous searches in place. I don't see too many use cases where you would add `-n 1` to an alias. There's one case for `define`, where I use `-n 3`.

**Comment by zmwangx** [comment]
> No code changes, no messages with lengthy explanations for this in the code please.

No problem, then I won't even look into this. I asked precisely not to waste time on a feature that won't be included.

> There's one case for `define`, where I use `-n 3`.

Just in case you don't know, there's a CLI for Google Translate that serves as an awesome command line dictionary: https://github.com/soimort/translate-shell.

```
> trans -d google
google
/ˈgo͞ogəl/

verb
    search for information about (someone or something) on the Internet using the search engine Google.
        - "I recently googled my 7th grade teacher and found his current e-mail address"

Examples
    - James is one of the bosses at a certain media institution; you can google him.

    - I googled the author to see what became of him, and to my delight the entire book is up on the web.

    - After writing this I googled him, and he turns out to have been the director of the Edinburgh Film Festival, which I'm waiting to hear from.

    - His name is DJ Reeve, but I googled him and all I get are scientists and some Swiss kid, so, that's not him.

    - However, after googling the guy, he seems to be an expert on handwriting not on typewritten documents.

    - For some additional fun, try googling other people you know - friends, relatives, or maybe that cute guy/girl who sits across from you in class.

    - I googled her recently, but the search turned up nothing.

    - Last night I googled me again and in no time at all was presented with 2270 results, I smiled quietly to myself.

    - So someone googled him and came up with his casting details.

    - So this morning I googled him and found Old Friends.

    - Three or so years ago I googled him, and there it was on the internet.

    - Just in case the link doesn't work, try googling Michael Briere or Holly Jones to get the story.

    - You've probably also heard me talk about how much I wanted to find him - how long I've been searching, googling him all the time and never finding anything.

    - Chris at Crooked Timber has googled the author of this piece and comes up with some revealing links.

    - But I was intrigued by Dan's comment, so I googled him, as you do, and had a look at some of the things he's written.

    - You know, if you're just googling your favorite celebrity, blogs tend to rank very high on that search engine.

    - ‘The person I finally chose, Ali, I googled him a lot: I found that he once had a speeding ticket in Connecticut,’ Isabelle smiled.

    - And this is the kind of thing I don't need coming up under my full name when I'm googled.

    - An old college boyfriend sent me an email yesterday after googling and finding my weblog.

    - You were the crush I've never forgotten and since the Internet has arrived, I've even googled your name Tim, but where would I begin.

See also
    Google
```

**Comment by jarun** [comment]
google-translate is cool. Loving it! :)

**Comment by jarun** [comment]
Updated the troubleshooting section in readme.
