### ISSUE TITLE
alternative tmp dir 

### ISSUE THREAD

**Issue by dubiouscript** [jarun/googler#291]
## Feature request

command line option OR env var  for alternative tmp location  

 i see that 
>Response body written to '/tmp/googler-response-*.html'.

so i would like to set 
>googler --tmp  /some-other-folder

or 
>googler_tmp=/some-other-folder googler 

has this been ever considered ?

**Comment by jarun** [comment]
Maybe you can override with `$TMPDIR`. Please raise a PR.

**Comment by jarun** [comment]
Closing the issue as there is no response and we use the tmp dir only for debug logs.

**Comment by zmwangx** [comment]
For the record we already use `tempfile.mkstemp` which does respect `TMPDIR`.
