### ISSUE TITLE
Add option to exit after selecting a url

### ISSUE THREAD

**Issue by NightMachinary** [jarun/googler#293]
I want an option that makes googler exit after a url has been sent to `url-handler`.

**Comment by jarun** [comment]
Try:

    googler -j --url-handler someutility hello

**Comment by NightMachinary** [comment]
@jarun This is not what I want; I want the selection to be interactive.

**Comment by jarun** [comment]
Please modify the script yourself. I don't think we can spend time on this at this stage of the project.

**Comment by NightMachinary** [comment]
Does that mean a PR to that effect is welcome?

**Comment by jarun** [comment]
Is this a very frequent use case? What is your workflow?

**Comment by NightMachinary** [comment]
I have two uses in mind; First is, I have a shell function to read URLs in
the terminal, and I don’t want to create a wrapper around it for
url-handler (because it takes some seconds to load the superfluous shell of
the wrapper script.).
The second use is for selecting urls for my some of my functions; E.g., one
for easily streaming YouTube in mpv, one for playing music from spotify.
You do realise that this option allows interactively searching ANY site for
any script, don’t you? :D

**Comment by jarun** [comment]
> I have a shell function to read URLs in the terminal

You can use it directly without any wrapper. url-handler calls the script with the url.

> for some of my functions

How does the change fit in here?

**Comment by NightMachinary** [comment]
url-handler calls a “script.” I don’t want that, as it necessates starting
a new shell for the script.
I want to sth like this:
googler —url-handler echo —exit-after “$query” | web-read

This same thing can be used for downloading from youtube:
y “$(googler —url-handler echo —exit-after “$query” -w youtube.com)”

(y is a function that downloads Youtube videos.)

This —exit-after allows googler to be integrated seamlessly into other
functions and scripts, without slowing everything down and requiring
creation of wrapper scripts.

**Comment by jarun** [comment]
Got it! Please raise the PR.
