### ISSUE TITLE
When installing on mac, requires to uninstall python first

### ISSUE THREAD

**Issue by ivanovaos** [jarun/googler#294]
When installing on mac, requires to uninstall python first, which I believe shouldn't be done.

```
==> Installing dependencies for googler: python
Error: python is already installed from !
Please `brew uninstall python` first."
```
Thanks for the great tool!

**Comment by jarun** [comment]
This looks more like a local issue to me because several users are using `googler` via Homebrew. Can you please check which version of Python you have installed already?

**Comment by ivanovaos** [comment]
@jarun I have python2(2.7) and python3(3.7) installed, and anaconda, on mac os x mojave. I have had googler installed previously and decided to upgrade it, that is where homebrew started to complain about python. Then I removed googler through homebrew and tried to install again, with the same error message

python2: /usr/local/bin/python2
python3: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3; /usr/local/bin/python3

**Comment by jarun** [comment]
@zmwangx can you take a look?

**Comment by jarun** [comment]
@ivanovaos are you seeing this issue with any other python3 utility?

**Comment by ivanovaos** [comment]
@jarun no, I haven't seen it before

**Comment by jarun** [comment]
@ivanovaos this may not be directly related to `googler`. Can you check if you have multiple versions of python3 installed?

I see that other people have also faced this problem. Can you please update the following thread with the details from your system?

https://github.com/Homebrew/brew/issues/6171

**Comment by ivanovaos** [comment]
@jarun yes, you are correct - I have two installations of python3, so I guess it is indeed connected to homebrew rather than googler!

**Comment by freakmoder** [comment]
I get this issue as well with several formulas (e.g. graphviz) which require python. This is annoying as there is no reason to uninstall python when it's already installed.

`Error: python is already installed from !`

please fix this!

**Comment by jarun** [comment]
Closing this as it is not a `googler` issue. Please pursue this with the Homebrew team.
