### ISSUE TITLE
Ubuntu Launchpad out of date

### ISSUE THREAD

**Issue by galenasphaug** [jarun/googler#295]
https://launchpad.net/googler shows version 3.7.1, current version is 3.9

**Comment by jarun** [comment]
Ubuntu is a bit behind on the releases. Adding @szlin.

**Comment by szlin** [comment]
@jarun Thanks for tagging me.
@galenasphaug It shows 3.9 at my end.

> googler source package in Eoan
> Version 3.9-1 uploaded on 2019-06-03
