### ISSUE TITLE
subdomains

### ISSUE THREAD

**Issue by Sy3Omda** [jarun/googler#297]
Hi,
First of all thx for this great tool,
my Q is it possible to recon all subdomains for certain site using this tool because i tried but it only response with few results rather than all subdomains listed when using google search.

Thx

**Comment by jarun** [comment]
Please share the comma d you ran and wht you expect.

**Comment by Sy3Omda** [comment]
sorry i can not understand you
if you asking about the result i want !
it would be something like
www.site.com
stg.site.com
test.test.site.com
dev.site.com
anything.anything.site.com

**Comment by jarun** [comment]
Sorry aboit the typo. Please share tje complete commnd you ran.

**Comment by Sy3Omda** [comment]
okay
`googler -n100 yahoo.com --json | grep "\"url\""|tr -s ' ' |cut -d ' ' -f3|tr -d "\"" | awk -F/ '{print $3}' | grep -i "yahoo.com"`

**Comment by jarun** [comment]
Sorry, I don't understand your use case. If you search `yahoo.com` in google web search it doesn't return subdomains.

**Comment by jarun** [comment]
In general, there is no subdomain-specific handling in `googler`.

**Comment by zmwangx** [comment]
Going through some old issues here to get up to speed after a hiatus, so excuse me for replying on a long-closed issue.

What you were trying to do is "subdomain enumeration." Search for this topic and you'll find many guides; googler *could* play a small part in it but there are many other arguably more useful techniques. I recall enjoying this particular blog post back when it came out: https://blog.appsecco.com/a-penetration-testers-guide-to-sub-domain-enumeration-7d842d5570f6 I also just found [appsecco/the-art-of-subdomain-enumeration](https://github.com/appsecco/the-art-of-subdomain-enumeration) but I'm not sure how good it is.

**Comment by Sy3Omda** [comment]
@zmwangx THANK you so much, that`s helpful.
i was trying to make use of this such amazing tool in addition to my arsenal tools.
