### ISSUE TITLE
Apt-get install older version of googler from package sources (Temp. Solution)

### ISSUE THREAD

**Issue by Avileox** [jarun/googler#301]
### Advanced Package Tool (APT) Download older version of googler from package source leads to (Not found) error.
While using `sudo apt-get install googler`
Older version of googler downloads from package sources 
![Screenshot from 2019-11-15 08-52-49](https://user-images.githubusercontent.com/40210313/68928480-2bb4b100-0758-11ea-862c-eead20733cae.png)
### Package: googler (3.7.1-1) [universe] foung on ubuntu package search
![Screenshot from 2019-11-15 08-54-57](https://user-images.githubusercontent.com/40210313/68928597-6e768900-0758-11ea-8e29-182389c64c3f.png)

### Download googler from apt-get
`apt get install googler`
### Check version by using
`apt get policy`
Older versoin Stdout `googler:
  Installed: 3.7.1-1
  Candidate: 3.7.1-1
`
### Check version on your machine
`googler -v`
Older version Stdout `
3.7`
If it shows an older version than v3,9(current version)
### Update googler by using
`googler -u`
Update version Stdout`3.9`

**Comment by jarun** [comment]
Googler project team does not maintain downstream packages.

**Comment by jarun** [comment]
Adding @szlin.

**Comment by zmwangx** [comment]
> Googler project team needs to update the current version of the package on all the package sources.

That’s unrealistic.

(1) “The project team” is two people, on and off;
(2) Only Debian Developer (DDs) can update Debian packages;
(3) Debian is policy driven and (in)famous for outdated packages, I don’t think even DDs can just do as they wish. I’m unfamiliar with how Ubuntu update packages, only that they base their distro on Debian testing. Someone familiar with Ubuntu development is welcome to enlighten me on this topic.

If you think the situation is bad with disco, try to look at LTS (bionic at the moment) especially when they approach the end of the two years cycle. (I use Ubuntu LTS exclusively and feel the pain almost all the time.)

I've commented multiple times elsewhere (and maybe here too) that there's a fundamental disconnect between what Debian considers "stable" and what is actually stable or even usable for a certain class of software that requires regular tending. Debian considers old, battle-tested software to be stable. Except in the increasingly interconnected world, more and more software interacts with online services and old software may simply be broken. I don't know how to solve this problem.

---

Re `googler -u`: using this with a managed installation is not a good idea. It causes you to have a version that is different from what the package manger thinks you have, and future package manager "upgrades" may actually downgrade your installation.

By the way, we actually discussed this Ubuntu/Debian-outdatedness problem a while back and I proposed just offering a installation script and be done with it.

Until then, I recommend [downloading a single file](https://github.com/jarun/googler#downloading-a-single-file).

**Comment by zmwangx** [comment]
By the way, here's a working copy of the installation script I mentioned above (wrote a long time ago...): https://gist.github.com/zmwangx/7fbaafbb3e9f2833324c1ac6291b9ef1 Not completely polished but open to suggestions.

**Comment by Avileox** [comment]
@zmwangx Thank you for elaborating and suggesting a more effective way, I just read more about Googler package on the Debian package tracker and found that DD put googler latest running version as unstable and v3.1 as stable, 
![Screenshot (2)](https://user-images.githubusercontent.com/40210313/68940001-07fd6500-0770-11ea-81e2-bdb6c135edad.png)

while v3.1 has some error while using on latest Debian based distro.
It will be good if the googler dev's put a note on README.md about the issue with apt-get installation and suggest other working method till the version get the update by Debian.

**Comment by szlin** [comment]
Hi,

If you want to use the newest version of googler in Debian, please use testing or unstable archive [1]. Ubuntu fetched the Debian packages automatically, and I don't manage the packages in Ubuntu. 

[1] https://wiki.debian.org/DebianStability

**Comment by szlin** [comment]
Hi,

<snip>

> I've commented multiple times elsewhere (and maybe here too) that there's a fundamental disconnect between what Debian considers "stable" and what is actually stable or even usable for a certain class of software that requires regular tending. Debian considers old, battle-tested software to be stable. Except in the increasingly interconnected world, more and more software interacts with online services and old software may simply be broken. I don't know how to solve this problem.
> 

Debian provides backports archive [1] for stable release [2], I think it might meet your requirement. However, it requires extra maintenance effort as well.

[1] https://backports.debian.org/
[2] https://wiki.debian.org/DontBreakDebian#Some_safer_ways_to_install_software_not_available_in_Debian_Stable

SZ

**Comment by zmwangx** [comment]
I wrote a wiki article about "No results", which includes a note about outdatedness: https://git.io/googler-no-results. googler now also prints a message pointing to the wiki article when "No results" happens (f0914da4e507e71b6179975a9fed98c51ca4871a). Obviously it won't be shown in old versions, but hopefully it will improve the situation going forward.
