### ISSUE TITLE
V3.9 (snap app) give "No results" for everything

### ISSUE THREAD

**Issue by timeislove** [jarun/googler#308]
as the subject described, pls note the following log:

Version 3.9
Copyright © 2008 Henri Hakkinen
Copyright © 2015-2019 Arun Prakash Jana <engineerarun@gmail.com>
Zhiming Wang <zmwangx@gmail.com>
License: GPLv3
Webpage: https://github.com/jarun/googler
timeislove@X1:~$ googler --count 3 googler
No results.
googler (? for help) 

timeislove@X1:~$ googler obama
No results.
googler (? for help) q
timeislove@X1:~$ googler --help

**Comment by jarun** [comment]
v4.0 fixes this. Please request snap maintainer to update.

**Comment by timeislove** [comment]
Hello, just curious. The "no results" bug happened before for previous version and there was no problem with ddgr which is from the same developer.As now the no results happens again and I checked ddgr is still working fine.Is there any reason why Googlers give the same bug while ddgr does not?RegardsOn 28 Nov 2019 19:09, Mischievous Meerkat <notifications@github.com> wrote:v4.0 fixes this. Please request snap maintainer to update.

**Comment by jarun** [comment]
@timeislove that's because Google and DuckDuckGo are two different services. Google tends to experiment with their layouts frequently.
