### ISSUE TITLE
add googler to scoop.sh

### ISSUE THREAD

**Issue by danalec** [jarun/googler#309]
Feature request: Please consider to maintain a **scoop**.sh installation recipe for `googler` in scoop.sh's "extra bucket"

project website: https://github.com/lukesampson/scoop
extra-bucket github: https://github.com/lukesampson/scoop-extras/tree/master/bucket

**Comment by jarun** [comment]
Please add it yourself and notify us. We don't maintain downstream ourselves due to bandwidth issues.
