### ISSUE TITLE
ImportError: cannot import name 'HTTPSConnection'

### ISSUE THREAD

**Issue by ishandutta2007** [jarun/googler#312]
ishandutta2007@MacBook-Pro:~/Documents/Projects/linkedin$ googler -u

Traceback (most recent call last):
  File "/usr/local/bin/googler", line 29, in <module>
    from http.client import HTTPSConnection
ImportError: cannot import name 'HTTPSConnection'

**Comment by jarun** [comment]
This is your local python env issue. HTTPSConnection is a python module which may not be installed correctly.

**Comment by ishandutta2007** [comment]
@jarun whats the correct way then?
I am on version 3.5 and have installed everything in requirements

**Comment by ishandutta2007** [comment]
Please suggest where from the python needs to be installed , my python is from pyenv I tried both 3.5 and 3.6, this is what I see,
```

Python 3.5.4 (default, Jun 23 2019, 14:38:42) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import http
>>> http.client.HTTPConnection('www.python.org')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'http' has no attribute 'client'

```

**Comment by jarun** [comment]
If you are on Ubuntu, just install python3 using `apt get`.

**Comment by jarun** [comment]
OK. You are on Apple.

**Comment by ishandutta2007** [comment]
it has only these functions _encode, parse_headers, urlsplit
but not HTTPSConnection

**Comment by ishandutta2007** [comment]
Yes I am on apple

**Comment by zmwangx** [comment]
Never seen this problem before. My guess is your didn’t compile with OpenSSL correctly, so `_ssl` is borked. What happens when you `import _ssl`?

**Comment by ishandutta2007** [comment]
```
>>> import _ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/ishandutta2007/.pyenv/versions/3.5.4/lib/python3.5/lib-dynload/_ssl.cpython-35m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/ishandutta2007/.pyenv/versions/3.5.4/lib/python3.5/lib-dynload/_ssl.cpython-35m-darwin.so
  Reason: image not found
```

**Comment by zmwangx** [comment]
Yup, borked as I say.

**Comment by ishandutta2007** [comment]
@zmwangx  solutions ? should i do `brew install ssl` ?

**Comment by ishandutta2007** [comment]
What is "compiling with OpenSSL"? I don't remember installing any of this libraries explicitly, be it 'http' or 'http.client' or 'ssl or 'open-ssl' manually, using all what came with stock python

**Comment by zmwangx** [comment]
Chill, I was typing ;)

From the linkage here

```
Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
```

it means when you compiled this Python 3.5.4 with pyenv you had OpenSSL 1.0.x installed with Homebrew, but later the `openssl` formula, at least `openssl@1.0`, was uninstalled. You probably either have no `openssl` now or only have `openssl@1.1`. Either way, `brew install openssl` to make sure, then recompile Python with pyenv.

**Comment by ishandutta2007** [comment]
if 
>>> import http.client
>>> http.client.HTTPConnection('www.python.org')

 is working then it must be there, just that its not working `from <module> import <function>` way.

**Comment by zmwangx** [comment]
Dude, that's an `HTTPConnection`, not `HTTPSConnection`. Trust me, as a former Homebrew maintainer I can spot a Homebrew problem from miles away, so just recompile.

**Comment by ishandutta2007** [comment]
Ah sorry mybad

**Comment by ishandutta2007** [comment]
yes it's 1.1
`brew install openssl`
> Warning: openssl@1.1 1.1.1d is already installed and up-to-date
> To reinstall 1.1.1d, run `brew reinstall openssl@1.1`

Since I can't find a easy way to recompile using pyenv without uninstalling everything I am trying out a new version of python(that's not on my system), will update only the problem gets solved.

**Comment by ishandutta2007** [comment]
Yup it's working with newly install python 3.7.1
Thanks @zmwangx for explaining it properly.
Moral of the story: "Never update openssl even if prompted, in case you have to you better know how to recompile python immediately"

**Comment by zmwangx** [comment]
Updating OpenSSL is usually fine, the jump from `libssl.1.0.0.dylib` to `libssl.1.1.dylib` is extremely rare. The dylib version number 1.0.0 has been the same for years. However, when it does change and you remove the old one, everything that depends on it *will* break (Homebrew can do its best making sure its packages are all recompiled, but it can't do anything about your pyenv Python installs).

This is not unique to OpenSSL either, just the nature of dynamic linking. If one day `libsqlite3.0.dylib` becomes `libsqlite4.0.dylib`, your old Python installs will break too.

**Comment by ishandutta2007** [comment]
What if googler had an option to install via pip ?

**Comment by zmwangx** [comment]
That's been discussed before many times. We explicitly disallowed any dependencies, so restructuring the repo just for installing a single script with pip is pointless. It also won't avoid a broken Python problem, so not sure how that's related.

**Comment by ishandutta2007** [comment]
I reason I asked is I have been installing lots of python libraries requiring some sort of web requesting or the other, I suspect they might be requiring `openssl` too, installed all of them via `pip`. For none of them I faced this issue, maybe for those cases `pyenv` handles recompilation.

**Comment by ishandutta2007** [comment]
I guess you are right these libraries might not be using `openssl` or else `import _ssl` would not break

**Comment by zmwangx** [comment]
I think some HTTP libraries may (optionally) use `pyopenssl` instead of PSL `ssl`. (Pretty sure `requests[security]` does this.) Maybe `pyopenssl` is capable of picking up the correct OpenSSL at runtime, or your `pyopenssl` was installed/upgraded post OpenSSL upgrade so it was linked against the correct dylib.

I didn't bother to check any actual code so the above is pure speculation.

Anyway, we have a no-third-party-dep policy so we can't do anything like that. A Python with borked `_ssl` is crippled in my book for all intents and purposes.

**Comment by ishandutta2007** [comment]
well since the library is at `/usr/local/opt/openssl/lib` it solved for the newly installed python 3.7.1 but broke for my older python versions :( . Recompiling those seems to be the only option but can't find any way for pyenv. If you happen to know any way to recompile in pyenv do let me know.

**Comment by zmwangx** [comment]
> recompile in pyenv

```command
$ pyenv uninstall x.y.z
$ pyenv install x.y.z
```

If you want to preserve the exact dependencies,

```command
$ pyenv shell x.y.z
$ pip freeze > /tmp/x.y.z-requirements.txt
```

before uninstallation and

```command
$ pyenv shell x.y.z
$ pip install -r /tmp/x.y.z-requirements.txt
```

editable installs can't be preserved this way; the replication should be otherwise faithful.

You can even install the same version under a different name without uninstalling the existing; I used to do this with pyenv in order to have a separate framework build (required for PyQt5). I don't remember if that's a manual process or a hidden feature though. Anyway, duplicating `plugins/python-build/share/python-build/x.y.z` to `plugins/python-build/share/python-build/<new_name>` is one manual way to do it.

**Comment by ishandutta2007** [comment]
Well the first idea is the obvious solution which's on top of my head too, but more than that I want to save my data as well as time as those modules accumulated over time might be worth in GBs.  I have created ticket here, lets see if anyone has any innovative solutions https://github.com/pyenv/pyenv/issues/1488

About about your second Idea, would copying modules manually from one installed copy to other suffice, ok let me give it a try?

**Comment by ishandutta2007** [comment]
@zmwangx an unrelated question, do you by any chance know any good open-souce project on lines googler which can help me work with gmail end to end from terminal. The ones I find searching "gmail from terminal" on github are too basic.

**Comment by zmwangx** [comment]
In fact you can just copy the entire `lib/pythonx.y/site-packages` directory from the old installation to the new one, in theory it should work as long as it's the same Python version. Not completely sure if there would be subtle problems.

> gmail end to end from terminal

Any IMAP client, e.g. mutt.

**Comment by ishandutta2007** [comment]
> Any IMAP client, e.g. mutt.

The thing is google detects your browsers to prevent mail hacking which is why whenever we try login to a gmail account from a new PC or Different browser on same PC it send notification to android where the mail was created or tries to verify via OTP etc, lots of complexities are there which clients like Pine or mutt may not handle which is  why I have been looking for some open source projects which preferably uses gmail official api.
