### ISSUE TITLE
Google news searches produce "no result"

### ISSUE THREAD

**Issue by kenficara** [jarun/googler#316]
With the latest version from master, I run `./googler -N --debug  test` and get this output:

```
[DEBUG] googler version 4.0
[DEBUG] Python version 3.7.6
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=test&sei=mBo_WDMPEeqiEqy8Ms9rdw&tbm=nws
[DEBUG] Cookie: 1P_JAR=2020-01-09-18
[DEBUG] Response body written to '/var/folders/2h/gy2v20851pb17jzxrd_wpmwh_1zrbc/T/googler-response-65p2szdl.html'.
No results.
If you believe this is a bug, please review https://git.io/googler-no-results before submitting a bug report.
```
The debug output is [in this gist](https://gist.github.com/kenficara/d3a3e649c648d5869ca9a4d182c647df).

OS is MacOS 10.14.6 (Darwin 18.7.0), Python version is as shown above, and locale i set as follows:

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

**Comment by zmwangx** [comment]
On my tablet right now so can’t look into the details, but judging from how it’s rendered (see https://gitcdn.xyz/cdn/kenficara/d3a3e649c648d5869ca9a4d182c647df/raw/fece93a7c54b7d90073189131b2ddb63fed17328/googler-response-65p2szdl.html) it’s an unfamiliar layout where every result is inside a box, mostly another layout A/B test. It probably won’t persist.

**Comment by jarun** [comment]
It worked for me right after the defect was raised and works for me now.

**Comment by samyules** [comment]
Can confirm this problem. Also using MacOS 10.14.6, and current version from Master. Output from running `./googler -N --debug test`:
`[DEBUG] googler version 3.8
[DEBUG] Python version 3.7.6
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=test&sei=qMFiwjaAEeqfsQxN6c5AaA&tbm=nws
[DEBUG] Cookie: 1P_JAR=2020-01-14-03
[DEBUG] Response body written to '/var/folders/y2/9h76tv611lg6ztpzn_y8z3t00000gp/T/googler-response-p6uvmcio'.
No results.`

**Comment by samyules** [comment]
I have the same problem. Also running MacOS 10.14.6. Output from `googler -N --debug test`:
```
[DEBUG] googler version 4.0
[DEBUG] Python version 3.7.6
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=test&sei=nhd50jaBEeq9+wxN6c5AaA&tbm=nws
[DEBUG] Cookie: 1P_JAR=2020-01-14-03
[DEBUG] Response body written to '/var/folders/y2/9h76tv611lg6ztpzn_y8z3t00000gp/T/googler-response-y12ezwg_.html'.
No results.
If you believe this is a bug, please review https://git.io/googler-no-results before submitting a bug report.
```

**Comment by zmwangx** [comment]
Now I’m seeing this new layout too. As always we wait 24 hours (let’s say from the first time a maintainer was able to reproduce, which is now).

**Comment by zmwangx** [comment]
Btw here's a patch for this new layout:

```diff
diff --git a/googler b/googler
index 8a51a8a..97885e6 100755
--- a/googler
+++ b/googler
@@ -2239,6 +2239,23 @@ class GoogleParser(object):
             self.results.append(Result(index, title, url, abstract,
                                        metadata=metadata, sitelinks=sitelinks, matches=matched_keywords))
 
+        if not self.results:
+            for card in tree.select_all('g-card'):
+                a = card.select('a[href]')
+                if not a:
+                    continue
+                url = self.unwrap_link(a.attr('href'))
+                text_nodes = []
+                for node in a.descendants():
+                    if isinstance(node, TextNode) and node.strip():
+                        text_nodes.append(node.text)
+                if len(text_nodes) != 4:
+                    continue
+                publisher, title, abstract, publishing_time = text_nodes
+                metadata = '%s, %s' % (publisher, publishing_time)
+                index += 1
+                self.results.append(Result(index, title, url, abstract, metadata=metadata))
+
         # Showing results for ...
         # Search instead for ...
         spell_orig = tree.select("span.spell_orig")
```

Due to these parser-sabotaging changes, the parser is unfortunately becoming increasingly less resistant to future changes.

**Comment by jarun** [comment]
I am not seeing this issue now.

**Comment by jarun** [comment]
Not seeing this anymore.
