### ISSUE TITLE
xsel or xclip installed but prompted "failed to locate suitable clipboard utility"

### ISSUE THREAD

**Issue by timeislove** [jarun/googler#318]
hello,

using v.4 (snap app).

tried both xsel and xclip but after i typed c index, it prompted me failure to locate the clipboard utility.

just curious, would this feature make use of any sys env?

**Comment by jarun** [comment]
Can't reproduce this. Probably you have to install xsel/xcip using snap too?

**Comment by jarun** [comment]
If that doesn't help, please check with snap maintainer(s). We do not maintain it.
