### ISSUE TITLE
How to search results between specific time periods 

### ISSUE THREAD

**Issue by sant527** [jarun/googler#320]
#### Feature requests
Can we have an option to specify search results pertaining to a specific time period like

2019-01-01-12am to 2019-01-01-2am

**Comment by jarun** [comment]
Please check if google provides any such params and we can consider.

**Comment by jarun** [comment]
Feature requests

How can i achieve the results of the below google search link using googler. It searches for news keyword under videos section between dates feb-12-2020 to feb-14-2020

https://www.google.com/search?q=news&biw=1332&bih=595&source=lnt&tbs=cdr%3A1%2Ccd_min%3A2%2F12%2F2020%2Ccd_max%3A2%2F14%2F2020&tbm=vid

**Comment by jarun** [comment]
For the start and end dates the params are:
```
cd_min%3A2%2F12%2F2020
cd_max%3A2%2F14%2F2020
```

for Nov 8 2019 to Nov 21 2019 it would be:

```
cd_min%3A11%2F8%2F2019
cd_max%3A11%2F21%2F2019
```

there's also "tbm=vid" which might be interesting.

@zmwangx do you think it would be useful to have these new custom search params in?

**Comment by jarun** [comment]
I have implemented the videos support.

**Comment by zmwangx** [comment]
> do you think it would be useful to have these new custom search params in?

Sure, sounds reasonable. These are encoded in the `tbs` parameter

```
tbs: cdr:1,cd_min:<m/d/yyyy>,cd_max:<m/d/yyyy>
```

Both `cd_min` and `cd_max` are optional.

**Comment by zmwangx** [comment]
I double checked and the date format (even as seen in the date selector fields) doesn't seem to be affected by locale or Google version (tld).

**Comment by jarun** [comment]
Cool! Can you raise the PR? My weekend is over. :'(

**Comment by sant527** [comment]
also one more option is we can select the source of the videos i.e youtube.com etc 

Eg:

https://www.google.com/search?q=news&tbs=cdr:1,cd_min:2/11/2020,cd_max:2/14/2020,srcf:H4sIAAAAAAAAAB3LQQqAMAwF0du4EXqnWD9abRNJE7CeXs3yDcw8xM0XpCxtKrwWstLQg1QPegClUBPGyMKmUiPYjs1Jv4XDuC9F_19fk5_1QCkLod11kAAAA&tbm=vid&source=lnt&sa=X&ved=0ahUKEwiC2KDWp-nnAhUr6nMBHVC6AjkQpwUIIQ&biw=1332&bih=595&dpr=1

But the results it shows are not time ordered. I want to have in the descending order.

**Comment by jarun** [comment]
@sant527 you can run website specific search in `googler` already.

**Comment by jarun** [comment]
I am not sure of the order though.

**Comment by zmwangx** [comment]
Date range implemented in #322.

Re video site: those `srcf` strings look almost as random as encrypted session cookies to me (yes, I know they only vary by a few bytes). I'm not sure we can reverse engineer them (any expert on exotic encodings here?), and even if we can I don't think I'll vote in favor of this feature.

**Comment by jarun** [comment]
I have added video search and so far it seems to work. Let's see.

**Comment by zmwangx** [comment]
I was responding to “also one more option is we can select the source of the videos i.e youtube.com etc”.

**Comment by jarun** [comment]
ahh, ok

**Comment by sant527** [comment]
Thank you for adding the data feature and also videos feature. Ofcourse the scrf feature is encrypted but looks like it works irrespective of session cookie. I opened it in different browsers after clearing the history it shows the youtube.com results only, I think they have an encrypted string for each website.

**Comment by jarun** [comment]
> Ofcourse the scrf feature is encrypted but looks like it works irrespective of session cookie. I opened it in different browsers after clearing the history it shows the youtube.com results only

What are you suggesting?

**Comment by sant527** [comment]
just add scrf  like --scrf 

I tried to modify the googler file at /usr/local/bin/googler on my system
```
addarg('--srcf',help='scrf')

if 'from' in opts or 'to' in opts or scrf in opts:
            cd_min = opts.get('from', '')
            cd_max = opts.get('to', '')
            srcf = opts.get('srcf', '')
            qd['tbs'] = 'cdr:1,cd_min:%s,cd_max:%s,srcf:%s' % (cd_min, cd_max,srcf)
```

then run the command

`$ googler -n 20 -V --from 1/5/2020 --to 1/6/2020 --srcf H4sIAAAAAAAAAB3LQQqAMAwF0du4EXqnWD9abRNJE7CeXs3yDcw8xM0XpCxtKrwWstLQg1QPegClUBPGyMKmUiPYjs1Jv4XDuC9F_19fk5_1QCkLod11kAAAA nature

`

And its working

**Comment by jarun** [comment]
We can't have options added to specify random tokens. Google keeps changing it's result format so they may change these tokens anytime. We are not here to waste our time on catering to these kind of requests and maintaining these kind of options which may break anytime.

And how are we going to document this for users? Run a google video search, copy the encrypted token and use it in the `--srcf` token. We don't even know what _srcf_ means but yes, we added it as an option. And yes, for every video site, save the specific token and when you search that site copy and paste it from your note in the terminal.

Feel free to fork, add the options you need and maintain those using your time.

**Comment by jarun** [comment]
Also, for me the query you suggested is working even without the token. If it doesn't work at some point I will boot the `-V` option without thinking twice and retain the range options for the regular search.
