### ISSUE TITLE
Recommended proxy?

### ISSUE THREAD

**Issue by taewookim** [jarun/googler#325]
Not a bug.. but i tried using various free open proxies, none (or very few) seem to get through.
Which proxy services gets the job done (i.e. gets through consistently and w/o issues)? Are residential IP proxies the only solution?

**Comment by zmwangx** [comment]
Yeah free open proxies are garbage. They’re mostly just misconfigured proxy servers found with crawlers like Shodan anyway. (Ask me how I know that. I once left privoxy open and started getting lots of traffic hours later — apparently it appeared on a “free open proxy” list and stayed there for a few days or longer even after I fixed my acl config.)

Residential IPs are not a necessary condition. Some server IPs are blocked (all my Newark, NJ and previously Atlanta, GA Linode IPs were blocked, IIRC), some are not (our CI previous ran on GCP through Travis and now on AWS (?) through CircleCI and both appear okay, and I personally had success with GCP IIRC).

There are tons of paid proxy pool services out there, some more expensive and less sketchy than others. I don’t have much experience with them, let alone tunneling googler through them, so you’ll just have to try for yourself.
