### ISSUE TITLE
-n counts less than 5 returns no results or different count

### ISSUE THREAD

**Issue by elig0n** [jarun/googler#327]
Tried on master.
at one case running googler with -n N where N is less than 5 would return no results.
on another case, other numbers usually higher than 5 would return less results than requested.

Example command and output:
$ ./googler -d --np -n2 "return of"
[DEBUG] googler version 4.0
[DEBUG] Python version 3.7.7
[DEBUG] Connecting to new host www.google.com
[DEBUG] setsockopt failed
[DEBUG] Fetching URL /search?ie=UTF-8&num=2&oe=UTF-8&q=return+of&sei=n8kpxHA4Eeq6HwD_+t4V4w
[DEBUG] Cookie: 1P_JAR=2020-03-27-14
[DEBUG] Response body written to '/tmp/googler-response-ifpex713.html'.
No results.
If you believe this is a bug, please review https://git.io/googler-no-results before submitting a bug report.

Response body file at:
https://paste.ubuntu.com/p/hkfJWCgnVc/

Running on WSL Debian testing.

**Comment by jarun** [comment]
Try the next page. Some of the links in the first page are ads and are filtered out.

**Comment by elig0n** [comment]
next pages sometimes show the designated number, sometimes less - also due to ads?
anyway I don't see a way to specify page in the command line as I'm interested in --noprompt or --json responses. But anyway wouldn't it be better to not count ads to begin with ?

**Comment by jarun** [comment]
> sometimes less - also due to ads?

Yes.

> But anyway wouldn't it be better to not count ads to begin with ?

We don't pre-fetch pages.

**Comment by elig0n** [comment]
> We don't pre-fetch pages.
I'm not sure I understand what that means. 
The parser can't deal with it ?

**Comment by jarun** [comment]
We fetch one page at a time. So when you open a search the first page is fetched. Many of the results are ads and those are not shown. We do not pre-fetch the second apge in advance to show you up to 10 results by combining results from the second page.

**Comment by elig0n** [comment]
but can the results counter skip ads ?

**Comment by jarun** [comment]
It skips ads. That's why they are now shown. I am not sure what you mean.

**Comment by zmwangx** [comment]
Not just ads, also some smart card results.
