### ISSUE TITLE
Possible to get total number of results for google news?'

### ISSUE THREAD

**Issue by onseau** [jarun/googler#340]
the number typically tops out at a few hundred for a given term on google news, so would it be possible to set results to 100 per page and run  loop to get to the last page and getting the total number of results?

**Comment by jarun** [comment]
Sorry, this has been discussed earlier. We do not support scripting as it's against google policies.

**Comment by onseau** [comment]
sorry i'm not a programmer.  what is scripting?  or specifically, what part of that should i try to avoid?  i don't understand

**Comment by onseau** [comment]
reason i'm asking is because i was doing this manually, so if i can't do that, could i use python to find the number of pages at least?  or get the number of results on the last page?  etc., then i can estimate from there.

**Comment by jarun** [comment]
You shouldn't try to fetch mass results from google in loop.

There's an unsupported patch to get the total number of results: https://github.com/jarun/googler/issues/144#issuecomment-260716097

Beyond that you are on your own.

**Comment by onseau** [comment]
thank you!!!

**Comment by onseau** [comment]
ahh ok.  problem is, it has to be done this way, because of how google calculates that number on the first page.  it drops exponentially until you reach the last page, where the actual reported number is accurate.  thank you anyway!  i'll look for another way.
