### ISSUE TITLE
News headline doesn't wrap correctly

### ISSUE THREAD

**Issue by jarun** [jarun/googler#349]
The headine for some news results do not wrap correctly.

```
$ googler -N cricket

 1.  'He has the ability of Virender Sehwag': Wasim Jaffer impressed with young 
India... [crickettimes.com]
     The Cricket Times, 13 hours ago
     Ever since leading India to U-19 World Cup triumph in 2018, Prithvi Shaw  has been making waves in
     the cricketing world as the youngster is ...

 2.  Twitter reacts to James Anderson letting out massive roar as Campbell 
exhausts DRS luck [sportscafe.in]
     SportsCafe, 1 day ago
     The United Nation was close to officially announcing July 9 as the  Holder-Campbell day, until James
     Anderson decided to try his luck to  bring ...
```

@zmwangx please take a look.

**Comment by zmwangx** [comment]
Lol they hard wrap it in HTML, wtf? What's the fucking point, it's like someone doesn't know HTML renderers collapse `[ \t\n\r]`.

<img width="665" alt="Screen Shot 2020-07-11 at 2 30 56 AM" src="https://user-images.githubusercontent.com/4149852/87187099-33484c00-c31f-11ea-8af6-4583c401fa97.png">

**Comment by zmwangx** [comment]
This is trivial at first sight but more involved when I actually sit down to write the fix. The thing is I want to collapse whitespace (`re.sub(r'[ \t\n\r]+', ' ', ...)`) everywhere, including the abstract, but I need to be careful and make sure it doesn't screw up offsets of matches.

Too late now, will finish later.

**Comment by jarun** [comment]
No hurry! :+1:
