### ISSUE TITLE
Ctrl-C doesn't interrupt program immediately on Windows when connection is slow/stuck

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#352]
So I had the pleasure of using googler on Windows. There was a connection problem to Google, and I further had the pleasure to experience the confusion of Ctrl-C seemingly doing nothing for more than ten seconds before a `KeyboardInterrupt` is processed eventually.

Of course it may not be easy for people to reproduce a connection problem to Google, but I wrote this simple TCP honeypot one can play with (all the code can be found in this gist, too: https://gist.github.com/zmwangx/9d4a730d881df4080cb7b1ee3046ee70):

```python
# A TCP honeypot listening on 127.0.0.1:8080 that stalls connections.

import socketserver
import time


class HoneypotServer(socketserver.TCPServer):
    # Stall each connection for 10 seconds.
    def get_request(self):
        time.sleep(10)
        return self.socket.accept()


def main():
    server = HoneypotServer(("127.0.0.1", 8080), socketserver.BaseRequestHandler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
```

Then, a very stripped down client doing a simple `HTTPSConnection.connect` would expose the problem:

```python
# A naive HTTPS client trying to connect to 127.0.0.1:8080.

import http.client


def main():
    conn = http.client.HTTPSConnection("127.0.0.1", 8080)
    try:
        conn.connect()
    except (OSError, KeyboardInterrupt):
        pass


if __name__ == "__main__":
    main()
```

Regardless of when you Ctrl-C on Windows, this would hang for 10 seconds.

**The fundamental problem is Python seemingly not being able to process an interrupt signal when it's blocked on socket operations like recv.**

It is said that Ctrl-Break would work better and interrupt immediately. I use an Apple Extended Keyboard which doesn't have these Windows keys, and remapping a function key to Break doesn't seem to have the desired effect, can't tell if it's a problem with the remapping or Ctrl-Break simply doesn't work as advertised here.

I don't actually have a solution here. I know for one that actual async programming with `asyncio` could solve the problem:

```python
# A async HTTPS client trying to connect to 127.0.0.1:8080.

import asyncio

import aiohttp


async def main():
    async with aiohttp.ClientSession() as client:
        try:
            async with client.get("https://127.0.0.1:8080/"):
                pass
        except aiohttp.ClientError:
            pass


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
```

Ctrl-C cleanly interrupts this on Windows. But this is apparently not suitable:

- Dependency on `aiohttp` since PSL asyncio only has [TCP primitives](https://docs.python.org/3/library/asyncio-stream.html);
- Probably will lose some low level flexibility like our `socket.create_connection` override for `-4`, `-6`;
- Got a whole other API, and blue/red functions to boot.

I assume other async solutions like gevent could work, too, but again it's dependencies, dependencies, dependencies.

Anyway, just putting this out there in case some Windows expert could fix the problem without external batteries.

**Comment by jarun** [comment]
@dertuxmalwieder could you help with this?

**Comment by dertuxmalwieder** [comment]
I’m not near a Windows machine right now, but @zmwangx is correct (as in: Ctrl+C has its quirks on Windows, Ctrl+Break should work).

**Comment by zmwangx** [comment]
Looked into this some more. Ctrl-Break (sending SIGBREAK) terminates programs alright, but doesn't leave room for cleanup or recovery. Curiously, unlike SIGKILL on *nix, it can be handled, but once I install a handler the behavior reverts back to blocking on recv.

I opened [bpo-41437](https://bugs.python.org/issue41437) to see if I can fish out a definitive answer from a core dev.

**Comment by jarun** [comment]
I don't see anyone working on this for a while and I don't see any issues. So closing this.
