### ISSUE TITLE
[FR] Add a way to add parameters to the Google URL

### ISSUE THREAD

**Issue by NightMachinary** [jarun/googler#365]
I want to extract the date a URL was last updated via Google. Currently, this information can be found in the metadata key of the JSON googler returns. The problem is that we need to add `&as_qdr=y19` to the search URL for some dates to be shown in Google. Currently there is no way to do this in googler.

**Comment by jarun** [comment]
We support quick date range (`qdr`) using the `-t` option. As I understand from the [developer docs](https://developers.google.com/custom-search/docs/xml_results), `as_qdr` is probably the same thing or almost similar. We can't add a parameter for every Google search option available. Please feel free to have your own patch. `googler` is quite stable and I don't see any reason to undergo significant modification in the near future.

**Comment by NightMachinary** [comment]
[**@jarun**](https://github.com/jarun) commented on [Sep 21, 2020, 4:35 PM GMT+3:30](https://github.com/jarun/googler/issues/365#issuecomment-696100808 "2020-09-21T13:05:27Z - Replied by Github Reply Comments"):
> We support quick date range (`qdr`) using the `-t` option. As I understand from the [developer docs](https://developers.google.com/custom-search/docs/xml_results), `as_qdr` is probably the same thing or almost similar.

Thanks, `--time` worked. 

> We can't add a parameter for every Google search option available. Please feel free to have your own patch. `googler` is quite stable and I don't see any reason to undergo significant modification in the near future.

I was thinking of a general `--add-to-url '&as_qdr=y19'` thingy. That wouldn't break the API. But I guess you're right that sending PRs for specific new parameters is a better approach.

**Comment by jarun** [comment]
No, I am not asking for a PR either. We do not want to have 100 options in `googler` so when a newbie sees the utility he runs away. Please have your own patch with yourself. I, for example, do not need it.
