### ISSUE TITLE
When using as a pipe command, feeding input to googler results in asking for input and initiating the query from pipe's input 

### ISSUE THREAD

**Issue by PatxiofromAlphensign** [jarun/googler#370]
just thought it would be a small bug to report.

Querying in a piped command, like this
`echo <input> | googler`
results in 
```
Please initiate a query.
googler (? for help)
```
followed by the desired output

**Comment by jarun** [comment]
`googler` is not written for scripted usage.
Please refer to https://support.google.com/webmasters/answer/66357?hl=en

**Comment by PatxiofromAlphensign** [comment]
Well, I wasn't really talking about automated queries or scripted usage I guess. It is that when running `googler` in a piped commands, it goes like this - it first thinks it has got no query input (so it asks `Please initiate a query.
googler (? for help)`, and then it outputs the whole search result just perfectly (feeded off `stdout`).

**Comment by jarun** [comment]
Just think of `googler` as a substitute of google web search. You open the browser, search for a term on google. Similarly with googler, the workflow is you open the terminal fire googler with your search term. We didn't really indent to do anything extra for more sophisticated use cases.
