### ISSUE TITLE
googler no results 10/4/20

### ISSUE THREAD

**Issue by mtv111** [jarun/googler#376]
googler 4.2 producing "no results" for most searches

[DEBUG] googler version 4.2
[DEBUG] Python version 3.8.5
[DEBUG] Platform: macOS-10.15.7-x86_64-i386-64bit

**Comment by rootid** [comment]
Same issue but it returns no result 
googler hello world --debug
[DEBUG] googler version 4.2
[DEBUG] Python version 3.8.5
[DEBUG] Platform: macOS-10.15.4-x86_64-i386-64bit
[DEBUG] Connecting to new host www.google.com
[DEBUG] Opened socket to 172.217.12.132:443
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=hello+world&sei=KFDldAaeEeuJCqzeSAARIg
[DEBUG] Cookie: 1P_JAR=2
[DEBUG] Response body written to '/var/folders/ws/6fvgzmpx5t9gds22jkp95v7h0000gn/T/googler-response-lr95wpz2.html'.
No results.
If you believe this is a bug, please review https://git.io/googler-no-results before submitting a bug report.
googler (? for help):

**Comment by jarun** [comment]
The fix is available on master. Keeping this defect open so others find it.

**Comment by mtv111** [comment]
sorry but could you provide a link to the fix? im not familiar with master

**Comment by jarun** [comment]
https://github.com/jarun/googler#from-source

**Comment by mtv111** [comment]
hmm not finding the fix. sorry but I don't use this that often so am not entirely sure of how to fix this. is there a terminal command I can run to fix this? thanks for the help

**Comment by jarun** [comment]
sudo curl -o /usr/local/bin/googler https://raw.githubusercontent.com/jarun/googler/master/googler && sudo chmod +x /usr/local/bin/googler

**Comment by mtv111** [comment]
perfect thank you. working now

**Comment by Strykar** [comment]
> The fix is available on master. Keeping this defect open so others find it.

Why not make a new release with the fix.. last one was in July?

**Comment by jarun** [comment]
It will have to wait till the weekend.
