### ISSUE TITLE
Steps to potentially support image search

### ISSUE THREAD

**Issue by bergercookie** [jarun/googler#384]
I'm aware of issue #360 and the fact that `googler` currently doesn't support image search.

I'm curious though, is this a technical limitation, or is it that one hasn't spent the time to implement this?
If it's the latter what would be the steps to add support for it?

Thanks

**Comment by jarun** [comment]
Primarily:

- we prefer to keep the utility textual
- there is no standard to render images on the terminal

**Comment by bergercookie** [comment]
But AFAIU there's nothing that stops the program from potentially fetching links to the google-suggested images and displays them (only the links) at stdout, right?

**Comment by jarun** [comment]
There's no point in supporting google image search without showing images. Links are too random to mean anything.

**Comment by zmwangx** [comment]
It's not like I haven't given this some substantial thought at one point.

- All UI ideas (including fetching the images, stitching them into larger grids and labelling them, opening in image viewer or even video player) I could come up with were utter garbage. Why not use an actual graphical and interactive application — a graphical web browser — for something inherently graphical and interactive?

- Google Images search returns image results including captions in a JS blob, so the architecture would be significantly different. The answer is probably regex, which takes the fragility to a whole new level.

Among all the rejected suggestions, image search would be a hard no.
