### ISSUE TITLE
Unable to user googler

### ISSUE THREAD

**Issue by Jacksole** [jarun/googler#389]
I just downloaded googler and I get this message when  
Traceback (most recent call last):
  File "/usr/bin/googler", line 41, in <module>
    import webbrowser
  File "/usr/lib/python3.6/webbrowser.py", line 628, in <module>
    cmd = _synthesize(cmdline, -1)
  File "/usr/lib/python3.6/webbrowser.py", line 83, in _synthesize
    cmd = browser.split()[0]
IndexError: list index out of range

I do have python3.6.9 and 3.8.2 and my WSL distro can with 2.7 on it has well.

**Comment by jarun** [comment]
googler version?

**Comment by jarun** [comment]
Anyway, if importing the module fails, I'm not sure we can do much.

**Comment by jarun** [comment]
Please take this to the python webbrowser module maintainers.

**Comment by Jacksole** [comment]
It was 3.5

**Comment by jarun** [comment]
The latest is v4.3.1.
