### ISSUE TITLE
Feature request: Add cli flag for url expansion

### ISSUE THREAD

**Issue by tobx** [jarun/googler#394]
Hello,

first of all: `googler` is great!

Since I really do not care about the URL, but only about the domain, I would like to set the short version as default without having to press <kbd>U</kbd> every time after opening `googler`.

Last but not least I have seen multiple issues regarding paging (#281):

I am using the integrated terminal when working with VSCode and elsewhere the default OS terminal. Those have different sizes so my current workaround is to have two bash aliases with different search result numbers. I do not like it though and terminal splits are not working.

Not having paging is like opening a PDF document always on the large page. Sure you can scroll up or even use a shortcut, but would that not be very strange?

Paging and automatic terminal size detection would be very helpful, but I understand that this is not in your interest and fully respect that I should code it if I need it. I will not though, because I am working on other projects right now.

Why I still mention that: for an even faster "Google experience" it would be nice to have the option to prefetch the next page. If that is an option for you to implement a cache for the search results, then this might lead the way to implement paging at any time later.

**Comment by jarun** [comment]
For the first question, please read the documentaiton: https://github.com/jarun/googler#domain-only-url

There has been many discussions around paging and terminal size detection already. Please refer to the issue threads for more context. If you ask me, I am accustomed to <kbd>Ctrl+Shift+PgUd</kbd> and <kbd>Ctrl+Shift+PgDn</kbd>. Probably see if you can simplify those in your terminal emulator.

**Comment by tobx** [comment]
Fair enough and thank you for the doc link, I have not seen it.
