### ISSUE TITLE
Update screenshot after prompt refresh

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#40]
Just a reminder: we should update the screenshot once we solidify the prompt refresh.

The screenshot could be optimized with `optipng` (or better yet, `zopflipng`) to reduce the size of the repo.

**Comment by jarun** [comment]
How about uploading to imgur and linking?

**Comment by zmwangx** [comment]
Sure.

**Comment by jarun** [comment]
Closed at https://github.com/jarun/googler/commit/e1938518e3091d3ff46684888d290caaa5e697de.
