### ISSUE TITLE
You can install googler with Awesome package manager

### ISSUE THREAD

**Issue by shinokada** [jarun/googler#406]
Hi, I created [Awesome package manager](https://github.com/shinokada/awesome) and I can install your repo using it.

After installing the Awesome:

```
awesome -i jarun/googler
```

If you can put it in your README, it will be awesome.

Thanks.

Shin

**Comment by jarun** [comment]
Why not submit it to https://repology.org? It would be available for everyone to see.

At least for `googler`, we are not adding packager-specific commands..
