### ISSUE TITLE
Abstract part incomplete result

### ISSUE THREAD

**Issue by mannan291** [jarun/googler#410]
The abstract part of the result comes incomplete when the date format comes in string. Here is the screenshot: 
![Screenshot_1](https://user-images.githubusercontent.com/83581864/124431988-84501c00-dd8a-11eb-9698-6a7cfb9c2ad7.png)

**Comment by jarun** [comment]
if you can fix it please raise a PR.

**Comment by jarun** [comment]
I am closing this as there is no response. Also, the next time you raise an issue on `googler`, please be more clear on what you searched, how you confirmed etc. I am not an expert web dev myself.
