### ISSUE TITLE
Wrong CONSENT cookie is set

### ISSUE THREAD

**Issue by einsJannis** [jarun/googler#411]
googler --count 3 --exact tyler --debug
[DEBUG] googler version 4.0
[DEBUG] Python version 3.8.5
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&nfpr=1&num=3&oe=UTF-8&q=tyler&sei=5eSyOgDSEey203FWodHKvQ
[DEBUG] Cookie: CONSENT=PENDING+188
[DEBUG] Response body written to '/tmp/googler-response-54z1p3zi.html'.
No results.
If you believe this is a bug, please review https://git.io/googler-no-results before submitting a bug report.
googler (? for help) 

[googler-response-54z1p3zi.html](https://gist.github.com/einsJannis/1278e172fb3a4c05bf13d1cc930ea076)

This is clearly a bug, I think the wrong CONSENT cookie is set

**Comment by jarun** [comment]
> This is clearly a bug, I think the wrong CONSENT cookie is set

Please raise a PR with the fix.
