### ISSUE TITLE
Understanding packaging

### ISSUE THREAD

**Issue by julkhami** [jarun/googler#412]
Hey,

I was wondering, why is googler packaged for operating systems rather than package managers?

I don't know much about either, but I thought a package manager held software in a certain configuration, regardless of what system it was being downloaded to. If that's not the case, then I guess package managers usually know what system they are downloading to and choose the right version accordingly? I don't think that's the case. Or is there always a strict correspondence between an OS and a package manager, i.e. Ubuntu should always use apt? Because I have used a few different package managers on my system, Termux - pkg, apt and maybe the snap store as well.

Also, why is googler only recommended for installation with a package manager for operating systems in newer versions? I.e., what happened, why is it not back-compatible?

Thanks very much.

**Comment by jarun** [comment]
That's the way it was done from the beginning. No other reason.
