### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by L-ian9** [jarun/googler#413]
└─# proxychains  ./googler -d                                                                                                 1 ⨯
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[DEBUG] googler version 3.9
[DEBUG] Python version 3.9.1
[DEBUG] Connecting to new host www.google.com
[proxychains] Strict chain  ...  192.168.124.14:10809  ...  www.google.com:443  ...  OK
Please initiate a query.
googler (? for help) ?

omniprompt keys:
  n, p                  fetch the next or previous set of search results
  index                 open the result corresponding to index in browser
  f                     jump to the first page
  o [index|range|a ...] open space-separated result indices, numeric ranges
                        (sitelinks unsupported in ranges), or all, in browser
                        open the current search in browser, if no arguments
  O [index|range|a ...] like key 'o', but try to open in a GUI browser
  g keywords            new Google search for 'keywords' with original options
                        should be used to search omniprompt keys and indices
  c index               copy url to clipboard
  u                     toggle url expansion
  q, ^D, double Enter   exit googler
  ?                     show omniprompt help
  *                     other inputs issue a new search with original options

我总是得到以下错误：
            └─# proxychains googler -C hello world | tee output                                                                           1 ⨯
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] Strict chain  ...  192.168.124.14:10809  ...  www.google.com:443  ...  OK
[proxychains] Strict chain  ...  192.168.124.14:10809  ...  www.google.com.hk:443  ...  OK
[ERROR] Failed to get 'https://www.google.com.hk/search?ie=UTF-8&oe=UTF-8&q=hello+world&sei=Mz0BGBP8EeyNXAAMKZtjcw'.

**Comment by jarun** [comment]
proxychains isn't tested. Please use the `-p PROXY` option.
