### ISSUE TITLE
New Design for Google News

### ISSUE THREAD

**Issue by y-shimada0402** [jarun/googler#415]
-N option is not working.
The /tmp/googler-response*.html output by --debug is retrieved.
Thanks for your help.

#### Bug reports
googler --upgrade
Downloading https://raw.githubusercontent.com/jarun/googler/v4.3.2/googler
Already up to date.

googler -N --debug COVID-19
[DEBUG] googler version 4.3.2
[DEBUG] Python version 3.8.10
[DEBUG] Platform: Linux-5.4.0-84-lowlatency-x86_64-with-glibc2.29
[DEBUG] Connecting to new host www.google.com
[DEBUG] Opened socket to 172.217.175.4:443
[DEBUG] new_connection completed in 0.081s
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=COVID-19&sei=cAjwph9ESeSOyzYBwXmcqw&tbm=nws
[DEBUG] Cookie: 1P_JAR=2021-09-15-04
[DEBUG] fetch_page completed in 1.298s
[DEBUG] Response body written to '/tmp/googler-response-kjib3xmq.html'.
[DEBUG] parse completed in 0.169s
No results.
[DEBUG] Fetching https://raw.githubusercontent.com/jarun/googler/master/info.json for project status...
If you believe this is a bug, please review https://git.io/googler-no-results before submitting a bug report.

Before opening an issue, please

💥💥TRY TO REPRODUCE ON [THE LATEST DEVELOPMENT VERSION][master] FIRST💥💥

The bug you noticed might have already been fixed.

[master]: https://github.com/jarun/googler#downloading-a-single-file

If the issue can be reproduced on master, then please make sure you provide the following:
- Output of `googler -d`;
- Link to the response body (you should see a line like `[DEBUG] Response body written to '/Volumes/ramdisk/googler-response-xxxxxxxx'` in the output of `googler -d`; please upload the file to a [gist](https://gist.github.com/) and include the gist's URL in the issue);
- Details of operating system, Python version used, terminal emulator and shell;
- `locale` output, if relevant. It's a good idea to set your locale to UFT-8. Please refer to [googler #131](https://github.com/jarun/googler/issues/131).

If we need more information and there is no communication from the bug reporter within 7 days from the date of request, we will close the issue. If you have relevant information, resume discussion any time.

#### Feature requests
Please consider contributing the feature back to `googler` yourself. Feel free to discuss. We are more than happy to help.

--- PLEASE DELETE THIS LINE AND EVERYTHING ABOVE ---

**Comment by rfaile313** [comment]
Can also confirm this is broken.

```
# googler --version
4.3.2

# googler business

 1.  Business - Wikipedia
     https://en.wikipedia.org/wiki/Business
     Business is the activity of making one's living or making money by producing or buying and selling products
     Simply put, it is "any activity or enterprise ...

 2.  Business - Insider
     https://www.businessinsider.com/
     Business Insider tells the global tech, finance, markets, media, healthcare, and strategy stories you want to
     know.

 3.  business.com: Expert Business Advice, Tips, and Resources
     https://www.business.com/
     Get the business advice, tips, and resources you need to run and grow your business.

 4.  Google My Business - Manage Your Business Profile
     https://www.google.com/business/
     Get your business listed on Google with a free Business Profile. See how you can turn people who find you on
     Search and Maps into new customers.

 5.  Business Definition - Investopedia
     https://www.investopedia.com/terms/b/business.asp
     A business is defined as an organization or enterprising entity engaged in commercial, industrial, or
     professional activities. Businesses can be for-profit ...

 6.  21 Great Small Business Ideas to Start in 2021
     https://www.businessnewsdaily.com/2747-great-business-ideas.html
     What are the most successful small businesses?
     Choose a business idea that you are knowledgeable and passionate about. Before starting a business, determine if
     there is a demand for what you want to provide.

 7.  Businessweek - Bloomberg
     https://www.bloomberg.com/businessweek
     Black-Owned Businesses Hope the Summer Boom Doesn't Fade · relates to Black Lives Matter Creates a Boom for
     Black-Owned Bookstores. Small Business ...

 8.  Small Business Administration
     https://www.sba.gov/
     We support America's small businesses. The SBA connects entrepreneurs with lenders and funding to help them plan,
     start and grow their business.

 9.  Business | City of San Jose
     https://www.sanjoseca.gov/business
     Updates on City of San José Services and/or Operations (English | Español | Tiếng Việt | 中文). COVID-19 Pandemic
     Help for Residents | Businesses | Nonprofits.

googler (? for help)

# googler business --news
No results.
If you believe this is a bug, please review https://git.io/googler-no-results before submitting a bug report.
googler (? for help)
```

> [DEBUG] googler version 4.3.2
> [DEBUG] Python version 3.6.9
> [DEBUG] Platform: Linux-4.15.0-144-generic-x86_64-with-Ubuntu-18.04-bionic

[Debug HTML output](https://gist.github.com/rfaile313/9c2d5a40de4b8be20a2c7700b1aa4c19)

**Comment by jarun** [comment]
If you care enough to contribute, please raise the PR.

**Comment by rfaile313** [comment]
@jarun howdy 👋 I poked around the binary a bit the other day before I posted, It was not super clear to me how to adjust for the changed news cards, it did not seem as trivial as adjusting a selector which is why I posted here. 

If you would not mind pointing me in the right direction I would be happy to test some local changes and cut a PR.

**Comment by jarun** [comment]
Please enable the debug flag and check the html response dumped. Open the same search in another device. Do you see the results in the dump? If yes, the parser needs to be modified to show the results. If not, the cards are javascript which needs many other changes.

**Comment by rfaile313** [comment]
@jarun ok thanks - submitted a PR with a fix👍

**Comment by jarun** [comment]
Thank you!

**Comment by y-shimada0402** [comment]
@rfaile313  san
I am grateful for your support.
Arigatou gozaimasu.
I’m studying English really hard, but I’m not very good at it.
I'm learning github.


> @jarun howdy wave I poked around the binary a bit the other day before I posted, It was not super clear to me how to adjust for the changed news cards, it did not seem as trivial as adjusting a selector which is why I posted here.
> 
> If you would not mind pointing me in the right direction I would be happy to test some local changes and cut a PR.
