### ISSUE TITLE
Search by filetype

### ISSUE THREAD

**Issue by bitcoinmeetups** [jarun/googler#422]
Hello,

I'm MB. A very nice and polite guy.

Search by filetype:

Search for a specific file type:

 googler instrumental filetype:mp3

Always generates nothing. Solution?

**Comment by jarun** [comment]
That's happening because even with the web search the results are only a few ads which googler filters out.

**Comment by jarun** [comment]
Probably media/mp3 is blacklisted. PDF works:

    googler filetype:pdf instrumental
