### ISSUE TITLE
No Results.

### ISSUE THREAD

**Issue by UnmeshDeshpande** [jarun/googler#427]
#### Bug reports

OS: Ubuntu 20.04LTS (Gnome DE)
Terminal: Tilix (Bash) [Googler installed via apt]
HWInfo: Ryzen 5 4600h; 8GB DDR4 3200MHz Single Channel; GTX 1650 Mobile (1f99); 512GB SSD 

Debug Output:
   $ googler --debug
[DEBUG] googler version 4.0
[DEBUG] Python version 3.8.10
[DEBUG] Connecting to new host www.google.com
Please initiate a query.
googler (? for help) google
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=google&sei=gM0vMkRzEeyv5KdiRAIkHA
[DEBUG] Cookie: CONSENT=PENDING+817
[DEBUG] Response body written to '/tmp/googler-response-jcvjscyv.html'.
No results.
If you believe this is a bug, please review https://git.io/googler-no-results before submitting a bug report.
googler (? for help)

**Comment by Beast12** [comment]
```
User@me:~$ googler -w github.com HomeAssistant --debug
[DEBUG] googler version 4.0
[DEBUG] Python version 3.8.10
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=HomeAssistant+site:github.com&sei=lbc0zkbaEeyIHDGdJGCg9Q
[DEBUG] Cookie: CONSENT=PENDING+633
[DEBUG] Response body written to '/tmp/googler-response-aub_tqf7.html'.
No results.
If you believe this is a bug, please review https://git.io/googler-no-results before submitting a bug report.
googler (? for help) 


```

Same here... Doesn't matter what I give as search... Always the same.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

Installed with APT

```
User@me:~$ googler --version
4.0

```

**Comment by jarun** [comment]
Do you guys read error messages? Did you go through the link https://git.io/googler-no-results?

Packaged version on Ubuntu is old.

**Comment by yucongo** [comment]
```bash
snap install googler
```
will install ``googler version 4.3.2`` (as of now) that works in ubuntu 18 and 20 while `apt install googler` installs  googler version 4.0.0 which would result in `no results`.

Hope this helps someone.

**Comment by Beast12** [comment]
Yes, this was the solution. Thanks!!
