### ISSUE TITLE
googler skipping first result for some searchs

### ISSUE THREAD

**Issue by mtv111** [jarun/googler#432]
made sure my googler is up to date today but this issue persists. you can see here that the first result is not listed in googler.
![googler skipping first results](https://user-images.githubusercontent.com/57563693/147517264-356e083a-08b4-4f01-b8e3-804db4222873.jpg)

**Comment by jarun** [comment]
The first result is ignored if it's an ad/promoted result. I am not seeing this with other search queries.

**Comment by mtv111** [comment]
is there a way to make it not ignore these results?

**Comment by jarun** [comment]
You can enable these in the parser. Just go through the code/inline comments.
