### ISSUE TITLE
News text missing (internal bug)

### ISSUE THREAD

**Issue by jarun** [jarun/googler#47]
Text is missing from news items. Try:

    $ googler -N keywords

**Comment by zmwangx** [comment]
Can you bit a little bit more specific? Also removed the irrelevant template text for you.

**Comment by zmwangx** [comment]
Ah I see what you mean now. So the body text is missing.

**Comment by zmwangx** [comment]
I checked the v2.1 tag and got the same thing, so it's not a regression or anything. Is this related to the 3rd div level problem you mentioned the other day?

**Comment by jarun** [comment]
Yep!

**Comment by jarun** [comment]
Instead of showing the full text snippet for news, the time and news source would be shown. The title would work as the news headlines and set the context.

Fixed at 34363795a521f369a384f6c52011d05af8e25cff.
