### ISSUE TITLE
googler with proxychains cannot open link with number of search result

### ISSUE THREAD

**Issue by roleyzhang** [jarun/googler#54]
#### Bug reports
I tried to use `googler -d` to watch what happened but nothing show on screen
- Output of `googler -d`
```
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.11
[proxychains] DLL init: proxychains-ng 4.11
[DEBUG] Base URL [/search?ie=UTF-8&oe=UTF-8&start=0&]
[DEBUG] Search URL [www.google.com : /search?ie=UTF-8&oe=UTF-8&start=0&q=mutt+tutorial]
[proxychains] Dynamic chain  ...  127.0.0.1:1080  ...  www.google.com:443  ...  OK
[DEBUG] Response body written to '/tmp/googler-response-lmyvnq9j'.
```
- Response body, something like `/tmp/googler-response-xxxxxx`
There is a lot of things in googler-response-xxxxxx
- Details of operating system, Python version used, terminal emulator and shell
My Python version: 3.5.1
OS: Arch linux x86_64 4.4.5-1-ARCH
Terminal: Urxvt v9.22
Shell: zsh
local: zh_CN.urf8.
  
Also I tested with tsocks with googler, that's ok, I can use number of search result to open page at my chromium.

**Comment by jarun** [comment]
Hi,

Can you please share the googler-response file? Or use a pastebin maybe?

**Comment by zmwangx** [comment]
I'm confused.

1. Define "nothing show on screen";
2. I've never used proxychains before. It prints directly to tty? How's that even possible? Did you really invoked googler as `googler -d mutt tutorial` and got that output, or were you chaining commands somehow? Please show the exact invocation.
3. "There is a lot of things in googler-response-xxxxxx" Not sure what that means. `/tmp/googler-response-lmyvnq9j` is a single file.
4. Define "also I tested with tsocks with googler".

**Comment by boldaslove007** [comment]
Http://www.w3.org/TR/NOTE-Sgml-xml-971215 world wide consortium 15 Dec-1997 jjc@jclark.comISO regulation number 176/CHARSET ISO 8879:1986(ENR CHARSET BASESET Markit://details?hl=en&ld=com--twitter.andriod&referrer=matclick_id%3D401672db4139b139b136ba10cf25179190072016032920954%26utm-campaighn%3D10861935528%26utm_Content%3DInternal%26utm_Medium%3DInternal%26utm_Source%3DDadMarketplace%Gtom_Term%3DInternal.   BASESET "ISO Regulation Number176//CHARSET thats all i know  i cant evan search for this shit its forbidden because its whats blocking me its like serching for my self after im dead
Zhiming Wang <notifications@github.com> wrote:
>I'm confused.
>
>1. Define "nothing show on screen";
>2. I've never used proxychains before. It prints directly to tty? How's that even possible? Did you really invoked googler as `googler -d mutt tutorial` and got that output, or were you chaining commands somehow? Please show the exact invocation.
>3. "There is a lot of things in googler-response-xxxxxx" Not sure what that means. `/tmp/googler-response-lmyvnq9j` is a single file.
>4. Define "also I tested with tsocks with googler".
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jarun/googler/issues/54#issuecomment-203241078


I'm confused.


Define "nothing show on screen";
I've never used proxychains before. It prints directly to tty? How's that even possible? Did you really invoked googler as googler -d mutt tutorial and got that output, or were you chaining commands somehow? Please show the exact invocation.
"There is a lot of things in googler-response-xxxxxx" Not sure what that means. /tmp/googler-response-lmyvnq9j is a single file.
Define "also I tested with tsocks with googler".

**Comment by jarun** [comment]
proxychains uses LD_PRELOAD.

**Comment by boldaslove007** [comment]
Arun Prakash Jana <notifications@github.com> wrote:
>proxychains uses LD_PRELOAD.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jarun/googler/issues/54#issuecomment-203324585


proxychains uses LD_PRELOAD.

**Comment by roleyzhang** [comment]
Hi guys,

Sorry for my horrible English, I uploaded my googler-response file which you can reference.
@zmwangx 
1. I mean that I use googler -d tried to find out what cause this issue, but no detail message show on the screen.
2. I list my steps:
    a. starting ssh tunnel & setting local socks5 proxy at 127.0.0.1 port 1080
    b. Using 'proxychains googler -d mutt setting -l en'
    c. The searching result show on screen which you can see the attached pic.
    d. I input the number which show on the searching result and Enter( If I use VPN or tsocks then the searching result will show on my chromium) but nothing happen.
3. I mean the googler-response-xxxxxx file has a lot of content, i don't know which can describe this issue.
4. I use tsocks with googler, the steps as same as proxychains:
    a. starting ssh tunnel & setting local socks5 proxy at 127.0.0.1 port 1080
    b. Using 'tsocks googler -d mutt setting -l en'


![2016-03-30-193704_944x469_scrot](https://cloud.githubusercontent.com/assets/2442381/14140993/e7a6e6c6-f6ae-11e5-8887-a0a874460181.png)

[googler-response-9zf7rdtt.zip](https://github.com/jarun/googler/files/195388/googler-response-9zf7rdtt.zip)

**Comment by jarun** [comment]
OK, understood that you are able to fetch the results fine. The response is fine too.

Which version of googler are you using?

1. When you enter the result number at omniprompt (with proxychains) does your browser open?
2. What happens in case of tsocks? Does the browser open?

3. If the browser opens in both the cases, is the URL shown in the browser same for both?

**Comment by zmwangx** [comment]
Without installing proxychains and learning how to set up a proxy with it, my first guess is it's eating or buffering stdin somehow. You could apply this patch:

```diff
diff --git a/googler b/googler
index 3b0fafd..139bb78 100755
--- a/googler
+++ b/googler
@@ -443,9 +443,11 @@ def show_omniprompt():
 
     message = "Enter n, p, result number or new keywords"
     if colorize:
-        return raw_input("\x1b[7m%s\x1b[0m " % message)
+        user_input = raw_input("\x1b[7m%s\x1b[0m " % message)
     else:
-        return raw_input("%s: " % message)
+        user_input = raw_input("%s: " % message)
+    debugp("Omniprompt input: %s" % user_input)
+    return user_input
 
 
 # Messaging wrappers
```

Then run `proxychains googler -d blah blah` again and enter a number at the prompt. If you don't see a line like

```
[DEBUG] Omniprompt input: 1
```

then it's probably proxychains' fault.

If you do see that line then it may or may not our fault. In that case, try to play with `Result.open`, for instance simplify it:

```diff
diff --git a/googler b/googler
index 3b0fafd..1362f9c 100755
--- a/googler
+++ b/googler
@@ -309,19 +309,7 @@ class Result:
             print("%s\n" % text.replace("\n", " "))
 
     def open(self):
-        _stderr = os.dup(2)
-        os.close(2)
-        _stdout = os.dup(1)
-        os.close(1)
-        fd = os.open(os.devnull, os.O_RDWR)
-        os.dup2(fd, 2)
-        os.dup2(fd, 1)
-        try:
-            webbrowser.open(self.url)
-        finally:
-            os.close(fd)
-            os.dup2(_stderr, 2)
-            os.dup2(_stdout, 1)
+        webbrowser.open(self.url)
 
 
 # Functions
```

**Comment by roleyzhang** [comment]
@jarun 
1. My chromium was opened when I enter the result number at omniprompt (with proxychains), no error show on the browser, just no new page has been opened. 
2. When I used tsocks, I input the number of searching result and pressed enter then my chromium will open a new page to show the content of searching result.
@zmwangx 
Thanks for your comment, I will try to patch googler and test it.

**Comment by jarun** [comment]
You mean the browser didn't even try to open any URL?
In that case, @zmwangx might be right.

**Comment by zmwangx** [comment]
> My chromium was opened when I enter the result number at omniprompt

If the browser does open, then we probably do get the input. Please try the aforementioned patches.

**Comment by zmwangx** [comment]
Ping?

**Comment by jarun** [comment]
Closing this one as we have a workaround in `tsocks`. Feel free to comment with additional information.
