### ISSUE TITLE
Shell completion scripts for googler

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#56]
**Update** (2016-04-10 10:18:11 PM PDT): See https://github.com/jarun/googler/issues/56#issuecomment-208165928 for the bash version.

---

I just wrote a tiny Zsh completion script for googler: https://github.com/zmwangx/googler/blob/zsh-completion/contrib/zsh/_googler. In case you don't use Zsh, below is a brief screencast for demonstration.

If you think this is something worth having, we can add it to `contrib/zsh`, and briefly mention it in README. I'll also make sure the Homebrew formula automatically installs it to `/usr/local/share/zsh/site-functions` starting from the next release.

[![asciicast](https://asciinema.org/a/3vxxl7gzy1ezoj9m2w5lz30it.png)](https://asciinema.org/a/3vxxl7gzy1ezoj9m2w5lz30it)

**Comment by shaggytwodope** [comment]
If this is included I'll add to the aur package. Just need a reminder... lol.

**Comment by jarun** [comment]
How about bash and fish completion scripts too?

**Comment by zmwangx** [comment]
I hardly know any fish, and while I know non-interactive bash very well, I never bothered to learn bash's inferior completion system (compared to Zsh). So just like the name "contrib" suggests, if someone is willing to contribute they of course could be included, but they probably won't come from me ;)

**Comment by zmwangx** [comment]
What shell do you use @jarun? Maybe you could write one for your shell?

**Comment by jarun** [comment]
No problem, that was just a suggestion. I use fish. Will take a look.

**Comment by jarun** [comment]
Looks like fish closely follows the bash way. Let's have the zsh completion in, and wait for someone else interested in picking it up.

**Comment by jarun** [comment]
Seems like `bash` doesn't support help text for completion.

**Comment by zmwangx** [comment]
Okay, I read the manual and wrote one for Bash.

https://github.com/zmwangx/googler/blob/shell-completions/contrib/bash/googler-completion.bash

It only completes option names. AFAIK that's about the best you can do in Bash.

> Seems like bash doesn't support help text for completion.

I think so. Could be wrong.

**Comment by jarun** [comment]
:+1:

**Comment by jarun** [comment]
BTW:

    # Do not complete non option names
    [[ $cur == -* ]] || return 1
isn't taken care of out of the box?

**Comment by zmwangx** [comment]
> isn't taken care of out of the box?

If I don't do this check, then

    googler TAB

will complete to

    googler -

I don't think one should try to complete options without an explicit `-`.

**Comment by jarun** [comment]
OK. After it completes to

    googler -

What about pressing another tab, as in:

    googler -[TAB]

(I am so sorry for asking this, I don't have a Linux system right now)

**Comment by zmwangx** [comment]
Pressing tab again lists options as expected. But my problem with that is one shouldn't complete to `-` in the first place. Positional arguments should have higher precedence than options, and in this case positional arguments are non-completable.

**Comment by jarun** [comment]
I guess when a user presses `TAB`, he is looking for options to provide before adding his keyword(s).

**Comment by zmwangx** [comment]
I have to disagree. I would rather take a rigorous approach: you can only complete an argument given a finite selection pool, and you can only partially complete an argument with an infinite pool if they share a common prefix. When you press TAB at `googler |` (`|` for cursor), the selection pool is infinite and they don't share a common prefix, so completing to `-` is artificially limiting the selection pool.

This is obvious in Zsh — when you press TAB at `googler |` you get an argument description "keyword" but no choices, and when you press TAB at `googler -|` you get option selection. In Bash this is more abstract due to lack of messages, but IMO the principle should still be the same.

**Comment by zmwangx** [comment]
(Principles and rigor are nice, but it ultimately depends on the convention. I don't know the convention in Bash.)

**Comment by jarun** [comment]
OK. Let's keep it your way. I guess some user would come back if they think otherwise.

**Comment by jarun** [comment]
Let's fish! c23fbf3df7d8c63efd3381496273f3511afbaef2

@shaggytwodope Sure! We'll remind you once we are ready. I missed your comment in the morning.

**Comment by zmwangx** [comment]
I looked at Fish's documentation and it seems that we may be able to do better (not sure if Fish can understand the full command line — like Zsh — or not, but at least it can be somewhat positionally aware). Anyway, I don't really care.

**Comment by zmwangx** [comment]
Submitted #57 for Bash and Zsh.

**Comment by jarun** [comment]
Closed at https://github.com/jarun/googler/commit/72f7171f7455c6fb5ca4d26eed2d7f283b603738.
