### ISSUE TITLE
2.3 release reminders

### ISSUE THREAD

**Issue by zmwangx** [jarun/googler#60]
I'm not pressuring you to cut a release; just trying to collect some reminders. @jarun Feel free to directly edit the top post.

- [x] Remove [Troubleshooting 1](https://github.com/jarun/googler#troubleshooting) from README.md (it should no longer be possible, and if it happens either the user is using an outdated version — in which case the issue template asks the user to try the latest version — or it's a new bug and/or an incomplete fix);

- [ ] Install shell completion scripts in the Homebrew formula ([this branch](https://github.com/zmwangx/homebrew-core/tree/googler-2.3));

- [x] Update image with new omniprompt;

- [x] Remind @shaggytwodope on AUR packaging.

**Comment by jarun** [comment]
- [ ] Update image with new omniprompt.

> I'm not pressuring you to cut a release

No probs, it's not happening before next weekend anyway ;).

**Comment by jarun** [comment]
I have taken care of item 1 and 3. Planning a release this weekend.

**Comment by zmwangx** [comment]
👍

**Comment by shaggytwodope** [comment]
Updated the -git package [here](https://aur.archlinux.org/packages/googler-git) and the completions seem to work great. Might even try using fish myself... lol. Will update main package accordingly when ready.

**Comment by jarun** [comment]
@shaggytwodope we will make a release this weekend, most probably tomorrow. Stay tuned! ;)

**Comment by jarun** [comment]
@shaggytwodope @zmwangx released v2.3. Things look quite stable.
Sorry, I couldn't complete the testing by morning. Got real sleepy around 4AM.

@shaggytwodope Fish shell is awesome. You may need to switch to bash for serious scripting. But productivity-wise Fish is kick-ass with its auto-completion for commands, manpages and history. Some way or other it will always pick up the stuff you wanted to type.

**Comment by shaggytwodope** [comment]
@jarun awesome, aur package updated. 

I will eventually give fish a try... need to find time to move from zsh.

**Comment by jarun** [comment]
Thank you! :+1:

**Comment by zmwangx** [comment]
Submitted https://github.com/Homebrew/homebrew-core/pull/558.

---

Speaking of shells, I've tried fish before and was not particularly impressed. It's a good shell out of the box, but that's pretty much it, there's not much room for improvement AFAIK; whereas Zsh is customizable in almost every fashion imaginable. When done right (this is important), there's more granularity in Zsh than in any other shell, especially in terms of completions. With the possible exceptions of syntax highlighting and predictive typing. There are zsh-syntax-highlighting and zsh-auto-suggestions, but I'm not at all impressed by those. Fortunately I'm not a fan of either feature. I find syntax highlighting in shell rather useless most of the time (shell commands are usually pretty simple and you don't need "googler" in blue to know it's a command; and when shell commands get complicated, especially with Zsh's rich expansion facilities, syntax highlighting can't keep up anyway) and even somewhat when the color jumps around the spectrum as you type (g red, go blue, goo red, goog red, googl red, google blue, googler blue...). As for predictive typing, completion system does most of the job, and if I'm typing something over and over which can't be helped by the completion system, I'll just make an alias (sometimes directory local ones, I have a ton of those), problem solved.

My other problem with fish is its non-POSIX syntax. I can't copy from the command line into scripts and vice versa, and that's very counter-productive, considering how many scripts I write.

---

By the way, I seriously suggest serious scripting in Zsh instead of Bash. Zsh's [expansions](http://zsh.sourceforge.net/Doc/Release/Expansion.html) are so rich, they simply work wonders and save you tons of time. On the very surface level, not having to quote parameter expansion, and being able to expand an array with `$array` instead of `${array[@]}` are already big wins both in productivity and security. I'll just give one (ubiquitous) example of why it's superior to Bash for scripting. When you write scripts you often want to know where the absolute path of the script in order to call other scripts from the same or related directories, and find data in relevant location. (Very simple demand, [the single most upvoted bash question on SO](https://stackoverflow.com/questions/tagged/bash?sort=votes).) In Zsh this is as simple as

```zsh
here=$0:A:h
```

`:A` for expanding to the absolute path, `:h` for taking the dirname. In Bash this is almost mission impossible, unless you write a path resolver (which is of course possible in pure bash, but good luck doing that in every single script). You can try external commands, say `readlink` or `realpath`, but there's no cross-platform way to do it, because `realpath` is not always available, and BSD `readlink` is incompatible with coreutils `readlink`. Neither is POSIX anyway. In the end I usually just resort to Perl:

```bash
here="$(perl -e 'use File::Basename; use Cwd "abs_path"; print dirname(abs_path(@ARGV[0]));' -- "$0")"
```

Very sad.

**Comment by jarun** [comment]
Looks like I have to try out Zsh.

Thanks for the cool release guys! I am happy with where we have reached so far with `googler`.

**Comment by zmwangx** [comment]
> Looks like I have to try out Zsh.

No obligation, interactive shell is mostly a personal preference. Fish to Zsh is definitely a hard sell, it's almost impossible to convince someone to dig into configurations once he's used to an excellent out-of-box experience; but to me, Zsh configuration is almost an art 😃 If you do want to try Zsh though, make sure to take a look at https://github.com/sorin-ionescu/prezto/ .

I feel stronger about Zsh vs Bash for noninteractive use. IMO there's hardly any reason to use Bash over Zsh beyond availability (which isn't a problem for personal use), so do try to write Zsh for personal scripts, you'll enjoy it.

**Comment by zmwangx** [comment]
Merged in Homebrew 😃 

![screen shot 2016-04-23 at 10 19 49 am](https://cloud.githubusercontent.com/assets/4149852/14762973/f8ecdf76-093c-11e6-80c3-9322572c8549.png)

**Comment by jarun** [comment]
:+1:
