### ISSUE TITLE
Suppress Omniprompt

### ISSUE THREAD

**Issue by spamwalter** [jarun/googler#72]
I am automating a bunch of searches and redirecting the results to text files.  I would like the option to suppress the Omniprompt text from the results.

By this I mean I do not want the text "Enter n, p, result number or new keywords (? for help):" to appear at the end of the file.

Also, it seems to wait for user input even when output is redirected.  I'd like the option to suppress the omniprompt entirely.

Thank you.

**Comment by jarun** [comment]
I guess if we provide an option to disable omniprompt your second problem will also resolved. Does that work for you?

Also, before further discussion with the team I can't commit that we'll be exposing the above option in help or man (IF we add any). Is that OK?

**Comment by spamwalter** [comment]
Hi!

It would be better, but not best in my opinion.  With grep, my calling script (Python) can get an exception without looking at the output:


    try:
        sPathHits = subprocess.check_output(["grep", "-EniIrw", sTerm, sTextPath], universal_newlines=False)
    except subprocess.CalledProcessError:
        # no hits
        ... do something else...

I can’t do this for googler.  This is a little easier for me than checking for empty output, if only for the sake of consistency.

THANK YOU

Walter.

**Comment by jarun** [comment]
> With grep, my calling script (Python) can get an exception without looking at the output

Please elaborate a little more. If you are redirecting the text to a file before calling the subprocess, why would grep miss the text? If you are worried about timing, why not add a few seconds of delay? or ami I missing the point completely?

Also, if you can spare some time, feel free to raise a PR (now that I know you are a Pythonsia ;)).

**Comment by spamwalter** [comment]
Hi!

Sorry, my issue applies when redirecting from the command line, but it also applies when capturing output from a subprocess in Python.

The code I sent you just searches for a pattern in a folder and captures the output.  It doesn’t redirect the before calling the subprocess.  t want to be able to detect the no-hit case using the exit code (Python’s check_output does this behind the scenes.)

I’m not worrying about the timing.

Does that make sense.

What is a PR?

Thanks,

Walter.

**Comment by jarun** [comment]
PR: Pull Request. You can modify `googler` for your needs and raise a pull request on GitHub to incorporate the code.

**Comment by spamwalter** [comment]
Ah-ha

I am just working around this for now. I will consider modifying it if I need to use it on another project.

I really appreciate this tool.  It is already great!

W..

**Comment by zmwangx** [comment]
This is a reasonable request, and we can add a `--non-interactive` option. I'm fine with exposing it.

**Comment by zmwangx** [comment]
As for waiting for user request, just redirect stdin to `/dev/null`. See https://github.com/jarun/googler/blob/master/tests/test for running googler in batch (the only thing impossible for now is to suppress prompt display).

**Comment by zmwangx** [comment]
Re grep: There's no consistency, because your code itself is flawed. `grep` failed doesn't imply there's no hit; it could mean `grep` just failed. See `EXIT STATUS` section in `man 1 grep`. Also, let's keep this discussion in #73. There I detail why that's not a reasonable request, and why you can't just use `grep` as an example.

**Comment by zmwangx** [comment]
I submitted #74 to fix this. It's as simple as a new `--noninteractive` option. Feel free to give it a try.

**Comment by jarun** [comment]
Fixed at 210185425bf2f32dd3664c612395eb5845828a34.
